dropbox/pyston

src/runtime/long.cpp

This is a simple fix for #167, it passes ``make check``. I am not sure if I should test the GC but again, I don't really know how to test the GC.

fixing #167: using gc allocator for gmp

---

src/runtime/str.cpp
test/tests/str_functions.py

Implement `str` functions `ljust`, `rjust`, and `center`.

Str just funcs

---

src/core/stringpool.h

add the asserts back into stringpool

---

minibenchmarks/deltablue.py
minibenchmarks/richards.py

a couple more benchmarks from various python (and v8, smalltalk, etc) suites, which work but could be faster

add richards.py and deltablue.py minibenchmarks

---

src/runtime/builtin_modules/pyston.cpp
src/runtime/types.cpp
src/runtime/types.h

it lets scripts control some of the internal options
will be used for interpreter performance tracking

Add the '__pyston__' module

---

src/runtime/objmodel.cpp
src/runtime/types.cpp
src/runtime/types.h
test/tests/classname.py
test/tests/descriptors_getset_ics.py

- Implement setting for getset descriptors
- Implement setting for `__name__` for types
- Reenable test case the `classname.py` test

Getset set

---

src/codegen/unwinding.cpp

for -I and 'import optparse' this will result in about 5% speedup

Unwinding: remember the bounds of the interpreter function

---

src/core/threading.cpp
src/runtime/str.cpp

- make ```str.join()``` faster
- make ```yield``` faster

Smaller performance improvements for fasta

---

CMakeLists.txt
Makefile
src/CMakeLists.txt
src/codegen/unwinding.cpp
src/runtime/ctxswitching.S
src/runtime/ctxswitching.h
src/runtime/generator.cpp
src/runtime/types.h

This is a huge speed improvement for generators,
fasta.py takes 8secs now instead of 18secs

New context switching code for generators

---

src/runtime/builtin_modules/builtins.cpp
src/runtime/objmodel.cpp
src/runtime/objmodel.h

Teach len() howto rewrite itself

---

src/codegen/compvars.cpp

Convert the integer to a float and then let the float code handle the operation
With this change the type analysis is also able to comprehend that
e.g. '1 - <float>' will return a float
This means that the math operations in the 'linear_combination' function in chaos.py
get completely inlined.
-5% on chaos.py
```python
def linear_combination(self, other, l1, l2=None):
if l2 is None:
l2 = 1 - l1
v = GVector(self.x * l1 + other.x * l2,
self.y * l1 + other.y * l2,
self.z * l1 + other.z * l2)
```

compvar: add int <op> float handling

---

Makefile
from_cpython/CMakeLists.txt
from_cpython/Include/Python.h
from_cpython/Include/codecs.h
from_cpython/Include/unicodeobject.h
from_cpython/Lib/encodings/__init__.py
minibenchmarks/pyaes.py
src/capi/abstract.cpp
src/capi/codecs.cpp
src/capi/modsupport.cpp
src/runtime/builtin_modules/builtins.cpp
src/runtime/builtin_modules/sys.cpp
src/runtime/capi.cpp
src/runtime/import.cpp
src/runtime/str.cpp
src/runtime/tuple.cpp
src/runtime/types.cpp
src/runtime/unicode.cpp
test/tests/optparse_test.py
test/tests/str_encode_decode.py
test/tests/sys_test.py

This is not yet ready for merging (but ```"".encode("base64")``` is working) but I would like to get some feedback on how I have to implement ```__import__(,level=0)``` correctly. The import code is confusing me...
Notes:
- ```import optparse``` starts to fail because with this change we are able to import locale.py (which will use functools) and will set ```__name__``` so this depends on #292.
-  #292 brings it further but then it can't find ```__dict__```. haven't yet looked into what's missing.
- I did not yet check if ```PyString_Repr``` has the same behaviour
- I undefined unicode support
- pyaes.py works
- have to test more stuff

import codec module

---

test/tests/unicode_test.py

I was trying out the new unicode support and thought we may want to add this small test.

add small unicode encoding test

---

src/core/cfg.cpp
test/tests/del_multi.py

Finally I hope I did it correctly this time :)

Fixes issue #294

---

src/runtime/int.cpp

after #350 is merged, this is all that's required to get `import json` succeed.

copy _PyInt_Format implementation from cpython

---

src/asm_writing/rewriter.h
src/codegen/irgen/irgenerator.cpp
test/tests/json_test.py

test is basically the contents of this page: https://docs.python.org/2/library/json.html

add a json test and get it running

---

src/runtime/builtin_modules/builtins.cpp
src/runtime/file.cpp
src/runtime/import.cpp
src/runtime/int.cpp
src/runtime/long.cpp
src/runtime/long.h
src/runtime/str.cpp
test/tests/builtins.py
test/tests/imp_test.py
test/tests/intmethods.py
test/tests/long.py

Add imp.load_module() and next() support
The ```imp.load_module()``` just supports a specific type virtualenv needs for now.

virtualenv fixes

---

from_cpython/Modules/_struct.c
src/runtime/inline/tuple.cpp
src/runtime/long.cpp
src/runtime/tuple.cpp
test/tests/long.py
test/tests/tuples.py
test/tests/uuid_test.py

This are fixes for virtualenv...

Add a few 'long' methods, support tuple sublasses, add uuid test and fix a _struct GC bug

---

from_cpython/Include/pyport.h
from_cpython/Modules/getpath.c
from_cpython/Modules/zipimport.c

Removes the hack outlined in a comment to #356

Move stat.h include into pyport.h

---

from_cpython/Include/object.h
src/capi/object.cpp
src/capi/typeobject.cpp
src/runtime/builtin_modules/thread.cpp
src/runtime/capi.cpp
src/runtime/objmodel.cpp
test/test_extension/slots_test.c
test/tests/capi_slots.py
test/tests/setattr.py
test/tests/threading_local.py

Don't feel like this is ready to merge yet, mostly looking for comments. I'm dissatisfied with the reentrancy involving setattrInternal+PyObject_GenericSetAttr.

__setattr_ and thread._local

---

from_cpython/Include/pyconfig.h
minibenchmarks/iobench.py
src/capi/abstract.cpp
src/capi/modsupport.cpp
src/codegen/ast_interpreter.cpp
src/codegen/irgen.cpp
src/codegen/irgen/hooks.cpp
src/core/types.h
src/runtime/builtin_modules/builtins.cpp
src/runtime/float.cpp
src/runtime/import.cpp
src/runtime/int.cpp
src/runtime/long.cpp
src/runtime/types.cpp
src/runtime/types.h
test/tests/docstrings.py
test/tests/test_package/__init__.py
test/tests/trunc_test.py

a few small additions to get iobench.py working.
The `__doc__` change (46773ef) is wrong for a couple reasons, the biggest of which is that it's only set in the interpreter: The `-n` command line flag results in no doc strings.  Where should this go instead?  `wrapFunction`?

get iobench.py working

---

docs/INSTALLING.md

I created a new virtualbox ubuntu14.04 machine, and found `libsqlite3-dev` is needed, but not been installed on the installing document.

update INSTALLING.md, and libsqlite-dev in cmake section

---

src/capi/abstract.cpp
src/codegen/ast_interpreter.cpp
src/runtime/builtin_modules/builtins.cpp
src/runtime/iterobject.cpp
src/runtime/long.cpp
src/runtime/objmodel.cpp
test/tests/itertools_test.py
test/tests/long.py
test/tests/reversed.py
test/tests/with_exit.py

Please have a look at the individual commits...

Misc fixes for pip part 3

---

from_cpython/Lib/distutils/command/install.py
from_cpython/Modules/zipimport.c
src/analysis/scoping_analysis.cpp
src/runtime/capi.cpp
src/runtime/objmodel.cpp
src/runtime/objmodel.h

Hopefully one of the last sets of patches required.
- Update libpypa to fix another missing newline at end of file bug.
- Set distutils package install directory
- zipimporter: Ignore bytecode files inside archives (This let's them still load if the souce file can get found)

Misc fixes for virtualenv / pip

---

from_cpython/Include/object.h
src/gc/roots.h

no usage of StackRoot<> yet, just getting the definition in for the coming work.

add StackRoot<> and #defines for DECREF

---

tools/tester.py

This is pretty useful for me since there are a few flaky tests

add option to tester script to skip specified tests

---

src/runtime/generator.cpp

also, don't register MAX_STACK_SIZE bytes with the GC, register INITIAL_STACK_SIZE.
----
splitting this out from #422 to get it in sooner, since it's more likely to have a large impact with the big-app work than the other fixes.
```
pyston (calibration)                      :    1.0s baseline: 1.0 (-0.3%)
pyston django_migrate.py                  :    5.9s baseline: 10.7 (-45.1%)
pyston interp2.py                         :    6.0s baseline: 5.9 (+1.6%)
pyston raytrace.py                        :    6.6s baseline: 6.8 (-1.7%)
pyston nbody.py                           :    8.9s baseline: 9.3 (-4.0%)
pyston fannkuch.py                        :    8.1s baseline: 8.0 (+0.7%)
pyston chaos.py                           :   21.5s baseline: 20.5 (+5.2%)
pyston fasta.py                           : …
```

free generator stacks both in the destructor and when a generator exits.

---

src/codegen/unwinding.cpp

with this we drop from 50ms to 20ms for django requests.  I expect it'll help other things as well, with bigger impact the more functions we jit.

use a binary search to find/insert CompiledFunction*'s into the registry

---

from_cpython/Lib/logging/__init__.py
src/codegen/unwinding.cpp
src/codegen/unwinding.h
src/runtime/builtin_modules/sys.cpp
src/runtime/code.cpp
src/runtime/frame.cpp
src/runtime/types.cpp
src/runtime/types.h
test/tests/logging_test.py
test/tests/sys_getframe1.py
test/tests/sys_getframe2.py

implement sys._getframe + frame objects, and add co_name/co_filename properties to code object
also rework a bit of the logging module to use only sys._getframe, not f_back.

sys._getframe + frame objects

---

src/runtime/types.cpp

Fixes the issue with `file->f_encoding` being collected in #424.

Attach BoxedFile::gcHandler.

---

from_cpython/Lib/distutils/sysconfig.py
src/runtime/builtin_modules/sys.cpp
src/runtime/str.cpp
test/tests/str_functions.py

Small fixes for getting pyxl to work. Next step is teaching pypa about "# coding".

Set correct site-package directory, fix 'str * -1', add sys.dont_write_bytecode

---

.travis.yml
CMakeLists.txt

Currently ninja-build isn't in the travis apt whitelist.
If this works we get ccache in travis!

Switch travis-ci to docker infrastructure

---

CMakeLists.txt

@dagar says there's some intermittent failures here but I'd like to track them down.

Increase test parallelism on pyston_old_parser

---

src/codegen/compvars.cpp
src/codegen/entry.cpp
src/codegen/irgen/irgenerator.cpp
src/core/types.h

With these get down to 0 cache misses on a simple django test

Jit cache misses

---

from_cpython/Lib/types.py
src/codegen/irgen/hooks.cpp
src/runtime/builtin_modules/sys.cpp
src/runtime/capi.cpp
src/runtime/capi.h
src/runtime/objmodel.cpp
test/cpython/NOTES.org
test/tests/doctest_test.py
test/tests/many_attrs_setattr.py
test/tests/sys_test.py

Unfortunately not that many more tests are passing, but a bunch of them get farther than they used to.

Take another pass over the CPython test suite

---

src/analysis/function_analysis.cpp
src/codegen/irgen/irgenerator.cpp
src/codegen/irgen/util.cpp
src/codegen/irgen/util.h

Some (smaller) speed-ups.
```
For test/integration/django_test.py:
us_compiling_analysis_liveness: 103369 --> 18156
us_compiling_analysis_phis: 190171 --> 25232
us_compiling_irgen: 153015 --> 101026
```

Speed-up analysis and irgen

---

docs/INSTALLING.md

pkg-config is needed to run the virtualenv_test

add pkg-config to the install instructions

---

from_cpython/Include/pyconfig.h
from_cpython/Objects/stringobject.c
src/runtime/list.cpp
src/runtime/long.cpp
src/runtime/set.cpp
src/runtime/str.cpp
src/runtime/types.cpp
test/tests/copy_test.py
test/tests/long.py
test/tests/unicode_test.py

- fix crash when calling ```copy.deepcopy()```
- add ```long.__floordiv__```
- use ```str.join``` from cpython which supports unicode and doesn't accept non string arguments.
- support ```set``` subclasses
- ```listIAdd()``` can return a subclass from a list

Fix misc smaller issues

---

Makefile
from_cpython/Include/Python.h
src/CMakeLists.txt
src/analysis/scoping_analysis.cpp
src/analysis/scoping_analysis.h
src/codegen/codegen.cpp
src/codegen/irgen/hooks.cpp
src/codegen/irgen/hooks.h
src/core/types.h
src/gc/heap.h
src/runtime/builtin_modules/ast.cpp
src/runtime/builtin_modules/builtins.cpp
src/runtime/import.cpp
src/runtime/types.cpp
src/runtime/types.h
test/tests/ast_test.py
test/tests/compile_eval.py
test/tests/functions.py
test/tests/instance_methods.py
test/unittests/analysis.cpp
tools/tester.py

And a couple other things for sqlalchemy, though it's not working yet.

support ast.parse and 3-arg eval()

---

src/runtime/float.cpp
test/tests/float.py

`cpython/test_decimal.py` gets a little farther

implement float.__getformat__

---

from_cpython/Include/pyconfig.h
minibenchmarks/django-template.py
src/capi/descrobject.cpp
src/capi/typeobject.cpp
src/capi/types.h
src/codegen/ast_interpreter.cpp
src/codegen/entry.cpp
src/codegen/irgen/hooks.cpp
src/codegen/parser.cpp
src/codegen/unwinding.cpp
src/core/stats.cpp
src/core/stats.h
src/core/types.h
src/core/util.cpp
src/core/util.h
src/gc/collector.cpp
src/gc/gc_alloc.h
src/jit.cpp
src/runtime/builtin_modules/builtins.cpp
src/runtime/dict.cpp
src/runtime/generator.cpp
src/runtime/list.cpp
src/runtime/objmodel.cpp
src/runtime/stacktrace.cpp
src/runtime/str.cpp
src/runtime/tuple.cpp
src/runtime/types.cpp
src/runtime/types.h

Each thread has a stack of timers (which should have automatic storage.)  creating a timer starts it and pushes it onto the stack, and also pauses the currently running one (if there is one) to avoid double counting.  When a timer goes out of scope it's stopped and popped off the stack, and the previous one on the stack is resumed.

Stat timers

---

from_cpython/Include/pyconfig.h
from_cpython/Modules/_collectionsmodule.c
src/capi/abstract.cpp
src/capi/float.cpp
src/runtime/builtin_modules/builtins.cpp
src/runtime/int.cpp
src/runtime/iterobject.cpp
src/runtime/list.cpp
src/runtime/long.cpp
src/runtime/str.cpp
src/runtime/types.cpp
test/tests/builtins.py
test/tests/intmethods.py
test/tests/list.py

- Add ```round(x,d)```
- handle ```int << int``` overflow, 
- fix ```int(9223372036854775808, 0)```
- add support for assigning a generator to a list slice
...

Misc bugfixes and features for protobuf

---

src/runtime/builtin_modules/builtins.cpp
test/tests/intern.py

Implement intern() builtin function.

---

from_cpython/Include/descrobject.h
src/capi/errors.cpp
src/core/options.cpp
src/jit.cpp
src/runtime/capi.cpp
src/runtime/file.cpp
src/runtime/stacktrace.cpp
src/runtime/types.cpp
test/tests/dash_m.py
test/tests/dir.py
test/tests/file.py
test/tests/file_closed.py
test/tests/import_target.py
test/tests/oldstyle_classes.py

and some exceptions work to support `pyston -m pydoc`

-m support

---

src/runtime/types.cpp

oops, forgot to do this earlier!

visit im_class in gc handler

---

.gitmodules
src/codegen/ast_interpreter.cpp
src/codegen/irgen/irgenerator.cpp
src/core/types.h
src/runtime/builtin_modules/sys.cpp
src/runtime/code.cpp
src/runtime/import.cpp
src/runtime/int.cpp
src/runtime/objmodel.cpp
src/runtime/objmodel.h
src/runtime/set.cpp
src/runtime/stacktrace.cpp
src/runtime/types.cpp
src/runtime/types.h
test/integration/sqlalchemy_test.py
test/tests/code_test.py
test/tests/imp_test.py
test/tests/intmethods.py
test/tests/module_subclassing.py
test/tests/override_assertionerror.py
test/tests/set.py
test/tests/sys_modules_replacement_target.py
test/tests/sys_modules_replacement_test.py
test/tests/unicode_test.py

getting stuck trying to get pytest (their test runner) to work.  I wonder what you are not allowed to override in python.

Sqlalchemy tests

---

src/runtime/builtin_modules/sys.cpp
src/runtime/types.h
test/tests/sys_test.py

Fix "sys.excepthook is missing" warnings

---

src/runtime/builtin_modules/builtins.cpp
test/tests/input.py

Implement built-in input() function.

---

tools/lint.py

sometimes it's helpful to add a comment after an `#include` to say what it's for. This makes the linter understand that.

fix linter to allow comments after includes

---

src/analysis/scoping_analysis.cpp
src/codegen/irgen/hooks.cpp
src/core/cfg.cpp
src/core/types.h
test/tests/arg_unpacking.py
test/tests/global_and_local.py
test/tests/no_newline.py
test/unittests/analysis.cpp

Support arg unpacking
This doesn't work for single-element tuples, due to a bug in pypa. (I submitted a PR to dropbox/libpypa to fix this.)

support arg unpacking

---

Makefile
from_cpython/CMakeLists.txt
from_cpython/Include/floatobject.h
from_cpython/Include/pyport.h
from_cpython/Objects/floatobject.c
src/runtime/float.cpp
src/runtime/types.h
test/tests/float.py

implement float.hex and float.fromhex

---

src/runtime/long.cpp
test/tests/long.py

implement long.__pos__

---

from_cpython/Objects/floatobject.c
from_cpython/Objects/stringobject.c
src/runtime/builtin_modules/builtins.cpp
src/runtime/float.cpp
src/runtime/str.cpp
test/tests/builtins.py

along with implementation of `__format__` for `float` and `str`.

builtin format

---

src/codegen/parse_ast.py
src/codegen/parser.cpp
src/codegen/serialize_ast.cpp
test/tests/decimal_test.py
test/tests/decorator_whitespace.py
test/tests/parsing_bom.py
test/tests/super_long_string.py

- byte order marker
- newline between decorator and its function
- strings with size >64k [including a fix]
also, a decimal.Decimal test

Add some parsing tests

---

src/capi/typeobject.cpp
src/runtime/builtin_modules/builtins.cpp
src/runtime/capi.cpp
src/runtime/dict.cpp
src/runtime/int.cpp
src/runtime/objmodel.cpp
src/runtime/objmodel.h
src/runtime/tuple.cpp
src/runtime/types.cpp

We weren't even doing any rewriting for hash, so there's not much
downside.  This also cuts down on boxing quite a bit since
we can usually avoid boxing the hash value.

Switch hash to using tp_hash

---

CMakeLists.txt

remove the redundant -Wno-sign-compare

remove redundant -Wno-sign-cmopare

---

Makefile
from_cpython/CMakeLists.txt
from_cpython/Modules/_elementtree.c
from_cpython/setup.py
src/gc/heap.h
src/runtime/long.cpp
test/tests/decorator_whitespace.py
test/tests/dict.py
test/tests/elementree_test.py

- _elementtree has currently better perf than the python implementation

Add the _elementtree and update libpypa

---

src/runtime/generator.cpp

This is a small perf improvement for django-template.py: took  7.4ms for last iteration from 8.2ms

Generator: don't generate the traceback for the StopIteration exc when the generator is exiting back to a hasnext call.

---

src/codegen/ast_interpreter.cpp
src/codegen/ast_interpreter.h
src/codegen/irgen/irgenerator.cpp
src/core/types.h
src/gc/collector.cpp
src/runtime/types.cpp
test/tests/generator_collection_finally.py
test/tests/generator_collection_running.py

This is not yet ready but I would like to get early feedback from travis-ci.

free generator even if the don't exit

---

src/capi/descrobject.cpp
src/capi/typeobject.cpp
src/capi/types.h
src/codegen/ast_interpreter.cpp
src/codegen/irgen/hooks.cpp
src/codegen/parser.cpp
src/codegen/unwinding.cpp
src/core/stats.h
src/gc/collector.cpp
src/jit.cpp
src/runtime/builtin_modules/builtins.cpp
src/runtime/builtin_modules/thread.cpp
src/runtime/dict.cpp
src/runtime/generator.cpp
src/runtime/list.cpp
src/runtime/objmodel.cpp
src/runtime/str.cpp
src/runtime/tuple.cpp
src/runtime/types.cpp

Add some more stats and add a new "avoidability" system to try to do better rollups.

Playing with stattimers

---

src/capi/descrobject.cpp
src/capi/types.h
src/runtime/capi.cpp
src/runtime/objmodel.cpp
src/runtime/types.cpp

```
django_template.py             6.4s (2)             6.3s (2)  -1.4%
pyxl_bench.py             4.6s (2)             4.4s (2)  -4.4%
sqlalchemy_imperative.py             2.4s (2)             2.4s (2)  +0.3%
django_migrate.py             2.0s (2)             2.0s (2)  -1.2%
virtualenv_bench.py             8.2s (2)             8.2s (2)  -0.8%
geomean                 4.1s                 4.0s  -1.5%
```

Some more perf hunting

---

CMakeLists.txt

Add debug symbols to release mode.

---

.travis.yml

Fixes https://travis-ci.org/dropbox/pyston/jobs/67604256.

travis-ci compile and test in single step

---

microbenchmarks/itertools_chain_bench.py
src/core/stats.cpp
src/core/stats.h
src/runtime/cxx_unwind.cpp
src/runtime/descr.cpp
src/runtime/types.h

Wanted to get this PR in mostly for the new stats, but I guess it has a minor perf impact as well:
```
django_template.py             5.2s (2)             5.1s (2)  -2.3%
pyxl_bench.py             4.1s (2)             4.1s (2)  +1.0%
sqlalchemy_imperative2.py             5.7s (2)             5.6s (2)  -1.4%
django_migrate.py             1.9s (2)             1.9s (2)  -2.9%
virtualenv_bench.py             8.0s (2)             8.0s (2)  -0.6%
geomean                 4.5s                 4.5s  -1.2%
```

Switch BoxedMethodDescriptor to tpp_call

---

from_cpython/Lib/test/test_complex_args.py
from_cpython/Lib/test/test_defaultdict.py
from_cpython/Lib/test/test_filecmp.py
from_cpython/Lib/test/test_opcodes.py
from_cpython/Lib/test/test_popen.py
from_cpython/Lib/test/test_stat.py
src/runtime/file.cpp
test/cpython/NOTES.org

A few more are now passing; a bunch more get farther.

Take another pass over the failing cpython tests

---

CMakeLists.txt
Makefile
from_cpython/Include/abstract.h
from_cpython/Include/tupleobject.h
src/asm_writing/rewriter.cpp
src/codegen/parser.cpp
src/core/stats.cpp
src/gc/collector.cpp
src/runtime/builtin_modules/builtins.cpp
src/runtime/builtin_modules/sys.cpp
src/runtime/classobj.cpp
src/runtime/code.cpp
src/runtime/descr.cpp
src/runtime/list.cpp
src/runtime/objmodel.cpp
src/runtime/str.cpp
src/runtime/tuple.cpp
src/runtime/types.cpp
src/runtime/types.h
test/extra/pyicu_101.patch

Trying to look into why our fastpaths are sometimes not as fast as CPython's.  Add some timers, and take care of some low-hanging fruit that I found.

fastpath investigations

---

src/asm_writing/assembler.cpp
src/asm_writing/assembler.h
src/asm_writing/icinfo.cpp
src/asm_writing/icinfo.h
src/asm_writing/rewriter.cpp
src/asm_writing/rewriter.h
src/runtime/ics.cpp
src/runtime/ics.h

Factored out a few commits from from the JIT tier pull request.
Please have a look at the individual commits.
The Runtime IC sizes need probably tweaks in the future - they are just guessed

Preperations for the new JIT tier

---

src/asm_writing/assembler.cpp
src/asm_writing/assembler.h
src/asm_writing/rewriter.cpp

+ add small cleanup: add helper for mode calculation

rewriter: use lea to allocate stack space

---

src/asm_writing/rewriter.h
src/runtime/list.cpp
src/runtime/objmodel.cpp
src/runtime/tuple.cpp

```
django_template.py             4.6s (2)             4.4s (2)  -4.3%
pyxl_bench.py             4.0s (2)             3.9s (2)  -1.6%
sqlalchemy_imperative2.py             5.3s (2)             5.2s (2)  -1.3%
django_migrate.py             2.0s (2)             1.9s (2)  -5.4%
virtualenv_bench.py             5.3s (2)             5.2s (2)  -1.2%
geomean                 4.0s                 3.9s  -2.8%
```

rewriter optimization; switch things away from compareInternal

---

src/asm_writing/icinfo.cpp
src/codegen/ast_interpreter.cpp
src/codegen/baseline_jit.cpp
test/tests/incremental_tb_bjit.py

+ sneaked in a small perf improvement:
```
pyston pyxl_bench.py                      :    3.6s base_3: 3.7 (-1.0%)
pyston sqlalchemy_imperative2.py          :    4.7s base_3: 4.8 (-1.3%)
pyston django_migrate.py                  :    1.7s base_3: 1.7 (-1.5%)
pyston virtualenv_bench.py                :    5.0s base_3: 5.0 (-0.7%)
```

Small fixes for the baseline JIT

---

src/codegen/ast_interpreter.cpp
src/codegen/ast_interpreter.h
src/codegen/codegen.cpp
src/codegen/compvars.cpp
src/codegen/irgen.cpp
src/codegen/irgen.h
src/codegen/irgen/hooks.cpp
src/codegen/irgen/irgenerator.cpp
src/codegen/irgen/irgenerator.h
src/codegen/osrentry.h
src/codegen/patchpoints.cpp
src/codegen/patchpoints.h
src/codegen/unwinding.cpp
src/codegen/unwinding.h
src/core/cfg.cpp
src/core/types.h
src/runtime/builtin_modules/builtins.cpp
src/runtime/frame.cpp
src/runtime/objmodel.cpp

with the goal of moving towards reenabling speculation+deopt.

tiering refactoring

---

test/unittests/analysis.cpp

It was failing an assert that doesn't get checked on travis-ci,
which only tests release mode :/

Fix analysis_unittest after tiering changes

---

test/extra/test_helper.py

Print out the last N lines of a failing test instead of first N

---

src/codegen/ast_interpreter.cpp

This reverts commit 784932207cf44f3e41c1e0fdb439ee3e54bd0f92, reversing
changes made to 194d51eb7218a0f9bdffe75425a46791cf604415.

Revert "Merge pull request #685 from undingen/interp_gc2"

---

src/runtime/long.cpp
test/tests/float.py

#569 seems didn't continuing. So I improve it according the #569 conversations.

add long.__float__ attribute

---

.travis.yml
test/integration/pyxl_test.py
tools/configure_travis.sh

- Build and run in Debug mode
- make sure that building + running doesn't dirty the repository.

Add a couple tests to the travis-ci configuration

---

src/runtime/objmodel.cpp
src/runtime/tuple.cpp
src/runtime/types.h

some minor microoptimizations that I finally cleaned up.
```
django_template.py             4.0s (2)             4.0s (2)  -0.4%
pyxl_bench.py             3.6s (2)             3.6s (2)  -0.2%
sqlalchemy_imperative2.py             4.8s (2)             4.8s (2)  -0.3%
geomean                 4.1s                 4.1s  -0.3%
```

some misc microoptimizations

---

test/tests/modules.py

I guess "math" was split out to a shared module

Another 2.7.9 compatibility fix

---

.gitignore
CMakeLists.txt
Makefile
from_cpython/Lib/test/re_tests.py
from_cpython/Lib/test/test_re.py
microbenchmarks/django_lexing.py
microbenchmarks/re_split_ubench.py
src/codegen/ast_interpreter.cpp
src/codegen/codegen.h
src/codegen/entry.cpp
src/codegen/irgen/util.cpp
src/core/threading.h
src/runtime/capi.cpp
src/runtime/int.cpp
src/runtime/objmodel.cpp
src/runtime/types.cpp
src/runtime/types.h
test/cpython/test_re.py
test/tests/intmethods.py

and a couple new benchmarks.  we still have an annoying amount of build-to-build performance variability (there aren't any performance improvements here):
```
django_template.py             3.6s (2)             3.6s (2)  -0.4%
pyxl_bench.py             3.5s (2)             3.4s (2)  -1.1%
sqlalchemy_imperative2.py             4.3s (2)             4.4s (2)  +0.3%
geomean                 3.8s                 3.8s  -0.4%
```

some fixes and cleanups

---

.travis.yml
src/codegen/parser.cpp

we seem to be running into this quite a bit lately.  the more debug info I add the more confusing it gets, so let's add some more debug info.

Add some more debugging for travis-ci builds

---

test/tests/dash_m.py

Fix a small test output difference on Ubuntu 15.04

---

Makefile
microbenchmarks/django_variable.py
microbenchmarks/getattrfunc_ubench.py
src/asm_writing/icinfo.cpp
src/asm_writing/icinfo.h
src/asm_writing/rewriter.cpp
src/asm_writing/rewriter.h
src/core/stringpool.cpp
src/core/stringpool.h
src/runtime/builtin_modules/pyston.cpp
src/runtime/objmodel.cpp

- getattr microoptimizations
- reduce malloc calls in the rewriter
```
django_template2.py             5.4s (2)             5.2s (2)  -3.1%
pyxl_bench.py             3.3s (4)             3.3s (2)  -2.2%
sqlalchemy_imperative2.py             4.0s (4)             4.0s (2)  -1.4%
django_template.py             3.6s (2)             3.5s (2)  -2.7%
```

more small perf work

---

.travis.yml
CMakeLists.txt
Makefile
src/core/thread_utils.h
src/jit.cpp

The debug builds are takinga very long time to compile, but
when I reran one it completed very quickly.  Let's see if
this works+helps.

travis-ci fixes

---

src/codegen/baseline_jit.cpp
src/codegen/baseline_jit.h

This reduces the number of stack access, because previously when we accessed a field of the interpreter we always had to load it first from stack into a reg - and now we have a dedicated reg.
This is currently only a very small perf change but when #736 lands this becomes more important.
```
django_template.py             3.3s (4)             3.3s (4)  -0.3%
pyxl_bench.py             3.2s (4)             3.2s (4)  -0.4%
sqlalchemy_imperative2.py             3.7s (4)             3.8s (4)  +0.4%
geomean                 3.4s                 3.4s  -0.1%
```

bjit: omit frame pointer + use R12 for ASTInterpreter*

---

src/capi/object.cpp
test/tests/exceptions_basic.py

Make sure to intern attribute string in PyObject_SetAttr.

---

src/runtime/builtin_modules/thread.cpp

This switches the thread lock implementation to use a semaphore instead of a mutex.
I hope this gets rid of the threading_local.py error on travis-ci.

Use cpythons lock implementation

---

from_cpython/Lib/test/test_tuple.py
src/runtime/inline/xrange.cpp
src/runtime/tuple.cpp

(This will probably fail the build since it depends on #715 which isn't merged yet).

get cpython/test_tuple.py to pass

---

src/runtime/list.cpp
test/tests/list.py

list recursive printing

---

src/core/thread_utils.h
src/core/threading.cpp
src/gc/collector.cpp
src/gc/heap.cpp
src/gc/heap.h
test/tests/multiprocessing_test.py

- some extra debugging for the threading_local issue
- remove the data for threads that don't come along with a fork()

Add some PerThreadSet features

---

src/codegen/baseline_jit.cpp
src/codegen/baseline_jit.h
src/codegen/codegen.cpp
src/codegen/irgen/hooks.cpp
src/codegen/irgen/irgenerator.cpp
src/codegen/type_recording.cpp
src/codegen/type_recording.h
src/codegen/unwinding.cpp
src/core/types.h

```
django_template3.py             3.3s (4)             3.3s (4)  -0.5%
pyxl_bench.py             2.9s (4)             2.8s (4)  -2.2%
sqlalchemy_imperative2.py             3.2s (4)             3.2s (4)  -0.3%
geomean                 3.1s                 3.1s  -1.0%
```

Small bjit improvements + fixes the build

---

from_cpython/Lib/test/test_slice.py
src/runtime/types.cpp

Add `indices`, `__hash__`, `compare`, `__reduce__` functions to `slice` class.

Enable `test slice` and add missing function.

---

src/runtime/dict.cpp
src/runtime/list.cpp
src/runtime/set.cpp
src/runtime/tuple.cpp
test/tests/dict.py

add try catch block and remove raw_ostream

Recursive printing

---

src/capi/typeobject.cpp
src/capi/typeobject.h
src/runtime/builtin_modules/builtins.cpp
src/runtime/dict.cpp
src/runtime/generator.cpp
src/runtime/inline/list.cpp
src/runtime/inline/tuple.cpp
src/runtime/inline/xrange.cpp
src/runtime/list.cpp
src/runtime/list.h
src/runtime/objmodel.cpp
src/runtime/set.cpp
src/runtime/str.cpp
src/runtime/tuple.cpp
src/runtime/tuple.h

```
ea3daebf08d007db3e:  7075b3803b12f58f8f:
django_template3.py             3.3s (4)             3.3s (4)  -0.3%
pyxl_bench.py             2.8s (4)             2.8s (4)  -1.3%
sqlalchemy_imperative2.py             3.2s (4)             3.2s (4)  -2.3%
geomean                 3.1s                 3.1s  -1.3%
```

getiter: use tp_iter for non python types

---

Makefile
from_cpython/CMakeLists.txt
from_cpython/setup.py
src/capi/abstract.cpp
test/tests/builtins_future.py

Enable future builtins module and add test file

---

src/capi/types.h
src/runtime/capi.cpp

add __doc__ attribute to capifunc

---

src/codegen/irgen/irgenerator.cpp
src/runtime/objmodel.cpp
test/tests/property_ics.py
test/tests/unaryop_ics.py

```
django_template3.py             3.3s (4)             3.2s (4)  -0.9%
pyxl_bench.py             2.7s (4)             2.7s (4)  -0.6%
sqlalchemy_imperative2.py             3.1s (4)             3.1s (4)  -1.8%
geomean                 3.0s                 3.0s  -1.1%
```

Rewrite unaryop and property get

---

src/core/cfg.cpp
src/runtime/generator.cpp

this all showed up by running test/cpython/test_generators.py
sadly there are still a few until we can run the whole test

fix a few generator problems

---

src/core/types.h
src/runtime/builtin_modules/sys.cpp
src/runtime/dict.cpp
src/runtime/file.cpp
src/runtime/iterobject.cpp
src/runtime/list.cpp
src/runtime/long.cpp
src/runtime/objmodel.cpp
src/runtime/objmodel.h
src/runtime/types.cpp

And fix some of the issues that this found.

Enable validation of printf-style format strings

---

src/codegen/patchpoints.cpp
src/runtime/ics.h
src/runtime/objmodel.cpp
test/tests/nonzero_patching.py

```
origin/perf4~:        origin/perf4:
django_template3.py             3.2s (4)             3.2s (4)  +0.1%
pyxl_bench.py             2.9s (4)             2.8s (4)  -1.7%
sqlalchemy_imperative2.py             3.2s (4)             3.1s (4)  -1.9%
geomean                 3.1s                 3.0s  -1.2%
```

rewrite additional nonzero() cases

---

src/runtime/bool.cpp
src/runtime/str.cpp

- improve bool and str hash() speed
- optimize str.find(char) [ie use faster "find char in string" method over "find string in string" method]

microoptimizations

---

src/core/types.h
src/gc/collector.cpp
src/gc/gc.h
src/gc/heap.cpp
src/runtime/hiddenclass.cpp
src/runtime/hiddenclass.h
src/runtime/iterators.cpp
src/runtime/util.cpp

This will be useful to support more C++ objects that need to be tracked or allocated in our heap.

Refactors on types of GC objects

---

from_cpython/Include/Python.h
from_cpython/Include/pyconfig.h.in
src/analysis/scoping_analysis.cpp
src/capi/typeobject.cpp
src/codegen/parser.cpp
src/codegen/serialize_ast.cpp
src/core/ast.cpp
src/core/cfg.cpp
src/gc/collector.cpp
src/runtime/complex.cpp
src/runtime/dict.cpp
src/runtime/import.cpp
src/runtime/list.cpp
src/runtime/str.cpp

Depends on #767 
These are just a few small changes that help run NumPy which should be useful independently of the rest of the NumPy work.

Some work on the NumPy test

---

src/capi/typeobject.cpp
src/runtime/builtin_modules/builtins.cpp
src/runtime/capi.cpp
src/runtime/descr.cpp
src/runtime/int.cpp
src/runtime/objmodel.cpp
src/runtime/objmodel.h
src/runtime/rewrite_args.h
src/runtime/tuple.cpp
src/runtime/types.cpp

About 1% improvement; about half by adding an optimization to typeCallInner, and the other half by adding an even faster case to rearrangeArguments.

More small optimizations

---

src/analysis/type_analysis.cpp
src/analysis/type_analysis.h
src/codegen/ast_interpreter.cpp
src/codegen/irgen/irgenerator.cpp
src/codegen/parser.cpp
src/codegen/pypa-parser.cpp
src/codegen/serialize_ast.cpp
src/core/ast.cpp
src/core/ast.h
src/core/cfg.cpp
test/tests/assign_literal.py

As per libpypa request https://github.com/vinzenz/libpypa/issues/12

Introduction of slice ast type & updated libpypa

---

.gitignore
from_cpython/Include/pyerrors.h
from_cpython/Objects/exceptions.c
microbenchmarks/django_template3_reduced.py
src/codegen/ast_interpreter.cpp
src/codegen/irgen/irgenerator.cpp
src/core/types.h
src/runtime/builtin_modules/builtins.cpp
src/runtime/capi.cpp
src/runtime/objmodel.cpp
src/runtime/types.cpp
test/tests/.gitignore

By rewriting into it even if it throws exceptions (there are some places where it throws exceptions every single time), and creating exceptions faster.
```
django_template3.py             3.2s (4)             3.2s (4)  -1.1%
pyxl_bench.py             2.8s (4)             2.8s (4)  -0.5%
sqlalchemy_imperative2.py             3.3s (4)             3.2s (4)  -2.4%
geomean                 3.1s                 3.0s  -1.3%
```

improve getattr() speed

---

from_cpython/Lib/test/test_float.py
from_cpython/Objects/floatobject.c
src/capi/abstract.cpp
src/runtime/float.cpp

**Change:**
* Enable `test_float`, but hard code the `sys.float_info` for now. Already working on `sys.xxx_info` in another branch.
* Implement `PyNumber_Negative`
* Improve `floatNew`, `PyFloat_FromString`, and some other improvements about float.

Improve the float implementation, enable test_float

---

src/asm_writing/rewriter.cpp
src/asm_writing/rewriter.h

```
31f7289806254484c8:  760925b964ace749eb:
django_template3.py             3.0s (4)             3.0s (4)  -2.6%
pyxl_bench.py             2.6s (4)             2.6s (4)  -1.3%
sqlalchemy_imperative2.py             3.1s (4)             3.0s (4)  -1.7%
geomean                 2.9s                 2.8s  -1.9%
```

Microoptimize the rewriter class

---

src/runtime/set.cpp
src/runtime/set.h
src/runtime/types.h

This doen't have any significant perf change on our main benchmarks.

Switch our Python set implementation to use a llvm::DenseSet

---

Makefile
src/asm_writing/rewriter.cpp
src/capi/typeobject.cpp
src/capi/typeobject.h
src/codegen/ast_interpreter.cpp
src/codegen/ast_interpreter.h
src/codegen/baseline_jit.cpp
src/codegen/codegen.cpp
src/codegen/irgen.cpp
src/codegen/irgen.h
src/codegen/irgen/hooks.cpp
src/codegen/irgen/irgenerator.cpp
src/codegen/unwinding.cpp
src/codegen/unwinding.h
src/core/cfg.cpp
src/core/types.h
src/runtime/capi.cpp
src/runtime/code.cpp
src/runtime/cxx_unwind.cpp
src/runtime/exceptions.cpp
src/runtime/generator.cpp
src/runtime/objmodel.cpp
src/runtime/objmodel.h
src/runtime/traceback.cpp
src/runtime/tuple.cpp
src/runtime/types.cpp
src/runtime/util.cpp
test/unittests/analysis.cpp

Some misc small optimizations

---

src/runtime/file.cpp
src/runtime/set.cpp
test/tests/file_writing.py
test/tests/set.py

couple of minor changes that enable us to run mercurial (using their pure implementations of some modules.  the native modules don't build yet.)  enough to clone the mercurial source repo.
it's very, very slow at the moment.  cpython does it in about 30s, and we do it in 4.5m

Mercurial fixes

---

src/runtime/int.cpp
test/tests/intmethods.py

Use adjustment-post division to avoid int division overflow

---

.gitmodules
CMakeLists.txt
Makefile
test/extra/babel_test.py
test/extra/cheetah_test.py
test/extra/mysqldb_0001-Pyston-change-register-types.patch
test/extra/mysqldb_test.py
test/extra/protobuf_test.py
test/extra/pycurl_test.py
test/extra/pyicu_101.patch
test/extra/pyicu_test.py
test/integration/Cython_0001-Pyston-change-we-don-t-support-custom-traceback-entr.patch
test/integration/django_test.py
test/integration/gflags_test.py
test/integration/numpy_patch.patch
test/integration/numpy_test.py
test/integration/pycrypto_0001-fastmath-Add-support-for-Pyston.patch
test/integration/pycrypto_test.py
test/integration/pyxl_test.py
test/integration/sqlalchemy_smalltest.py
test/integration/sqlalchemy_test.py
test/integration/virtualenv_test.py
test/lib/test_helper.py
tools/tester.py

Move everything back into the main repo.

Undo testsuite split

---

src/analysis/type_analysis.cpp
src/codegen/ast_interpreter.cpp
src/codegen/codegen.h
src/codegen/irgen/irgenerator.cpp
src/codegen/runtime_hooks.cpp
src/codegen/unwinding.cpp
test/tests/deopt_generator_tests.py

```
3e360e58e74c6f1a2b:  b7bb155d168f8b40f0:
django_template3.py             2.9s (6)             2.9s (4)  +0.4%
pyxl_bench.py             2.6s (6)             2.5s (4)  -1.5%
sqlalchemy_imperative2.py             3.0s (6)             2.9s (4)  -1.9%
geomean                 2.8s                 2.8s  -1.0%
```

Fix and reenable type speculations

---

minibenchmarks/django_template.py
minibenchmarks/pyxl_bench.py
minibenchmarks/sqlalchemy_imperative.py
src/capi/typeobject.cpp
src/capi/typeobject.h
src/runtime/builtin_modules/builtins.cpp
src/runtime/objmodel.cpp

The part about "rewriting even though an exception was thrown" is kind of scary, but I think it's something we need to support.
this pr is about a 1% perf improvement.

more getattr rewriting

---

src/codegen/irgen/irgenerator.cpp
src/codegen/irgen/irgenerator.h
src/runtime/objmodel.cpp
src/runtime/types.cpp
test/tests/exceptions_regressions.py

Based on #865 with some more checking + a test.
Also, fix some issues that cropped up when setting "FORCE_CAPI_*=true" in the course of testing this.

Fix "error return without exception set"

---

src/codegen/codegen.cpp
src/codegen/irgen/hooks.cpp
src/core/types.h
src/runtime/code.cpp
src/runtime/code.h
src/runtime/frame.cpp

Just something I did along the way.

Some reorganization of CLFunction/BoxedCode code.

---

from_cpython/Modules/_sre.c
from_cpython/Python/dtoa.c
src/runtime/builtin_modules/builtins.cpp
src/runtime/list.cpp

```
150982683ad1dcc208:  ecccafff989f6d06f7:
django_template3.py             2.8s (4)             2.8s (4)  -0.9%
pyxl_bench.py             2.3s (4)             2.3s (4)  -1.1%
sqlalchemy_imperative2.py             2.9s (4)             2.8s (4)  -0.7%
geomean                 2.6s                 2.6s  -0.9%
```

misc small perf improvments

---

src/codegen/ast_interpreter.cpp
src/core/cfg.h
src/runtime/types.cpp

```
django_template3.py             2.9s (2)             2.8s (2)  -0.6%
pyxl_bench.py             2.4s (2)             2.4s (2)  -1.2%
sqlalchemy_imperative2.py             2.9s (2)             2.9s (2)  -0.6%
geomean                 2.7s                 2.7s  -0.8%
```

Rewrite some more typeCall cases

---

from_cpython/Include/descrobject.h
src/capi/typeobject.cpp
src/runtime/descr.cpp
src/runtime/types.cpp

```
django_template3.py             2.8s (4)             2.8s (4)  -0.2%
pyxl_bench.py             2.2s (4)             2.2s (4)  -0.7%
sqlalchemy_imperative2.py             2.8s (4)             2.7s (4)  -1.0%
geomean                 2.6s                 2.6s  -0.6%
```

BoxedWrapper optimizations

---

src/codegen/irgen/irgenerator.cpp
src/core/util.cpp
src/core/util.h
src/runtime/dict.cpp
src/runtime/dict.h
src/runtime/inline/dict.cpp
src/runtime/inline/list.cpp
src/runtime/inline/tuple.cpp
src/runtime/inline/xrange.cpp
src/runtime/list.cpp
src/runtime/list.h
src/runtime/set.cpp
src/runtime/str.cpp
src/runtime/tuple.cpp
src/runtime/tuple.h

```
7eec7fa2e53c908a06:  5c60ed7c85337bb516:
django_template3.py             2.7s (4)             2.7s (4)  -0.6%
pyxl_bench.py             2.2s (4)             2.2s (4)  -1.3%
sqlalchemy_imperative2.py             2.6s (4)             2.6s (4)  -1.4%
geomean                 2.5s                 2.5s  -1.1%
```

add tp_nextiter implementation for our iterators

---

src/codegen/irgen.cpp

one of the problems were that depending on if all files were all ready parsed we JITed more or less functions,
this changed the total number of jited functions which changed all the module names.
This lead to the result that in order to have all entries inside the cache we needed at least 3runs if the pyc files were old.
The whole name scheme should add some point get improved but for now it should be enough.

Generate better module names to make the object cache more effective

---

src/codegen/irgen/irgenerator.cpp
src/runtime/iterators.cpp

Add override keyword where necessary.

---

src/runtime/set.cpp
src/runtime/str.cpp
src/runtime/types.cpp
test/integration/sqlalchemy_smalltest.py
test/tests/augassign_reverse.py
test/tests/set.py
test/tests/str_adding.py
test/tests/str_adding_compat.py

- str()+MyClass()
- set initialization in new vs init
- some fixes to the sqlalchemy testing harness
we now pass the same tests that our testing harness can pass under cpython.

Sqlalchemy compatibility fixes

---

src/asm_writing/icinfo.cpp
src/asm_writing/icinfo.h
src/asm_writing/rewriter.cpp
src/asm_writing/rewriter.h
src/core/threading.cpp
src/core/threading.h
src/gc/collector.h
src/gc/gc.h
src/gc/heap.cpp
src/runtime/objmodel.cpp

Scan rewriters for interior pointers

---

minibenchmarks/sqlalchemy_declarative.py
src/runtime/set.cpp
test/tests/set.py

(just adding some frozenset methods)

Last few fixes to make sqlalchemy_declarative work

---

src/runtime/dict.cpp
src/runtime/set.cpp
test/tests/set.py

+ sneaked in small dict + set microoptimizations

Fix set comparisons

---

src/capi/typeobject.cpp
src/runtime/descr.cpp
src/runtime/util.cpp
test/tests/curses_test.py

By importing the cpython implementations of add_methods / add_members /
add_getset.

Properly handle METH_COEXIST

---

Makefile

@kmod 
i try to squash previous PR but it was messed up 
so i closed it and reopen it

fix Makefile to be able to 'make' after 'make clean'

---

test/tests/decorated_func_line.py

This is the test for the fix in vinzenz/libpypa#49

The line of a decorated function is the decorator

---

.gitmodules
src/codegen/irgen/hooks.cpp
src/codegen/parser.cpp
src/codegen/parser.h
src/codegen/pypa-parser.cpp
src/codegen/pypa-parser.h
src/jit.cpp
src/runtime/import.cpp
test/integration/decorator_test.py
test/tests/print_function.py
test/unittests/analysis.cpp

and run their testsuite.
depends on vinzenz/libpypa#48

Support the "decorator" library

---

.gitmodules
from_cpython/Include/Python.h
from_cpython/Modules/_ctypes/_ctypes.c
src/runtime/descr.cpp
src/runtime/objmodel.cpp
src/runtime/types.cpp
test/integration/pyinotify_test.py
test/tests/ctypes_test.py

**Changes**
- Add `pyinotify` submodule.
- Add `pyinotify` test.
closes #903

Add "pyinotify" test, with a minor modification to Pyston

---

src/runtime/import.cpp

the ```/proc/self/maps``` entry contains the absolute file path with resolved symlinks,
this patch retrieves now the absolute path of the lib and resolves symlinks.

Fix registerDataSegment error when encountering symlinks

---

src/runtime/objmodel.cpp

even though getFunctionName() is fast it showed up in the profiler because it get's called very often,
but most of the time the actual value is not used.
```
django_template3.py             2.7s (4)             2.7s (4)  -0.1%
pyxl_bench.py             2.3s (4)             2.2s (4)  -2.8%
sqlalchemy_imperative2.py             2.7s (4)             2.6s (4)  -0.7%
geomean                 2.5s                 2.5s  -1.2%
```

microptimize callFunc() by only calling getFunctionName() when necessary

---

src/core/types.h
src/runtime/generator.cpp
src/runtime/objmodel.cpp
src/runtime/objmodel.h
src/runtime/rewrite_args.h

```
django_template3.py             2.7s (4)             2.7s (4)  -0.3%
pyxl_bench.py             2.3s (4)             2.2s (4)  -4.1%
sqlalchemy_imperative2.py             2.7s (4)             2.6s (4)  -1.4%
geomean                 2.5s                 2.5s  -2.0%
```
perf looks a little bit to good may have been a very lucky build ;-D

Add more Rewritable template args to functions

---

src/capi/abstract.cpp

```
origin/perf_new4~:    origin/perf_new4:
django_template3.py             2.7s (4)             2.7s (4)  -0.5%
pyxl_bench.py             2.2s (4)             2.2s (4)  -0.9%
sqlalchemy_imperative2.py             2.6s (4)             2.6s (4)  +0.3%
geomean                 2.5s                 2.5s  -0.4%
```

Use callattr inside PyObject_CallMethod*

---

.gitmodules
src/codegen/compvars.cpp
src/runtime/builtin_modules/thread.cpp
src/runtime/descr.cpp
src/runtime/dict.cpp
src/runtime/list.cpp
src/runtime/objmodel.cpp
src/runtime/types.cpp
test/integration/sqlalchemy_0.5_smalltest.py
test/tests/int_ids.py
test/tests/list_subclassing.py
test/tests/none__class__.py
test/tests/str_adding.py
test/tests/str_adding_compat.py

This exposed some other issues for us.

Test against an old 0.5-series version of sqlalchemy

---

src/runtime/dict.cpp
src/runtime/objmodel.cpp
test/tests/keyword_ics.py

```
django_template3.py             2.7s (4)             2.7s (4)  -0.7%
pyxl_bench.py             2.2s (4)             2.2s (4)  -1.0%
sqlalchemy_imperative2.py             2.6s (4)             2.6s (4)  +0.1%
geomean                 2.5s                 2.5s  -0.5%
```

Add rewrite support for calls which use keyword args

---

CMakeLists.txt
src/codegen/ast_interpreter.cpp
src/codegen/ast_interpreter.h
src/codegen/irgen/hooks.cpp
src/runtime/objmodel.cpp

```
django_template3.py             2.7s (4)             2.5s (4)  -8.3%
pyxl_bench.py             2.2s (4)             2.2s (4)  -0.4%
sqlalchemy_imperative2.py             2.6s (4)             2.6s (4)  -0.6%
geomean                 2.5s                 2.4s  -3.2%
```

Misc perf improvements

---

src/jit.cpp
src/runtime/import.cpp
src/runtime/import.h
src/runtime/types.cpp
src/runtime/types.h

handle the situation which provide a directory to pyston

---

src/analysis/type_analysis.cpp
test/tests/intmethods.py

Doesn't really make sense any more.

Remove an old assert

---

src/runtime/builtin_modules/builtins.cpp
src/runtime/builtin_modules/gc.cpp
src/runtime/builtin_modules/sys.cpp
src/runtime/float.cpp
src/runtime/import.cpp

Just for existed builtin functions or methods. The method under a class is `instancemethod` in Pyston, CPython is `wrapper_descriptor`. But our `BoxedWrapperDescriptor` seems used for CPython method only. Maybe we need to let it support `CLFunction` too? Or use other strategy?

add doc to existed builtin function or method

---

from_cpython/Include/object.h
from_cpython/Objects/unicodeobject.c
src/capi/typeobject.cpp
src/runtime/list.cpp
src/runtime/objmodel.cpp
src/runtime/types.cpp
src/runtime/types.h

```
upstream/master:      origin/pyxl2_2:
django_template3.py             2.2s (4)             2.2s (2)  +0.7%
pyxl_bench.py             1.8s (4)             1.8s (2)  +0.4%
sqlalchemy_imperative2.py             2.3s (4)             2.3s (2)  -0.2%
pyxl_bench2.py             1.3s (4)             1.3s (2)  -1.3%
django_template3_10x.py            14.2s (4)            14.4s (2)  +0.9%
pyxl_bench_10x.py            14.3s (4)            14.2s (2)  -0.4%
sqlalchemy_imperative2_10x.py            17.5s (4)            17.4s (2)  -0.5%
pyxl_bench2_10x.py            12.2s (4)            11.5s (2)  -5.5%
geomean                 5.2s                 5.1s  -0.8%
```

Misc pyxl2 perf improvements continued

---

src/core/thread_utils.h

```
/home/travis/build/dropbox/pyston/src/core/thread_utils.h:196: static void pyston::threading::PerThreadSet<pyston::gc::SmallArena::ThreadBlockCache, pyston::gc::Heap *, pyston::gc::SmallArena *>::dtor(void *) [T = pyston::gc::SmallArena::ThreadBlockCache, CtorArgs = <pyston::gc::Heap *, pyston::gc::SmallArena *>]: Assertion `self->map.size() == self->map_elts' failed: 0 2
```

Test PR to track down the travis CI self->map.size() == self->map_elts assert

---

from_cpython/Lib/test/test_string.py
from_cpython/Objects/stringobject.c
src/runtime/str.cpp
src/runtime/types.cpp
test/CPYTHON_TEST_NOTES.md

please ignore the branch name, I made a mistake about it...

Add two attribute to str that let test_string pass.

---

microbenchmarks/control_flow_ubench.py
microbenchmarks/django_template3_reduced.py
microbenchmarks/megamorphic_control_flow.py
microbenchmarks/megamorphic_ubench.py
microbenchmarks/tester.py

in case we want to reproduce the graphs

microbenchmarks for the presentation

---

README.md

- add small 0.5 blurb
- add 0.4 blog post link
- reverse order (latest release first)

Update "roadmap" in readme

---

CMakeLists.txt
microbenchmarks/control_flow_ubench.py
microbenchmarks/megamorphic_control_flow.py
microbenchmarks/megamorphic_ubench.py
test/tests/NOTES.txt

And also detect attempts to compile on a 32-bit system and
quickly give a nice error message -- fixes #1018.

Some small documentation

---

llvm_patches/0012-Remove-move-warning.patch
src/asm_writing/assembler.cpp
src/asm_writing/rewriter.h
src/asm_writing/types.h
src/codegen/compvars.cpp
src/codegen/parser.cpp
src/core/common.h
src/gc/gc.h
tools/git_svn_gotorev.py

This is a continuation of #1019 and [dean0x7d/clang37_fixes](https://github.com/dean0x7d/pyston/commits/clang37_fixes).

clang-3.7 support

---

from_cpython/CMakeLists.txt
from_cpython/Lib/test/test_cmath.py
from_cpython/Objects/complexobject.c
from_cpython/setup.py
src/runtime/builtin_modules/builtins.cpp
src/runtime/complex.cpp
src/runtime/float.cpp
src/runtime/int.cpp
test/CPYTHON_TEST_NOTES.md

Add `complexobject.cpp` file, remove some fundamental and duplicated functions in `complex.cpp`. Some functions still leave in `complex.cpp`, because our complex object(`BoxedComplex`) is different from CPython's. So I think leave it there will be fine.

Add cmath module and fix some bugs discovered in test_cmath.

---

src/runtime/types.cpp
test/tests/builtin_type_not_subclassable.py

Fix issue #596 
make slice to be not subclassable.

Fix issue #596 'slice is not subclassable'

---

from_cpython/CMakeLists.txt
from_cpython/Include/Python.h
from_cpython/Include/frameobject.h
from_cpython/Include/sysmodule.h
from_cpython/Python/_warnings.c
src/runtime/builtin_modules/sys.cpp
src/runtime/capi.cpp
src/runtime/frame.cpp
src/runtime/traceback.cpp
src/runtime/types.cpp
test/tests/warnings_test.py

Implement `PyErr_WarnEx`, based on CPython implementation. Except use Pyston BoxedFrame instead PyFrameObject. And also apply some pyston changes.
closes #1013

Implement PyErr_WarnEx

---

test/CPYTHON_TEST_NOTES.md
test/tests/test_dictviews.py

I forgot to add this commit to #1042

enable dictview tests

---

src/runtime/builtin_modules/builtins.cpp
src/runtime/float.cpp
src/runtime/int.cpp
test/integration/numpy_patch.patch
test/tests/future_division.py

Two minor problem which found in NumPy tests

---

src/runtime/builtin_modules/builtins.cpp
src/runtime/classobj.cpp
src/runtime/code.cpp
src/runtime/frame.cpp
src/runtime/generator.cpp
src/runtime/inline/xrange.cpp
src/runtime/iterobject.cpp
src/runtime/list.cpp
src/runtime/objmodel.cpp
src/runtime/str.cpp
src/runtime/types.cpp
src/runtime/types.h
test/tests/builtin_type_not_subclassable.py

As we descuss about [not subclassable class] at #1038
i got  lists of 'should not be subclassalbe class' by `grep -L -e "Py_TPFLAGS_BASETYPE" Objects/  -R`
and check tp_name if tp_name is not subclassable type.
than I off the `Py_TPFLAGS_BASETYPE`

Add list of not subclassable class

---

docs/UNWINDING.md

fix docs/UNWINDING.md

---

src/runtime/descr.cpp
src/runtime/types.cpp
test/extra/flask_test.py

* Small fixes for Flask
* Check some of the template rendering jinja2

Small fixes for Flask

---

from_cpython/Lib/test/test_dictcomps.py
from_cpython/Lib/test/test_eof.py
from_cpython/Lib/test/test_longexp.py
from_cpython/Lib/test/test_mailbox.py
from_cpython/Lib/test/test_memoryio.py
from_cpython/Lib/test/test_minidom.py
from_cpython/Lib/test/test_old_mailbox.py
from_cpython/Lib/test/test_pep263.py
from_cpython/Lib/test/test_pep277.py
from_cpython/Lib/test/test_shlex.py
from_cpython/Lib/test/test_smtpnet.py
from_cpython/Lib/test/test_struct.py
from_cpython/Lib/test/test_timeout.py
from_cpython/Lib/test/test_wave.py
from_cpython/Lib/test/test_with.py
from_cpython/Lib/test/test_wsgiref.py
test/CPYTHON_TEST_NOTES.md
test/cpython/audiodata
test/cpython/xmltestdata

test_wsgiref.py was copied from the wrong cpython version...

Enable working cpython tests

---

test/CPYTHON_TEST_NOTES.md
test/integration/pycrypto_0001-fastmath-Add-support-for-Pyston.patch
test/integration/pycrypto_test.py

We did not yet run the whole testsuite but instead just ran a simple test we wrote.

Make the pycrypto integration test run the testsuite

---

from_cpython/Lib/test/test_imp.py
src/runtime/builtin_modules/builtins.cpp
src/runtime/long.cpp
test/CPYTHON_TEST_NOTES.md
test/extra/unidecode_test.py
test/tests/builtins.py
test/tests/long.py

this tests the import changes from #1105 and did not work before this change.

create a unidecode integration test and enable test_imp

---

.travis.yml
docs/INSTALLING.md
src/capi/abstract.cpp
src/capi/modsupport.cpp
src/runtime/builtin_modules/builtins.cpp
src/runtime/dict.cpp
src/runtime/int.cpp
src/runtime/int.h
src/runtime/long.cpp
test/extra/geoip_test.py
test/tests/builtins.py

Unfortunately there are still a few hiding which means we can't yet run test_builtin.py right now
but after this and #1111 there shouldn't be that many problems left.

add GeopIP integration test and use cpythons do_mkvalue and fix some problems of test_builtin.py

---

src/runtime/float.cpp
src/runtime/str.cpp
test/integration/numpy_test.py
test/tests/float.py
test/tests/str_functions.py

and add float() and str() param names
In addition noticed that we did not run one of our small numpy tests

Address minor comment from #1028

---

from_cpython/Lib/inspect.py
from_cpython/Lib/test/test_abc.py
from_cpython/Lib/test/test_collections.py
src/runtime/dict.cpp
src/runtime/types.cpp
test/CPYTHON_TEST_NOTES.md

The originally purpose of this PR was try to let `test_collections` could pass. At the end, it also fixed some issues in `test_abc`.

Abstract class improvements

---

.travis.yml
src/runtime/str.cpp
test/extra/paste_test.py
test/extra/pylons_test.py
test/extra/routes_test.py

paste triggers the ```str.__iter__``` problem (we should not have it but removing it causes a 3-4% perf regression for ```pyxl_bench2```)

add a paste, pylons and routes integration test

---

src/runtime/objmodel.cpp
test/tests/class_and_func_name.py

Ref nexedi fixing

---

src/runtime/float.cpp
src/runtime/int.cpp
src/runtime/long.cpp
test/tests/float.py
test/tests/long.py

- Add `__format__` function to `long` object. Use generic format function(`object_format`) will have many redundant calls and can not work with `d` format encode.
Mark as "WIP", because it may contains other minor NumPy fixing soon.

Some minor fixing which found in numpy tests

---

.travis.yml
CMakeLists.txt
from_cpython/Include/abstract.h
from_cpython/Lib/test/test_sqlite.py
src/asm_writing/rewriter.cpp
src/capi/abstract.cpp
src/runtime/float.cpp
test/integration/decorator_test.py
test/integration/django_test.py
test/integration/numpy_test.py
test/integration/pycrypto_test.py
test/integration/pyinotify_test.py
test/integration/pyxl_test.py
test/integration/sqlalchemy_smalltest.py
test/integration/virtualenv_test.py

- mark a few more things as reffail
- disable "force-llvm" tests for now since a lot of those are failing
- fix a couple misc issues

Turn on CI for the refcounting branch again

---

CMakeLists.txt
tools/tester.py

- adds a `-q` option and turns it on for CI (turns off all the "test passed" spam)
- some other minor improvements

Cherry-pick some tester improvements from the refcounting branch

---

src/runtime/dict.cpp
src/runtime/types.h

I'm not sure if this is actually triggerable or not

Fix another raise-before-stealing-argument bug

---

from_cpython/Lib/test/test_array.py
from_cpython/Lib/test/test_collections.py
from_cpython/Lib/test/test_decimal.py
from_cpython/Lib/test/test_dumbdbm.py
from_cpython/Lib/test/test_file2k.py
from_cpython/Lib/test/test_logging.py
from_cpython/Lib/test/test_memoryview.py
from_cpython/Lib/test/test_os.py
from_cpython/Lib/test/test_re.py
from_cpython/Lib/test/test_set.py
from_cpython/Lib/test/test_telnetlib.py
from_cpython/Lib/test/test_tuple.py
src/asm_writing/rewriter.cpp
src/asm_writing/rewriter.h
src/asm_writing/types.h
src/codegen/unwinding.cpp
src/runtime/objmodel.cpp
test/tests/oargs_decref.py

And update a bunch of test comments

Fix the lost-ref-from-oargs issue

---

from_cpython/Lib/test/test_array.py
from_cpython/Lib/test/test_collections.py
from_cpython/Lib/test/test_decimal.py
from_cpython/Lib/test/test_dumbdbm.py
from_cpython/Lib/test/test_file2k.py
from_cpython/Lib/test/test_logging.py
from_cpython/Lib/test/test_memoryview.py
from_cpython/Lib/test/test_os.py
from_cpython/Lib/test/test_re.py
from_cpython/Lib/test/test_set.py
from_cpython/Lib/test/test_telnetlib.py
from_cpython/Lib/test/test_tuple.py
src/asm_writing/rewriter.cpp
src/asm_writing/rewriter.h
src/asm_writing/types.h
src/codegen/unwinding.cpp
src/runtime/objmodel.cpp
test/tests/oargs_decref.py

A bunch more are passing with the recent fixes.

Update test notes

---

src/runtime/capi.cpp
src/runtime/tuple.cpp

running the integration tests need a little bit more work but I wanted to get this in already so we don't do duplicate work...

refcounting fixes for numpy in PyTuple_GetSlice, PyErr_SetExcInfo and PyErr_GetExcInfo

---

src/core/util.h

It was difficult to understand the intent of the legacy code.
So I tried to guess the original intent.

bitset begin() function fix

---

src/core/util.h

- Bitset iteration micro optimize

Bitset iteration micro optimize

---

src/runtime/builtin_modules/sys.cpp

This just copy the CPython implementation, so some NumPy tests could pass.
But most of types in Pyston didn't implement '__sizeof__' attribute yet.

copy CPython sys.getsizeof implementation with some Pyston changes

---

from_cpython/Lib/_abcoll.py
from_cpython/Lib/bisect.py
from_cpython/Lib/codecs.py
from_cpython/Lib/collections.py
from_cpython/Lib/test/test_abc.py
from_cpython/Lib/test/test_array.py
from_cpython/Lib/test/test_complex.py
from_cpython/Lib/test/test_file2k.py
from_cpython/Lib/test/test_fileio.py
from_cpython/Lib/test/test_mmap.py
from_cpython/Lib/test/test_set.py
from_cpython/Lib/test/test_signal.py
from_cpython/Lib/types.py
from_cpython/Lib/unittest/loader.py
from_cpython/Lib/unittest/result.py
from_cpython/Lib/warnings.py
from_cpython/Lib/weakref.py
from_cpython/Modules/_collectionsmodule.c
from_cpython/Modules/_ctypes/cfield.c
from_cpython/Modules/_elementtree.c
from_cpython/Modules/_functoolsmodule.c
from_cpython/Modules/_sre.c
from_cpython/Modules/cPickle.c
from_cpython/Modules/itertoolsmodule.c
from_cpython/Objects/fileobject.c
from_cpython/Objects/unicodeobject.c
from_cpython/Python/dtoa.c
from_cpython/Python/import.c
from_cpython/Python/pyarena.c
src/runtime/capi.cpp

Remove most of the "Pyston changes" in from_cpython/

Undo a bunch of Pyston changes to cpython code

---

from_cpython/Include/classobject.h
from_cpython/Lib/test/test_decimal.py
from_cpython/Lib/test/test_shelve.py
from_cpython/Lib/test/test_shutil.py
from_cpython/Lib/test/test_socket.py
from_cpython/Modules/_elementtree.c
src/runtime/classobj.cpp
src/runtime/types.cpp
test/integration/decorator_test.py
test/integration/pyinotify_test.py
test/tests/class_freeing_time.py
test/tests/deopt_namescope_tests.py
test/tests/deopt_tests.py
test/tests/elementree_test.py
tools/tester.py

And we have no more tests that are failing due to refcounting!
Except for test_decimal, which is timing out now.  But no more crashes/correctness issues :)

Fix the last two reffail tests

---

.gitmodules
test/integration/numpy_patch.patch
test/integration/numpy_test.py

Remove numpy submodule, clone numpy from github with v1.11.0 tag when testing.

Remove numpy submodule

---

src/codegen/unwinding.cpp
src/core/ast.cpp
src/core/ast.h
src/core/cfg.h
src/runtime/capi.cpp
src/runtime/types.cpp
test/integration/numpy_test.py

Improves the time for numpy.test from 180s to 150s.  I found a lot more things we could do but they might have to wait until after the 0.5 release.

One small change for numpy performance

---

src/codegen/irgen/refcounts.cpp
src/codegen/unwinding.cpp
src/codegen/unwinding.h
src/runtime/exceptions.cpp
test/integration/sqlalchemy_smalltest.py

this is the last of the integration and extra tests which was disabled :-)

enable sqlalchemy_smalltest

---

src/capi/abstract.cpp
src/runtime/builtin_modules/builtins.cpp
src/runtime/objmodel.cpp
src/runtime/objmodel.h
test/extra/lxml_test.py

this is https://github.com/dropbox/pyston/pull/1195 but pointing to upstream/master

binop: use PyNumber_* for user defined classes

---

src/runtime/builtin_modules/builtins.cpp

- There's no rewriter support in hex and oct in Pyston for now, so just change it to calling nb_hex.

[WIP] Some minor numpy fixing.

---

test/extra/numpy_fulltest.py

Merge conflict between my pr that added the full test suite and Sun's that
fixed one of the tests.

Update test results

---

from_cpython/Modules/_io/textio.c
src/runtime/iterators.cpp
test/extra/numpy_fulltest.py
test/tests/enumerate_test.py

We were fetching to eagerly which caused issues if the iterator got used for other stuff too

BoxIteratorGeneric call PyIter_Next() lazily

---

Makefile
README.md
docker/Dockerfile
docs/DOCKER.md

that is just based off of pulling our latest release

Create a simple Dockerfile

---

from_cpython/Include/object.h
from_cpython/Include/pyport.h
src/capi/typeobject.cpp
src/runtime/complex.cpp
src/runtime/int.cpp
test/test_extension/CMakeLists.txt
test/test_extension/setup.py
test/test_extension/type_test.c
test/tests/complex.py
test/tests/intmethods.py
test/tests/type_creation.py

closes #1232 by second commit.

Some fixings that let scipy tests pass.

---

test/extra/lxml_test.py
test/extra/numpy_fulltest.py
test/integration/numpy_test.py

download cython from github instead of cython.org

---

from_cpython/Include/pyport.h

this slipped in https://github.com/dropbox/pyston/pull/1231

Remove redefinition error in pyport.h

---

src/codegen/ast_interpreter.cpp
src/codegen/cpython_ast.cpp
src/codegen/irgen/hooks.cpp
src/codegen/irgen/irgenerator.cpp
src/codegen/parser.cpp
src/core/ast.h
src/core/cfg.cpp
src/runtime/descr.cpp
src/runtime/dict.cpp
src/runtime/frame.cpp
src/runtime/generator.cpp
test/tests/dict.py
test/tests/lineno_tricky.py
test/tests/lineno_tricky_multiline.py
test/tests/static_class_methods.py
test/tests/type_phi_test.py

And a few other misc things that I merged in from the metaserver branch.

Add more line numbers

---

Makefile
from_cpython/Include/code.h
src/capi/typeobject.cpp
src/runtime/code.cpp
src/runtime/frame.cpp
src/runtime/set.cpp
test/integration/numpy_test.py
test/test_extension/CMakeLists.txt
test/test_extension/api_test.c
test/test_extension/setup.py
test/tests/set.expected
test/tests/set.py

First, I try to switch from PyPy based Cython(which Pyston currently used) to CPython based Cython. Then Pyston need add some new API to process some operation in CPython based Cython.
Includes some other scipy related changes.

Add some helper API to Pyston.

---

src/runtime/types.cpp
src/runtime/types.h
test/tests/function_ctor_closure_checking.py
test/tests/functions.py

Enable function.func_closure and function.__new__

---

CMakeLists.txt
src/capi/object.cpp
src/capi/types.h
src/runtime/dict.cpp
src/runtime/objmodel.cpp
test/tests/dict_comparisons.py

@sizeoftank's #1271 but with the commits re-separated

Dictionary comparisons

---

src/asm_writing/rewriter.cpp
src/asm_writing/rewriter.h
src/runtime/objmodel.cpp

fix some scipy segfaults

---

from_cpython/Include/floatobject.h
from_cpython/Include/intobject.h
from_cpython/Include/stringobject.h
src/runtime/str.cpp

very minor but I think it's now time to enable them back for the small perf improvement they provide

capi: add the direct access macros back

---

src/runtime/list.cpp
src/runtime/str.cpp
src/runtime/tuple.cpp

Add list tp_as_mapping for issue #1197

Add missing tp_as_mapping

---

src/core/cfg.h

This should be a little bit more efficient for large number of vregs.

VRegSet: use a llvm bitvector as representation

---

from_cpython/Objects/stringlib/stringdefs.h
from_cpython/Objects/stringobject.c
src/runtime/str.cpp
test/tests/str_functions.py

it support non str separators
fixes #1297

str: use cpythons [r]partition

---

src/runtime/classobj.cpp
test/tests/oldstyle_classes.py

implement  ` tp_as_sequence ` &  ` tp_as_mapping ` for  ` instance_cls `

Add sq_slots & mp_slots to instance (issue #1197)

---

from_cpython/Include/object.h
src/capi/typeobject.cpp
src/capi/types.h
src/core/types.h
src/runtime/bool.cpp
src/runtime/capi.cpp
src/runtime/complex.cpp
src/runtime/float.cpp
src/runtime/list.cpp
src/runtime/long.cpp
src/runtime/long.h
src/runtime/objmodel.h
src/runtime/set.cpp
src/runtime/tuple.cpp
src/runtime/types.cpp
src/runtime/types.h
src/runtime/util.cpp

motivation is that I found a json encoder which is calling a huge amount of time into `PyObject_Repr`

implement tp_str and tp_repr for more of our builtin types

---

src/core/cfg.cpp
test/tests/compare_ordering.py

Fix extra nonzero call for chained comparisons #1190

---

src/core/threading.cpp
src/core/threading.h
src/runtime/generator.cpp
src/runtime/generator.h

reduce number of c++ exceptions
adds a few C API paths plus sets tp_iternext and tpp_hasnext

generator optimizations

---

src/analysis/scoping_analysis.cpp

and change it to use a unordered_map because it uses less memory in this case and is faster
(I assume because it does not have align the key value tuples)
saves about 10% of peak memory on django

ScopeNameUsage merge dicts into a single big one

---

src/analysis/scoping_analysis.cpp
src/runtime/generator.cpp
test/tests/generators.py

I'm suprised we did not run into this earlier...

don't handle functions containing lambdas with yields as generators

---

src/analysis/function_analysis.cpp
src/analysis/type_analysis.cpp
src/asm_writing/icinfo.cpp
src/asm_writing/icinfo.h
src/codegen/ast_interpreter.cpp
src/codegen/baseline_jit.cpp
src/codegen/baseline_jit.h
src/codegen/codegen.cpp
src/codegen/irgen.cpp
src/codegen/irgen.h
src/codegen/irgen/hooks.cpp
src/codegen/irgen/irgenerator.cpp
src/codegen/irgen/irgenerator.h
src/core/cfg.cpp
src/core/types.h
src/runtime/code.cpp
src/runtime/objmodel.cpp
src/runtime/util.cpp

saves between 5-10% with a very slight speed up.

Misc memory size reductions

---

src/asm_writing/icinfo.cpp
src/asm_writing/icinfo.h
src/asm_writing/rewriter.h
src/codegen/baseline_jit.cpp
src/codegen/baseline_jit.h
src/codegen/compvars.cpp
src/codegen/irgen.h
src/codegen/irgen/irgenerator.cpp
src/codegen/irgen/util.cpp
src/codegen/patchpoints.cpp
src/codegen/patchpoints.h
src/codegen/type_recording.cpp
src/codegen/type_recording.h
src/core/ast.h
src/runtime/ics.cpp
src/runtime/objmodel.cpp

this fixes the problems which I run into when I started to delete AST nodes (because new ones could end up having the same address as old ones).

Fix pointer reuse problems

---

src/runtime/import.cpp

this check is not very robust :-(

Fix leak check after path changes

---

from_cpython/setup.py

Copy CPython setup.py and add lots of Pyston changes.

Switch to CPython way to build standard C extensions.

---

README.md
docs/TIPS.md
src/core/stats.h

I think the option about stats is outdated. Thx.

Fix docs about stats option

---

src/runtime/dict.cpp
src/runtime/objmodel.cpp
src/runtime/types.cpp
test/tests/attrwrappers.py

And add some extra checking to make sure we don't make these kinds of mistakes more

Fix attrwrapper comparisons

---

src/codegen/irgen/util.h

this makes `ENABLE_SIGNAL_CHECKING = 0` work again

createAfter: don't crash when BB is empty

---

src/codegen/ast_interpreter.cpp
src/core/cfg.cpp
src/core/types.h
src/runtime/code.cpp
src/runtime/types.h

this was only a very small leak

ParamNames: don't leak BST_Name nodes

---

src/core/bst.h
src/core/cfg.cpp

Happy new year, it looks like a little bit late.
Anyway, I found an unused parameter. It looks like pyston wanted to record line numbers.
But, it looks like not using right now.

[Clean Up] Remove unused parmameter in BST_Name.
