src/runtime/builtin_modules/builtins.cpp, src/runtime/ics.h
spectral_norm.py runtime improves by about 5%:
rewriter_attempts: 135109 --> 55133
rewriter_commits: 80138 --> 162
runtime_ics_num: 40003 --> 15
slowpath_binop: 82702 --> 2726
=> Add a simple cache for runtime ICs

src/gc/collector.cpp
also keep a free list of chunks around to make subsequent collections faster.
results in TraceStack::pop and ::push being inlined and disappearing from the perf report (::push was at 3.99% before).
Also drops aggregate GC times for raytrace by ~5%.
before: gc_collections_us: 2151827
after: gc_collections_us: 2023809
=> use a vector of chunks for the TraceStack, instead of a vector of individual pointers.

src/core/types.h, src/gc/collector.cpp, src/gc/heap.cpp, src/gc/heap.h, src/runtime/types.h
with these two changes (on top of the TraceStack change already merged), I see this with average gc_collections_us timings:
before == master before TraceStack was merged.
raytrace:
before: 2126265.8
after: 1125626.9
reduction: 47%
fannkuch:
before: 2456650.1
after: 464613.6
reduction: 81%
spectral_norm:
before: 7679691.6
after: 1970772.3
reduction: 74%
chaos:
before: 9389854.3
after: 3874241.5
reduction: 58%
=> More gc perf changes

src/runtime/objmodel.cpp, src/runtime/types.h
Reduces slowpath_typecall from 40000 to 30 for spectral_norm
=> Mark enumerate_cls as safe for type call rewriting

src/analysis/scoping_analysis.cpp, src/codegen/ast_interpreter.cpp, src/core/stringpool.h
Speeds up the interpreter by about 10-15% when the higher tiers are disabled, in the normal version it does not change the performance of our benchmarks much because they are too short / to many hot functions :-(.
+ increased the OSR threshold to 200 and the reopt threshold to 100. this values looked like a better tade-off.
+ moved the interpreter in an anonymous namespace.
=> Small performance improvement when interpreting

CMakeLists.txt
now that the flatten attribute is removed we don't have to compile pyston in PIC mode.
=> Remove -fPIC

src/capi/types.h, src/core/types.h, src/runtime/builtin_modules/builtins.cpp, src/runtime/builtin_modules/gc.cpp, src/runtime/builtin_modules/sys.cpp, src/runtime/builtin_modules/thread.cpp, src/runtime/capi.cpp, src/runtime/generator.cpp, src/runtime/generator.h, src/runtime/objmodel.cpp, src/runtime/objmodel.h, src/runtime/types.cpp, src/runtime/types.h, test/tests/builtins.py
Implement the `builtin_function_or_method` type, which all the builtin functions are of (e.g., `sorted`).
Since we use the same calling convention for Python functions as our builtin C functions, I made a common base class, `BoxedFunctionBase` which has all the calling functionality, and two subclasses `BoxedFunction` and `BoxedBuilitinFunctionOrMethod`, each of which contributes the type, either `function_cls` or `builtin_function_or_method_cls`. (What a mouthful)
Difference is the attributes they have and stuff, e.g., `function_cls` is a descriptor which wraps itself in an `instancemethod`, and `builitin_function_or_method_cls` is not.
=> builtin functions

src/runtime/str.cpp, test/tests/str_functions.py
This small change will be needed by ```locale``` which gets imported by ```optparse```.
I split it out into a separate pull request because I think this is a performance regression and I would like to discuss a idea I have: 
- I would like to extend ```pyElements()``` to not use the generic iterable protocol when we know the class.
This should give us the same speed as a specialized implementation for every known iterable type while still preserving the the shortness of just a ```for (Box* e : rhs->pyElements()) ```.
=> Implement str.join(iterable)

src/analysis/type_analysis.cpp, src/codegen/ast_interpreter.cpp, src/codegen/irgen/irgenerator.cpp, src/codegen/unwinding.cpp, src/core/ast.cpp, src/core/ast.h, src/core/cfg.cpp, src/runtime/generator.cpp, src/runtime/generator.h, test/tests/generator_tracebacks.py
- fix tacebacks inside a generator frame: we have to also unwind the calling stack frame.
I'm not really happy with the way I implemented it because it takes advantage of an implementation detail (that ```ucontext``` and ```unw_context``` are the same).
This will have to change when we move to a different stack switching technique (probably soon) :-(. 
- added a clear exc info instruction:
Even when an exception happened inside a generator after the next ```yield``` the ```exc_info()``` will return none or the last exception in the calling frame from where the generator got called. (I hope I observed the behavior correctly.)
=> Generator tracebacks

minibenchmarks/pidigits.py, src/gc/gc_alloc.h, src/gc/heap.cpp, src/gc/heap.h, test/unittests/gc.cpp
The diff is kinda hard to deal with, but the biggest piece of this change is the addition of another arena (Large, between the old Small/Large with the old Large renamed to Huge.)
I also added some template functions to help factor out the shared code across all arenas.
pidigits was the motivating benchmark for this change, but almost all benchmarks show some improvement:
```
Saving results as 'three_arena'
pyston (calibration)                      :    1.0s baseline: 1.0 (+0.0%)
pyston nbody_med.py                       :    3.0s baseline: 3.0 (-0.6%)
pyston interp2.py                         :    6.4s baseline: 6.7 (-4.5%)
pyston raytrace.py                        :    7.8s baseline: 7.8 (-0.3%)
pyston nbody.py                           :   11.0s baseline: 11.1 (-0.8%)
pyston …
```
=> Add third GC arena

src/asm_writing/rewriter.cpp, src/asm_writing/rewriter.h
The reason for the speedup of spectral_norm is that we can now rewrite some stuff which did not fit inside the patchpoint before.
```
pyston (calibration)                      :    0.8s stock2: 0.8 (+2.5%)
pyston interp2.py                         :    5.9s stock2: 6.2 (-4.5%)
pyston raytrace.py                        :    6.9s stock2: 7.0 (-1.6%)
pyston nbody.py                           :    9.8s stock2: 9.6 (+1.9%)
pyston fannkuch.py                        :    7.0s stock2: 6.9 (+2.6%)
pyston chaos.py                           :   20.6s stock2: 21.6 (-4.6%)
pyston spectral_norm.py                   :   27.9s stock2: 34.2 (-18.6%)
pyston fasta.py                           :   17.1s stock2: 17.8 (-4.5%)
pyston pidigits.py                        :    4.4s stock2: 4.5 (-1.0%)
pyston …
```
=> Don't emit duplicate attr guards

src/gc/heap.cpp, src/gc/heap.h
For some reason the larger bucket sizes are causing a large perf hit
in spectral_norm.  It's unclear exactly why this is happening, but
theories are legion.  More investigation is warranted, but this gets us
back from the perf regression.
Also hoist the atom_idx calculation out of a couple of loops that were
iterating over object indices.
```
pyston (calibration)                      :    1.0s baseline: 1.0 (+1.7%)
pyston nbody_med.py                       :    2.8s baseline: 2.9 (-4.3%)
pyston interp2.py                         :    6.5s baseline: 6.5 (-0.4%)
pyston raytrace.py                        :    8.1s baseline: 8.0 (+0.3%)
pyston nbody.py                           :   10.3s baseline: 10.7 (-3.3%)
pyston fannkuch.py                        :    7.3s baseline: 7.1 (+1.8%)
pyston …
```
=> remove the larger buckets, and hoist some math out of loops.

minibenchmarks/bm_ai.py, src/runtime/generator.cpp
after bff1661, bm_ai.py crashed with an assert because we ran out of memory allocating generator stacks.
This change adds a simple destructor for BoxedGenerators, and some code to make use of the (already present in the file) available_addrs for some simple reuse.
As it stands, performance is pretty bad.  I lowered the number of iterators of the test to 1, and:
```sh
$ time python minibenchmarks/bm_ai.py
real	0m0.631s
user	0m0.625s
sys	0m0.006s
$ time ./pyston_release minibenchmarks/bm_ai.py
Warning: converting unicode literal to str
Warning: converting unicode literal to str
Warning: converting unicode literal to str
Warning: converting unicode literal to str
real	0m33.669s
user	0m24.300s
sys	0m9.367s
```
Clearly there's a lot going on with generators.  I merged #302 locally, and while …
=> reuse generator stacks

from_cpython/Modules/selectmodule.c, src/capi/typeobject.cpp, src/runtime/capi.cpp, src/runtime/objmodel.cpp, src/runtime/types.h, test/test_extension/slots_test.c, test/tests/capi_slots.py, test/tests/select_test.py
the select module uses tp_getattr to implement the `poll` type, so add places where we need to call it.
PyCFunction_NewEx was also needed (the tp_getattr implementation called it.)
Finally, PyNumber_Int was needed to run the changes to select_test.py.
=> add tp_getattr support, PyCFunction_NewEx, and most of PyNumber_Int's behavior

src/runtime/builtin_modules/builtins.cpp, src/runtime/types.cpp, test/tests/functools_test.py
With this small patch applied we should be able to successfully ```import optparse``` even after #293 is applied (but this patch depends on #292 too)
The suggested order to apply the patches would be:
- #292
- this one
- #293
=> make functools.wrap() work

CMakeLists.txt
Alright so using the git submodule HEAD as OUTPUT in a cmake custom command to keep track of the update was a stupid idea because running clean will delete the HEAD files! Please merge before someone tries to clean.
=> cmake fix gitsubmodules update

src/analysis/type_analysis.cpp, src/codegen/compvars.cpp, src/codegen/compvars.h, src/codegen/irgen.h, src/codegen/irgen/irgenerator.cpp, src/codegen/runtime_hooks.cpp, src/codegen/runtime_hooks.h, src/core/types.h, src/runtime/inline/link_forcer.cpp, src/runtime/objmodel.cpp, src/runtime/objmodel.h, src/runtime/types.h, test/tests/xrange.py
If the type analysis successfully determines that the __iter__() and __hasnext__()
methods we can now replace them with direct calls to the destination.
Else we create a patchpoint and do a rewrite.
- I'm not sure if there is a cleaner way todo this?
- I inverted the check inside ```BoxdedClass::hasGenericGetattr()``` because I think this is a bug. 
- inside the compvar code I'm now passing the ```CallattrFlags``` around instead of the ```bool clsonly```
- only the most common case gets rewriten. e.g. if the object does not implement "__iter__" I fallback and call  a helper function
``` 
pyston (calibration)                      :    0.8s baseline2: 0.8 (+2.7%)
pyston interp2.py                         :    3.4s baseline2: 3.7 (-8.9%)
pyston raytrace.py                        :    6.7s …
```
=> Add compvars and rewriting support for GET_ITER nodes 

src/runtime/builtin_modules/builtins.cpp, src/runtime/builtin_modules/sys.cpp, test/tests/sys_test.py
I hard coded the file system encoding to be UTF-8 on non windows systems.
Initially I replicated the behavior of CPython and imported the functions but then I thought it's overkill.
As far as I know every linux system we care about uses UTF-8 for file names. The CPython code retrieves on startup with ```nl_langinfo()``` the encoding and then tries to load the corresponding encoder (--> we would run a lot of additional python code shortly after ```setupRuntime()```.
Did I miss something?
=> Add sys.getdefaultencoding and sys.getfilesystemencoding

src/asm_writing/rewriter.cpp, src/asm_writing/rewriter.h, src/runtime/objmodel.cpp
using this for the std::vector's we use during calls helps some, with the biggest reduction being -10% on raytrace.
```
pyston (calibration)                      :    1.0s baseline: 1.0 (+0.1%)
pyston nbody_med.py                       :    2.1s baseline: 2.2 (-2.2%)
pyston interp2.py                         :    4.1s baseline: 4.0 (+0.7%)
pyston raytrace.py                        :    6.7s baseline: 7.6 (-10.8%)
pyston nbody.py                           :    7.8s baseline: 8.0 (-2.3%)
pyston fannkuch.py                        :    6.3s baseline: 6.2 (+1.8%)
pyston chaos.py                           :   20.1s baseline: 20.7 (-3.2%)
pyston spectral_norm.py                   :   16.8s baseline: 16.5 (+2.1%)
pyston fasta.py                           :    5.8s baseline: 5.9 (-2.2%)
pyston …
```
=> use llvm::SmallVector to reduce allocations

src/codegen/ast_interpreter.cpp, src/runtime/builtin_modules/builtins.cpp, src/runtime/objmodel.h, test/tests/map.py
in addition I added a small helper function for unpacking our function call argument array.
We could also call ```std::tie(arg1, arg2, arg3, args) =  getTupleFromArgsArray(a, size)``` instead of the ```std::arg<>``` calls.
=> Implement vararg map()

Makefile, from_cpython/CMakeLists.txt, from_cpython/Include/cStringIO.h, from_cpython/Python/structmember.c, src/runtime/capi.cpp, src/runtime/file.cpp, src/runtime/objmodel.cpp, src/runtime/types.cpp, src/runtime/types.h, test/tests/complex.py, test/tests/cstringio_test.py, test/tests/file.py
- the cStringIO module needs support for setting member descriptors
- fixed a bug: when adding the ```readonly``` field I noticed that the get member descriptor rewriting code generates a 64bit mem comparison for the 32bit offset value, thus comparing partially undefined memory.
=> Add cStringIO module + basic support for setting member descriptors

from_cpython/Objects/unicodeobject.c, src/runtime/str.cpp, test/tests/unicode_test.py
+ added unicode support to ```strAdd```
+ ```getWriteableStringContents``` return a pointer to the '\0' char when the string is empty. (Should be safe: http://www.cplusplus.com/reference/string/string/operator[]/)
+ Treat UTF-8 and utf-8 the same. Without this change we currently can't handle UTF-8 (uppercase) yet. I found it very confusing that utf-8 was working. I know that we have to implement the general dispatch function for unknown encodings too but I still think the case should not make a difference and for know this is enough to make it work.
=> Smaller changes to get more of virtualenv running

from_cpython/CMakeLists.txt, src/CMakeLists.txt
-added -Wno-unused-result and -Wno-strict-aliasing for gcc 4.8.2 compatibility
=> cmake ignore gcc warnings in from_cpython

src/runtime/builtin_modules/builtins.cpp, src/runtime/builtin_modules/sys.cpp, src/runtime/builtin_modules/thread.cpp, src/runtime/capi.cpp, src/runtime/classobj.cpp, src/runtime/dict.cpp, src/runtime/file.h, src/runtime/generator.cpp, src/runtime/inline/xrange.cpp, src/runtime/iterobject.cpp, src/runtime/list.cpp, src/runtime/objmodel.cpp, src/runtime/set.cpp, src/runtime/set.h, src/runtime/str.cpp, src/runtime/super.cpp, src/runtime/traceback.cpp, src/runtime/tuple.cpp, src/runtime/types.cpp, src/runtime/types.h, test/tests/weakref2.py, test/tests/weakref3.py, test/tests/weakref4.py, test/tests/weakref5.py, test/tests/weakrefs.py
All user-defined subclasses can be weakly referenced after this change, which is slightly more permissible than [cpython's implementation](https://docs.python.org/2/library/weakref.html).
There are a few holes, though, as the only builtin types that provide for weak references at present are type objects, functions, and instance methods.  We fail loudly (_weakref throws an exception) when an attempt is made to weakly reference something we don't support.
Subtypes of types that define a `tp_weaklistoffset` inherit their parent's (so we don't have multiple weaklists).  Also, if there is no `tp_weaklistoffset` and it's a user defined type, we inflate the object by `sizeof(Box**)` and set its `tp_weaklistoffset` appropriately.
With this change we can successfully `import numbers`.
I also …
=> add weakref support for user defined subtypes (with inheritance) and 'type' instances

src/core/cfg.cpp, src/runtime/builtin_modules/builtins.cpp, src/runtime/capi.cpp, src/runtime/import.cpp, src/runtime/import.h, test/tests/name_mangling.py, test/tests/package_import_in_nonpackage.py, test/tests/package_test.py, test/tests/relative_import1.py, test/tests/relative_import1_pkg/__init__.py, test/tests/relative_import1_pkg/string.py, test/tests/relative_import2.py, test/tests/relative_import2_pkg/__init__.py, test/tests/relative_import2_pkg/foo.py, test/tests/relative_import3.py, test/tests/relative_import3_pkg/A/__init__.py, test/tests/relative_import3_pkg/A/stuff.py, test/tests/relative_import3_pkg/B/__init__.py, test/tests/relative_import3_pkg/B/name2.py, test/tests/relative_import3_pkg/C.py, test/tests/relative_import3_pkg/C/__init__.py, test/tests/relative_import3_pkg/C/name1.py, test/tests/relative_import3_pkg/C/name3.py, test/tests/relative_import3_pkg/__init__.py, test/tests/relative_import4.py, test/tests/relative_import4_pkg/__init__.py, test/tests/test_package/absolute_import.py, test/tests/test_package/absolute_import_with_future.py, test/tests/test_package/intrapackage_import.py
most of the changes are to support `from .foo import bar`, but there were other fixes along the way (absolute imports from within a package).  I also added the path parameter to imp.find_module while I was at it.
With this change `import json` gets past its relative imports.
=> add support for relative imports, and bring our import api closer to cpython

CMakeLists.txt, Makefile, tools/tester.py
I was frustrated by having to read tester.py's source whenever I wanted to know how to use it, so now it's self-describing.
Unfortunately, the parsing of `-a` changes slightly; instead of `-a -n` (or some other option), you have to invoke `-a=-n`, to avoid `argparse` interpreting `-n` as another option. Seems a small price to pay, but I can probably find a way to do this better if you want to keep the old parsing.
=> make tester produce useful help messages

src/runtime/file.cpp, src/runtime/objmodel.cpp, test/tests/no-softspace.py
PyFile_Softspace (according to cpython docs) returns 0 and clears all errors if there was a problem getting or setting "softspace".  It's pretty clear that the rest of the codebase assumes as much from softspace as well.  We might be able to also wrap isSubclass in the try{} block and add noexcept, but I'm not sure if the isSubclass check would cause cpython to fail.
without this change we abort because of the catch block in PyFile_Softspace.  fixing that to return 0 bubbles Attribute errors from a few places (ast_interpreter.cpp, jitted code, etc.)
=> don't let AttributeError exceptions bubble out of softspace.  fixes fasta.py

CMakeLists.txt, Makefile, from_cpython/CMakeLists.txt, from_cpython/Include/pythonrun.h, from_cpython/Modules/getpath.c, src/core/options.cpp, src/jit.cpp, src/runtime/builtin_modules/sys.cpp, src/runtime/capi.cpp, test/tests/sys_test.py
I'm not 100% happy with this change but I think it's for now quite reasonable behavior and it helps getting virtualenv running.
It not exactly the same behavior as cpython but we use a different directory structure so it can't be.
(PyPy is also different then cpython in this regard).
The ```site.py``` script will now get imported on startup except ```-S``` is specified. I added the flag to all our regressions test runs --> ```site.py``` loading won't get tested by our test-suite (because otherwise several tests which check the stats will fail and also ```make check``` would be much slower). We probably need to adopt our site.py script in the future.
I removed printing out ```sys.prefix``` because it won't be the same as cpython. (It depens on the install location,...)
=> Add sys.prefix, sys.exec_prefix, site.py and $PYTHONPATH support

.travis.yml, CMakeLists.txt, Makefile, docs/INSTALLING.md, from_cpython/CMakeLists.txt, from_cpython/Modules/_sqlite/cache.c, from_cpython/Modules/_sqlite/connection.c, from_cpython/Modules/_sqlite/cursor.c, from_cpython/Modules/_sqlite/module.c, from_cpython/Modules/_sqlite/prepare_protocol.c, from_cpython/Modules/_sqlite/row.c, from_cpython/Modules/_sqlite/statement.c, from_cpython/Objects/bufferobject.c, src/runtime/builtin_modules/builtins.cpp, src/runtime/capi.cpp, src/runtime/long.cpp, src/runtime/types.cpp, test/tests/buffer_compare.py, test/tests/buffer_test.py, test/tests/sqlite_test.py, test/unittests/CMakeLists.txt
also add some capi functions (unimplemented) to get sqlite3 module to link.
the tests are in no way exhaustive, but sqlite is importable and works for simple tables.
also, the buffer type is missing it's tp_compare (we assert in PyType_Ready if tp_compare is not null), so we'll need to deal with that.
=> add cpython buffer + sqlite3 module, and a couple tests.

src/runtime/objmodel.cpp, test/tests/softspace.py
cpython can be observed setting softspace on an object even if it doesn't start with it.
the getattrInternal in softspace() throws an exception the first time through since the
attribute isn't present.  if we don't turn around and set it on the object, we throw
every time we print, which causes a pretty large perf regression in fasta (from ~6 seconds to ~17 seconds.)
=> split the getattr/setattr of softspace into two try blocks

src/codegen/pypa-parser.cpp, src/jit.cpp, src/runtime/stacktrace.cpp, test/tests/json_test.py, test/tests/prevent_nonascii_attrs.py, test/tests/unicode_test.py, test/tests/unicodedata_test.py
We support the \u, \U and \N escape sequences and
the unicode_literals option.
In addition updates pypa to latest version with unicode support.
=> Add support for unicode literals when using pypa

CMakeLists.txt
-don't pass empty CFLAGS='' when buliding libunwind in release mode
-revert libunwind submodule to older 65ac867416 (same as INSTALLING.md)
=> cmake fix libunwind flags

src/codegen/parser.cpp, src/codegen/pypa-parser.cpp, src/codegen/serialize_ast.cpp, src/codegen/serialize_ast.h, src/core/util.cpp, src/core/util.h, src/jit.cpp
before ```import pip``` -I took about 2.5sec on the second run, with this change it takes about 1.5sec
While the pypa parser is faster then our current cpython approach, caching the parse result is a significant speed improvement for large scripts. (import pip without cached files takes 7.5sec (cpython parser) vs. 2.5secs (pypa))
- I used the same binary format but choose a different magic string otherwise our pypa/cpython parser test would be useless because the result of the first run would be used instead of calling the parser.
- I'm unhappy with the code duplication :-( on the other-hand this is probably something we don't touch often. I could not use the normal AST recursive visit pattern because it does not visit the nodes in the order which our cache format requires.
=> Cache pypa parsed AST to disk

src/core/options.cpp, src/jit.cpp, tools/astprint.cpp
Switches the meaning of -x.
In addition update to latest pypa version
@tjhance: I haven't tried it with your ```exec``` support patch. But I hope I fixed the missing newline issue you run into.  Please let me know if you still encounter problems.
@vinzenz: Thanks for writing the parser!
=> Use the pypa parser as the default parser.

src/analysis/scoping_analysis.cpp, src/analysis/scoping_analysis.h, src/codegen/ast_interpreter.cpp, src/codegen/compvars.cpp, src/codegen/irgen/irgenerator.cpp, src/codegen/runtime_hooks.cpp, src/codegen/runtime_hooks.h, src/codegen/unwinding.cpp, src/runtime/inline/link_forcer.cpp, src/runtime/objmodel.cpp, src/runtime/objmodel.h, src/runtime/types.cpp, src/runtime/types.h, test/tests/static_closure_locations.py, tools/tester.py
This needs a lot of cleaning up but I wanted to solicit feedback on the approach first...
Right now we handle closure as normal objects with `HCAttrs`, and we de-reference variables from closures by walking up the closures until we find one with the variable name. This is overly-dynamic to the point of being wrong (see my new `static_closure_locations.py` test case):
```python
def f():
c = 0 
a = 0 
def g():
print c
print a
def h():
print c
def j():
print c
print a    # should throw a NameError
j() 
a = 1 
h() 
g() 
f()
```
Since the the set of names is a closure is fixed, in this diff I statically determine the size of the closure and the mapping of names to offsets (letting undefined variables be `NULL`). Then the IR for a closure lookup just consists of some pointer-dereferences with …
=> statically laid out closures

src/codegen/ast_interpreter.cpp, src/core/contiguous_map.h, src/gc/collector.cpp, src/runtime/dict.cpp, src/runtime/objmodel.cpp, src/runtime/traceback.cpp, src/runtime/types.h
A few changes (mostly dealing with scanning) that help GC perf.
```
pyston (calibration)                      :    1.0s baseline: 1.0 (-0.4%)
pyston django_migrate.py                  :    5.9s baseline: 10.7 (-45.1%)
pyston interp2.py                         :    6.0s baseline: 5.9 (+1.5%)
pyston raytrace.py                        :    6.7s baseline: 6.8 (-1.1%)
pyston nbody.py                           :    8.9s baseline: 9.3 (-4.0%)
pyston fannkuch.py                        :    8.1s baseline: 8.0 (+0.8%)
pyston chaos.py                           :   21.3s baseline: 20.5 (+4.2%)
pyston fasta.py                           :    6.0s baseline: 5.6 (+8.2%)
pyston pidigits.py                        :    5.4s baseline: 5.5 (-0.6%)
pyston richards.py                        :    2.0s baseline: …
```
=> a few changes which help out GC performance

from_cpython/Objects/unicodeobject.c, src/runtime/objmodel.cpp, src/runtime/str.cpp, src/runtime/types.h, test/tests/unicode_test.py
keeps from allocating a BoxedString every time we need a unicode object's hash().
saves ~1% on django_migrate.py.
=> use the same hash function for both unicode and string objects

src/codegen/ast_interpreter.cpp, src/codegen/irgen/hooks.cpp, src/codegen/irgen/hooks.h, src/codegen/irgen/irgenerator.cpp, test/tests/exec_in_basic_test.py
This lets you do `exec code in dict`, sort of
It doesn't pass in the globals, but it should still work a lot of the time (as long as there's no global variable reference from within a function in the exec, and if there is nothing explicitly declared `global`)
=> basic implementation of `exec code in dict`

src/runtime/builtin_modules/sys.cpp
implement Py_GetPlatform along the way.  CPython's implementation of this function just returns PLATFORM (which gets #defined at build time from the configure script.)
=> support 'linux2', 'darwin', and 'unknown' for sys.platform

from_cpython/CMakeLists.txt, src/CMakeLists.txt, test/unittests/CMakeLists.txt, tools/CMakeLists.txt
This is done so that cmake knows when a source file has been added or removed, otherwise cmake would have to be manually rerun.
=> cmake explicitly list all c++ source files

src/analysis/fpc.h, src/analysis/function_analysis.cpp, src/analysis/function_analysis.h, src/analysis/type_analysis.cpp
This change does not change our analysis algorithms but instead speeds them up by using llvms containers. This should not change the generated output.
```
for test/integration/django_test.py
us_compiling_analysis_definedness: 130569 --> 29087
us_compiling_analysis_liveness: 132502 --> 102092
us_compiling_analysis_phis: 229944 --> 188633
us_compiling_analysis_types: 214522 --> 36165
```
=> Speedup analysis by using llvms more cache friendly map/set algorithms

microbenchmarks/re_perf.py, src/asm_writing/rewriter.cpp, src/asm_writing/rewriter.h, src/runtime/objmodel.cpp, src/runtime/types.h, test/tests/capi_method_ics.py
This involves
- special-casing their `__get__`
- adding some ability to rewrite calls to functions that take *args
=> Rewrite calls into BoxedMethodDescriptors

CMakeLists.txt, Makefile, from_cpython/Lib/platform.py, src/capi/abstract.cpp, src/codegen/entry.cpp, src/runtime/builtin_modules/builtins.cpp, src/runtime/capi.cpp, src/runtime/classobj.cpp, src/runtime/float.cpp, src/runtime/import.cpp, src/runtime/inline/xrange.cpp, src/runtime/int.cpp, src/runtime/list.cpp, src/runtime/long.cpp, src/runtime/long.h, src/runtime/objmodel.cpp, src/runtime/str.cpp, src/runtime/tuple.cpp, src/runtime/types.cpp, src/runtime/util.cpp, test/tests/builtins.py, test/tests/gcj_2014_2_d.py, test/tests/index_meth.py, test/tests/intmethods.py, test/tests/list.py, test/tests/long.py, test/tests/tuples.py, test/tests/xrange.py
Add ```pow()```, ```long.__mod__```, ```__index__```, slice and xrange long arg support,
support for 3arg pow, long("0xBB", 16) and long("0xBBL", 0)
Support for ```__eq__``` method overwriting for old style classes is still missing, but when that's in place we fail only 2 out of 1820 pycrypto tests.
=> Misc stuff for pycrypto

.gitmodules, from_cpython/Include/longobject.h, src/codegen/ast_interpreter.cpp, src/codegen/irgen/hooks.cpp, src/runtime/classobj.cpp, src/runtime/long.cpp, src/runtime/types.cpp, test/integration/pycrypto_0001-fastmath-Add-support-for-Pyston.patch, test/integration/pycrypto_test.py, test/tests/functions.py, test/tests/oldstyle_classes.py
Adds:
- pycrypto integration test
- pyston specific CAPI extension for converting between a python longs and GMP
- old style classes support for ```__eq__``` and ```__ne__```
- cancel OSR if number of live syms exceeds 225
With this changes all pycrypto tests succeed
=> Add a pycrypto integration test

Makefile, from_cpython/Modules/_csv.c, from_cpython/Modules/_io/bufferedio.c, from_cpython/Modules/_ssl.c, from_cpython/Modules/_struct.c, from_cpython/Modules/binascii.c, from_cpython/Modules/datetimemodule.c, from_cpython/Modules/posixmodule.c, from_cpython/Modules/resource.c, from_cpython/Modules/selectmodule.c, from_cpython/Modules/signalmodule.c, from_cpython/Modules/socketmodule.c, from_cpython/Modules/threadmodule.c, from_cpython/Modules/timemodule.c, from_cpython/Modules/zipimport.c, from_cpython/Modules/zlibmodule.c
It seems like there's only one potentially bad one (zip_directory_cache),
and the rest are more or less benign (most of the occurrences are added
to the module as well as attributes), but it's probably good practice.
=> Add PyGC_AddRoot calls any time we assign to a static variable

.gitmodules
so that the untracked pyc files don't cause the repo to be marked as dirty
=> ignore untracked files in the gflags submodule

src/runtime/tuple.cpp
cpython only allows this for objects that are exactly the tuple type, and for good reason: we can't go around `memmove` stuff willy-nilly (especially since it could be an opaque CAPI object or something). Furthermore, this thing has pretty special-case usage, so it isn't really necessary. So let's keep the code simple and enforce this restriction, too.
=> prohibit _PyTuple_Resize for objects that are subclasses of tuple

src/runtime/list.cpp, test/tests/list_subclassing.py
splitting out the smaller self-contained bits of the django-fixes PR/branch.  `==` and `!=` both handle list subclasses.
=> list __eq__ and __ne__ work for rhs's that are list subclasses

src/runtime/descr.cpp, src/runtime/objmodel.cpp, src/runtime/types.cpp, src/runtime/types.h
This was named wrong and it was getting confusing. On top of that, its `tp_name` was wrong.
=> rename member -> member_descriptor

test/cpython/exception_hierarchy.txt
The `test_pep352.txt` opens this file. So this gets the test passing... for cpython.
=> add exception_hierarchy.txt which test/cpython/test_pep352.txt needs

Makefile, src/analysis/function_analysis.cpp, src/analysis/function_analysis.h, src/codegen/ast_interpreter.cpp, src/codegen/codegen.cpp, src/codegen/irgen.cpp, src/codegen/irgen/hooks.cpp, src/codegen/irgen/irgenerator.cpp, src/codegen/irgen/irgenerator.h, src/core/stats.cpp, src/core/types.h, src/gc/heap.cpp, src/gc/heap.h, src/runtime/stacktrace.cpp, test/tests/package_test.py, test/tests/test_package/absolute_import.py, test/tests/test_package/absolute_import_with_future.py, test/tests/test_package/intrapackage_import.py, test/unittests/analysis.cpp, tools/tester.py
This eliminates 20% of the memory used by "import pip".  We will probably want to cache them again eventually, but it seems like they're reused pretty rarely so I'm hopeful we won't see too much of a perf impact for now.
=> Reduce memory by not caching analysis passes

src/runtime/list.cpp, test/tests/list_subclassing.py
basically the same as 5209849, but for the other comparisons.  also add `subclass op subclass` comparison tests so that we ensure pyston doesn't rewrite the op to the reverse and succeed due to one of them being `list_cls`.
=> fix the remaining subclass checks for list comparisons <, <=, >, >=

src/capi/types.h, src/codegen/compvars.cpp, src/core/common.h, src/runtime/descr.cpp, src/runtime/dict.cpp, src/runtime/objmodel.cpp, src/runtime/types.cpp, src/runtime/types.h, test/tests/function_instancemethod.py, test/tests/instance_methods.py
Add the `im_class` field to `BoxedInstanceMethod` and implement `repr`.
There were a lot of places to insert it, hopefully I didn't screw up. It's kind of tricky: for example you can't assume it's a `BoxedClass`. One occasion where it wouldn't be a `BoxedClass` is if you were using old-style classes:
```
>>> class C:
...     def f(self): pass
... 
>>> C.f.im_class
<class __main__.C at 0x7fa97d41e258>
>>> type(C.f.im_class)
<type 'classobj'>
```
I also had to add support for the new field for the `InstanceMethodType` in codegen.
=> Add im_class field to BoxedInstanceMethod, implement instancemethodRepr

from_cpython/Include/fileobject.h, src/codegen/parser.cpp, src/codegen/pypa-parser.cpp, src/gc/collector.cpp, src/gc/collector.h, src/runtime/file.cpp, test/tests/coding_cp1252.py, test/tests/coding_koi8.py
I expect that there are still bugs hiding but at least the pyston tests pass and pyxl helloworld works.
This patch depends on a not yet merged pypa change https://github.com/vinzenz/libpypa/pull/31 so is not yet ready for merging.
=> Add support for specifying the encoding inside source files.

from_cpython/Objects/weakrefobject.c, src/capi/object.cpp, test/tests/weakref_proxy.py
I had to change ```new_weakref``` to use ```tp_alloc``` instead of ```PyObject_GC_New```
in order to create a weak ref because ```PyObject_GC_New``` allocated memory is scanned
conservatively.
```tp_alloc``` points to ```PystonType_GenericAlloc``` and is of PYTHON type.
@toshok Maybe you could also take a look at it and check if this makes sense.
=> Add support for weakref.proxy

src/.clang-format, src/analysis/scoping_analysis.cpp, src/analysis/type_analysis.cpp, src/asm_writing/icinfo.cpp, src/asm_writing/rewriter.cpp, src/codegen/ast_interpreter.cpp, src/codegen/irgen/irgenerator.cpp, src/codegen/patchpoints.h, src/core/ast.h, src/core/cfg.cpp, src/core/types.h, src/runtime/generator.cpp, src/runtime/objmodel.cpp, src/runtime/rewrite_args.h, src/runtime/types.cpp
The really long constructor initializer lists are pretty hard to read. This turns on the ConstructorInitializerAllOnOneLineOrOnePerLine option, which puts them one-per-line.
I realize that format style changes can be contentious :P so feel free to ignore if you disagree.
=> turn on ConstructorInitializerAllOnOneLineOrOnePerLine

src/runtime/tuple.cpp, src/runtime/types.h
(This depends on a few other PRs so just look at the last commit. As far as I know github doesn't have a great way to do PRs that depend on other PRs that live in a fork. :\ )
Since I made BoxedTuple a subclass of BoxVar, there's no need for an `nelts` field, since we can just use `BoxVar::ob_size`. Also, since the elements are stored at a fixed offset, we don't need a `Box** elts`, we can just make it an array `Box* elts[]`.
=> Clean up the BoxedTuple class

from_cpython/Objects/iterobject.c, src/capi/types.h, src/runtime/generator.cpp, src/runtime/types.cpp, src/runtime/types.h
convert both generators and PyCallIter (used for the sre match iteration code, amongst other places) to use `__hasnext__`-style iteration.  This reduces the number of exceptions thrown by django, and trims about 3s off the django integration test (using pyston_dbg).
the gcc warning fix and `fact()` change were to get make check to succeed for me.
=> Fewer StopIteration exceptions

.travis.yml, Makefile, src/jit.cpp, test/extra/pycurl_test.py
I don't feel like it's worth adding libcurl to our dependencies
just so that we can test pycurl.  Let's try adding it as a
Travis-CI-only test; I'm slightly worried that that will confuse people,
but I think we're already pretty used to travis-ci being a more
comprehensive test suite.
=> Add pycurl as an 'extra' test

from_cpython/Include/pyconfig.h, from_cpython/Include/pymath.h, from_cpython/Include/pyport.h, src/runtime/capi.cpp
Previously we were only copying them when we noticed they were needed,
but we've been spending a fair bit of time hunting down issues that
are caused by a missing HAVE_ define.
So instead, bulk-copy the ones that the CPython configure script determined.
I bet we'll start running into some that were available on my 14.04
machine but won't be on other configurations; I'm hoping that an extra
define is easier to debug than a missing one (build error vs run error),
making this the better approach.
=> Copy all HAVE_FOO defines from cpython

src/analysis/scoping_analysis.cpp, src/capi/object.cpp, src/codegen/ast_interpreter.cpp, src/codegen/irgen/hooks.cpp, src/codegen/pypa-parser.cpp, src/core/cfg.cpp, src/runtime/builtin_modules/builtins.cpp, src/runtime/builtin_modules/pyston.cpp, src/runtime/builtin_modules/thread.cpp, src/runtime/capi.cpp, src/runtime/classobj.cpp, src/runtime/dict.cpp, src/runtime/file.cpp, src/runtime/float.cpp, src/runtime/import.cpp, src/runtime/list.cpp, src/runtime/long.cpp, src/runtime/objmodel.cpp, src/runtime/set.cpp, src/runtime/str.cpp, src/runtime/super.cpp, src/runtime/tuple.cpp, src/runtime/types.cpp, src/runtime/types.h
Create it on demand whenever we need it. We can do this since we (i) save the size in `ob_size` and (ii) the char data is at a fixed offset.
=> remove the llvm::StringRef from BoxedString

src/runtime/generator.cpp, test/tests/generators.py
Before this patch we couldn't run 'list(G())' if G contained a explicit raise StopIteration statement.
This also adds support for custom StopIteration subclasses.
=> Generators: Support explicit StopIteration raising.

from_cpython/Objects/stringobject.c, src/capi/abstract.cpp, src/capi/modsupport.cpp, src/capi/typeobject.cpp, src/capi/typeobject.h, src/runtime/capi.cpp, src/runtime/int.cpp, src/runtime/objmodel.cpp, src/runtime/str.cpp, src/runtime/types.cpp, test/tests/dict_setting.py, test/tests/intmethods.py, test/tests/mutable_bases.py, test/tests/str_functions.py
- Allow changing ```class.__bases__```:
I copied the implementation from cpython but I'm not sure if the ```same_slots_added``` method is correct for pyston.  I'm not sure if I have to also check for additional things.
It looks like we are stricter than cpython (```tp_basicsize``` will more often have a different size) and support less sublassing.
- Add ```attrwrapper.clear()```:
My implementation looks very ugly, is there a cleaner way to clear the attributes?
=> Misc stuff

Makefile, from_cpython/CMakeLists.txt, from_cpython/Include/pyexpat.h, from_cpython/Modules/pyexpat.c, from_cpython/setup.py, src/capi/modsupport.cpp, test/cpython/test_pyexpat.py
I disabled the custom traceback stuff for now because we don't support it yet.
It's using the system libexpat but we could also use cpythons own copy.
=> Add pyexpat support

tools/timer_diff.py
if `PYSTON_TIMERS_IN_TICKS` environment variable is set, don't convert to usec on output.
tools/timer_diff.py outputs differences (above a threshold) from before/after stats dumps and color codes green the positive changes and red the negative ones.  for instance this output shows a good change (everything here is green):
```
$ python tools/timer_diff.py before after
us_timer_caching_parse_file, before 13064175701, after 272745376, delta -12791430325 (approx -4.57 sec) 
us_timer_chosen_cf_body_builtins, before 5193281273, after 3538990235, delta -1654291038 (approx -590.82 msec) 
us_timer_gettraceback, before 39122506231, after 29284971184, delta -9837535047 (approx -3.51 sec) 
us_timer_raiseraw, before 16759458630, after 11021429623, delta -5738029007 (approx -2.05 sec) …
```
=> StatTimer comparisons

CMakeLists.txt, libunwind_patches/0003-use-a-sorted-array-for-registered-objects-and-do-a-b.patch
This patch adds binary searching of dynamically registered objects (same as the libgcc hack from before).
before the patch pyston_release does django-template in ~14 seconds
after the patch it takes ~10 seconds.
=> add libunwind_patch for binary search

CMakeLists.txt, src/codegen/parser.cpp, src/codegen/serialize_ast.cpp, src/codegen/serialize_ast.h, src/gc/collector.cpp, src/gc/collector.h, src/jit.cpp, src/runtime/cxx_unwind.cpp, src/runtime/import.cpp, test/tests/pyc_import_target.py, test/tests/pyc_stress_test.py
and add a pyc "stress test".
I think these issues are the source of our sporadic ci failures;
it makes sense based on where things fail (usually in the parser), and
because it's stateful (if you already have pycs generated you don't
run into the issue) and because it only happens in multithreaded mode.
changes:
- read the entire file at once, then do checks
- add a simple xor checksum in addition to the expected length
=> Make our pyc handling more robust

from_cpython/CMakeLists.txt, from_cpython/Include/methodobject.h, from_cpython/Include/pyconfig.h, from_cpython/Modules/threadmodule.c, src/capi/modsupport.cpp, src/capi/typeobject.cpp, src/capi/types.h, src/core/types.h, src/gc/collector.cpp, src/gc/collector.h, src/gc/heap.cpp, src/runtime/builtin_modules/sys.cpp, src/runtime/builtin_modules/thread.cpp, src/runtime/capi.cpp, src/runtime/objmodel.cpp, src/runtime/types.cpp, test/tests/class_noctor.py, test/tests/object_new_arguments.py, test/tests/threading_local.py, test/tests/weakrefs_extensions.py
Gives us some nice features, but had some more dependencies than I anticipated:
- setting object.tp_init properly (cpython wants to check `cls->tp_init == object_cls->tp_init`)
- supporting weakrefs on extension types
=> switch to CPython's thread._local implementation

from_cpython/Objects/floatobject.c, src/codegen/ast_interpreter.cpp, src/core/types.h, src/runtime/objmodel.cpp, src/runtime/objmodel.h, src/runtime/types.cpp, src/runtime/types.h, test/tests/weakref4.py, tools/perf_collect.sh, tools/perf_diff.py
```
pyston django_migrate.py                  :    2.3s baseline: 2.3 (-1.7%)
pyston django-template.py                 :   15.1s baseline: 15.4 (-1.6%)
pyston interp2.py                         :    5.3s baseline: 6.3 (-15.1%)
pyston raytrace.py                        :    6.1s baseline: 6.2 (-0.7%)
pyston nbody.py                           :    8.4s baseline: 8.1 (+4.1%)
pyston fannkuch.py                        :    7.5s baseline: 7.5 (+0.2%)
pyston chaos.py                           :   20.2s baseline: 20.0 (+0.7%)
pyston fasta.py                           :    5.4s baseline: 5.4 (+0.3%)
pyston pidigits.py                        :    5.7s baseline: 5.7 (+0.0%)
pyston richards.py                        :    2.5s baseline: 2.7 (-6.2%)
pyston deltablue.py                       :    1.8s …
```
=> Convert runtime functions to take llvm::StringRef

Makefile, from_cpython/Include/pyerrors.h, src/codegen/irgen/hooks.cpp, src/runtime/builtin_modules/sys.cpp, src/runtime/capi.cpp, src/runtime/objmodel.cpp, src/runtime/types.cpp, test/integration/virtualenv_test.py, test/tests/builtins.py, test/tests/builtins_getitem.py, test/tests/exec_in_test.py
- changed the ```id()``` builtin to directly output the pointer value. I find this useful for debugging.
- Added ```PyErr_GetExcInfo``` and ```PyErr_SetExcInfo```
- they only got added in CPython >= 3.3 but Cython uses them in non cpython mode and they are useful.
- they are used to set/retrieve ```sys.exc_info```
- fixed ```__builtins__["attr"]``` usage inside imported modules. (The become dicts not modules - that's why this syntax works too)
- fixed ```PyObject_GetAttr``` with unicode attribute name
=> Add PyErr_GetExcInfo, make __builtins__ more similar to cpython and id() output more useful

src/codegen/ast_interpreter.cpp, src/codegen/codegen.h, src/codegen/entry.cpp, src/codegen/irgen.cpp, src/codegen/irgen/irgenerator.cpp, src/codegen/irgen/irgenerator.h, src/codegen/parser.cpp, src/codegen/unwinding.cpp, src/core/options.h, src/core/threading.cpp, src/runtime/stacktrace.cpp, src/runtime/traceback.cpp, tools/process_stackdump.py
Super simple and not very reliable, but can give some decent high-level insight into what's going on.  Specifically, it assigns all the time to the *next* python statement, which makes it a bit hard to interpret (fixing this probably involves figuring out how to handle signals for real).  I wrote a little script to collate the results with different levels of granularity, and interestingly the file-level granularity seems pretty useful.
For example, here's some of the output for django-template:
```
Hiding 117 entries that occurred 392 (12.8%) times
Occurs 81 (2.6%) times:
minibenchmarks/../test/integration/django/django/template/defaulttags.py
Occurs 88 (2.9%) times:
minibenchmarks/../test/integration/django/django/template/smartif.py
Occurs 122 (4.0%) times: …
```
=> Python-level sampling profiler

src/capi/typeobject.cpp, src/capi/typeobject.h, src/capi/types.h
found this while adding more timers and figured it was small enough to just fix instead of creating a trello card for it.
turns out we're converting from const char* to std::string (including the malloc/free) for num_slots * num_typeNew_calls.
=> use llvm::StringRef instead of std::string typeNew

CMakeLists.txt, Makefile, libunwind_patches/9999-is-patched-marker.patch, src/CMakeLists.txt
First, that we would only apply our patchset once.  If we ever revert the
patches (I'm not sure under what conditions that happens), we previously would
never apply them again.  Attempted to fix this by adding a special patch that
adds a new file that CMake looks for; if the file doesn't exist, cmake runs the
patches again.
Second, that we didn't rebuild libunwind if we apply new patches.
I'm not sure if there's a good general solution to this, but I was able
to figure out how to force libunwind to rebuild if we need to rerun the
patch command.  It took some hacking since CMake doesn't track dependencies
on external projects, so we have to add some custom dependencies.
=> Fix some issues with the way we build libunwind

src/runtime/builtin_modules/builtins.cpp
getattr throws an exception if the attribute is not present.  getattrFunc already throws the same exception (if there isn't a default value passed in).
For some reason Terminal.app has decided to not let me select text, but the result of this change for django-template.py is:
```
pyston django-template.py        : 8.0s baseline: 10.9 (-26.5%)
```
=> for getattrFunc use getattrInternal instead of getattr

microbenchmarks/re_compile_bench.py, src/core/types.h, src/runtime/builtin_modules/builtins.cpp, src/runtime/builtin_modules/sys.cpp, src/runtime/classobj.cpp, src/runtime/float.cpp, src/runtime/inline/boxing.cpp, src/runtime/int.cpp, src/runtime/long.cpp, src/runtime/objmodel.cpp, src/runtime/set.cpp, src/runtime/str.cpp, src/runtime/types.cpp, src/runtime/types.h, tools/process_stackdump.py
Two main things were still converting to std::string:
- boxString()
- classLookup() [lookups for old-style objects]
=> Reduce string allocations

libunwind_patches/0003-use-a-sorted-array-for-registered-objects-and-do-a-b.patch, src/capi/object.cpp, src/capi/typeobject.cpp, src/capi/typeobject.h, src/capi/types.h, src/runtime/builtin_modules/builtins.cpp, src/runtime/capi.cpp, src/runtime/int.cpp, src/runtime/long.cpp, src/runtime/objmodel.cpp, src/runtime/str.cpp, src/runtime/tuple.cpp, src/runtime/types.cpp, test/tests/comparisons.py
```
pyston django_migrate.py                  :    2.1s baseline: 2.2 (-0.5%)
pyston virtualenv_bench.py                :    5.7s baseline: 5.7 (-0.1%)
pyston django-template.py                 :   10.8s baseline: 11.1 (-2.4%)
pyston interp2.py                         :    5.1s baseline: 5.2 (-3.2%)
pyston raytrace.py                        :    6.3s baseline: 6.3 (-1.1%)
pyston nbody.py                           :    8.6s baseline: 8.3 (+3.8%)
pyston fannkuch.py                        :    7.3s baseline: 7.2 (+2.0%)
pyston chaos.py                           :   18.9s baseline: 20.0 (-5.6%)
pyston fasta.py                           :    5.3s baseline: 5.2 (+0.6%)
pyston pidigits.py                        :    5.6s baseline: 5.6 (+0.3%)
pyston richards.py                        :    2.4s …
```
=> tp_richcompare

src/runtime/classobj.cpp
So in #254  all binary operations can be implemented by the newly added function ``_instanceBinary``. Do you think this is the right way to do it? If so I will go ahead and add more code that implement other functions other than ``__eq__`` and  ``__ne__``.
=> Remove redundant code and pave way for #254

src/runtime/generator.cpp, test/tests/generators.py
Unconditionally raise a StopIteration when trying to iterate
a finished generator, regardless of what originally stopped
it from iterating.
=> Slightly change generator StopIteration handling

test/tests/weakref4.py
Make multiple copies of all of the objects we expect to get
collected, and just assert than any of them get collected.
=> Try to make weakref4 less flaky

src/codegen/parser.cpp, test/integration/virtualenv_test.py
We were doing this for the main packages, but we would get different
versions of their dependencies dependending on what the latest version
was.
Also, add some extra debugging output in the parser in case that
issue crops up again.
=> Specify all package versions in virtualenv_test

src/runtime/ics.cpp, src/runtime/ics.h
otherwise valgrind segfaults when we call into the ic.
also mmap the eh_frame to (hopefully) be nearby the ic, so the offset fits.
=> allocate runtime ics using mmap (with PROT_EXEC)

from_cpython/Include/Python.h, from_cpython/Lib/test/test_binop.py, src/capi/abstract.cpp, src/codegen/ast_interpreter.cpp, src/codegen/codegen.cpp, src/codegen/irgen/future.cpp, src/codegen/irgen/future.h, src/codegen/irgen/hooks.cpp, src/codegen/irgen/hooks.h, src/codegen/irgen/irgenerator.cpp, src/codegen/unwinding.h, src/core/cfg.cpp, src/core/types.h, src/runtime/builtin_modules/ast.cpp, src/runtime/builtin_modules/builtins.cpp, src/runtime/code.cpp, src/runtime/cxx_unwind.cpp, src/runtime/dict.cpp, src/runtime/frame.cpp, src/runtime/import.cpp, src/runtime/int.cpp, src/runtime/stacktrace.cpp, src/runtime/types.cpp, test/tests/compile_future.py, test/tests/compile_future2.py, test/tests/exec_future_import.py, test/tests/exec_future_import2.py, test/unittests/analysis.cpp
- Move `FutureFlags` from `BoxedModule` to `SourceInfo`.
- Handle `__future__` imports in exec statements.
- Handle the `division` import in cfg gen rather than later.
(This was prompted by a cpython test case that uses `from __future__ import division` in an exec statement.)
Seems like there is still a lot of cleaning up to do, but this is a step in the right direction. Notably, we have our own constants for the future imports, even though they're defined in cpython too.
=> Some `__future__` import stuff

src/runtime/types.cpp, src/runtime/types.h
CPython has this optimization as well, and it should
save us an average of 7 bytes per string.
=> Use the padding bytes at the end of BoxedString

.travis.yml, test/extra/cheetah_test.py, test/extra/mysqldb_0001-Pyston-change-register-types.patch, test/extra/mysqldb_test.py, test/extra/protobuf_test.py, test/extra/pyicu_101.patch, test/extra/pyicu_test.py, test/extra/test_helper.py
This are still a few left but they other fail currently.
Cheetah produces currently quite a lot of error because of a ```is``` comparison which fails.
(see: https://bitbucket.org/pypy/compatibility/wiki/cheetah)
=> Add more external projects to our travis-ci test suite

src/analysis/type_analysis.cpp, src/codegen/irgen/hooks.cpp, src/runtime/objmodel.cpp, test/tests/deopt_generator_tests.py, test/tests/deopt_namescope_tests.py, test/tests/deopt_tests.py
Unfortunately our type speculation strategy has bit-rot
over time, to the point that it's not super helpful.
Deopt (the flip side of the speculation) also has some bugs
in it which I was starting to trigger, so just disable the
whole thing for now.
Turning it off should just be a temporary measure and I'll
look soon into what we need to do to get it back on.
This had a minor but (surprisingly) somewhat positive effect on perf:
```
django_template.py            8.0s (12)            8.0s (18)  -0.9%
pyxl_bench.py            5.5s (12)            5.6s (18)  +1.4%
sqlalchemy_imperative.py            2.6s (28)            2.6s (26)  -0.8%
django_migrate.py            2.0s (12)            2.0s (10)  -0.5%
virtualenv_bench.py            8.5s (12)            8.4s (10)  -0.8%
```
richards.py also …
=> Temporarily disable type speculation

microbenchmarks/str_find_ubench.py, src/runtime/inline/boxing.cpp, src/runtime/str.cpp, src/runtime/types.cpp, src/runtime/types.h
Seems like a no-brainer, but the perf results are less convincing than I would have liked:
```
django_template.py             8.1s (6)             8.1s (6)  +0.4%
pyxl_bench.py             5.7s (4)             5.6s (4)  -1.8%
sqlalchemy_imperative.py             2.7s (4)             2.7s (4)  -0.4%
django_migrate.py            2.1s (12)            2.1s (13)  +1.0%
virtualenv_bench.py             8.5s (8)             8.5s (4)  +0.1%
```
=> cache + reuse 1-length strings

microbenchmarks/sre_optimize_unicode.py, microbenchmarks/tuple_ubench.py, src/runtime/tuple.cpp, test/tests/sre_compile_test.py
Before we would do this using `pyElements()`, which has some nice special-casing for lists, but I guess the overhead from that is still so much higher than iterating over a C array.  Or I guess in this case, it's just memcopying a region of memory so it's hard to beat.
=> Optimize creating tuples from lists

.travis.yml, CMakeLists.txt, Makefile
* add cmake option ENABLE_EXTRA_TESTS for tests that should only run on travis-ci
* change `make check` and `make quick_check` testing to use ctest
* this removes duplication, matches local testing to travis-ci, and provides a nice test summary
The exact `make check` and ctest test options have drifted a bit. This might be a good time to verify exactly what you want the testing to be.
=> cmake testing

src/asm_writing/assembler.cpp, src/asm_writing/assembler.h, src/asm_writing/rewriter.cpp, src/asm_writing/rewriter.h, src/asm_writing/types.h
This is based off of @undingen 's https://github.com/dropbox/pyston/pull/310 which optimized constant loading in the rewriter. It never got merged and the discussion there was never followed up on (until now).
Basically this is just @undingen 's patch plus some commits that
- remove the constant tracking and invalidation code
- instead, use the existing location tracking mechanism
This involves creating a RewriterVar in some cases where we previously took a constant as an argument without creating a RewriterVar.
Right now I just want to see if travis-ci passes, but I'd also like to run measurements and check that the assembly is what I expect it to be and so on.
=> constant loading optimizations in rewriter

Makefile, src/codegen/ast_interpreter.cpp, src/gc/heap.cpp, src/gc/heap.h, src/runtime/inline/boxing.cpp, src/runtime/int.h, src/runtime/types.h
Mostly related to making sure that some hot paths get
inlined better, particularly for allocation/sweeping.
These changes make a simple for-loop benchmark (which
is just dependent on allocation speed) about 25% faster.
Overall perf doesn't change that much, but the for loop case was bothering me :P
```
django_template.py             8.1s (2)             8.0s (2)  -0.5%
pyxl_bench.py             5.2s (2)             5.2s (2)  +0.1%
sqlalchemy_imperative.py             2.7s (2)             2.6s (2)  -0.9%
django_migrate.py             2.1s (2)             2.1s (2)  -0.3%
virtualenv_bench.py             8.4s (2)             8.3s (2)  -0.5%
geomean                 4.6s                 4.5s  -0.4%
```
=> Some small micro-optimizations

Makefile, src/capi/typeobject.cpp, src/runtime/super.cpp
Surprised that it even shows up at all:
```
django_template.py             6.5s (2)             6.4s (2)  -0.9%
pyxl_bench.py             4.8s (2)             4.6s (2)  -4.5%
sqlalchemy_imperative.py             2.4s (2)             2.3s (2)  -0.4%
django_migrate.py             2.0s (2)             2.0s (2)  -1.7%
virtualenv_bench.py             8.3s (2)             8.2s (2)  -0.5%
geomean                 4.2s                 4.1s  -1.6%
```
=> Switch super to tp_getattro

src/codegen/unwinding.cpp, src/codegen/unwinding.h, src/runtime/stacktrace.cpp, src/runtime/traceback.cpp, src/runtime/traceback.h, test/tests/native_print_tb.py, tools/tester.py
some parts of the code were using uninitialized BoxedTraceback instances as the end of the traceback chain, which is always wrong.  This was handled by our traceback.py, but `printTraceback()` wasn't checking to see if `has_line` was true before printing out `"",-1`.
The fix is to always use None for this sentinel value, and remove the option of allocating an uninitialized BoxedTraceback object.
=> Use None as traceback sentinel

src/asm_writing/icinfo.h, src/asm_writing/rewriter.cpp, src/asm_writing/rewriter.h, src/codegen/ast_interpreter.cpp, src/codegen/entry.cpp, src/codegen/parser.cpp, src/core/stats.cpp, src/core/stats.h, src/core/threading.cpp, src/gc/collector.cpp, src/gc/collector.h, src/gc/gc_alloc.h, src/runtime/generator.cpp, src/runtime/ics.h, src/runtime/iterators.cpp, src/runtime/objmodel.cpp, tools/tester.py
This was one of the main source of missed runtimeCall/callattr rewrites.  I think we still can do better by not hitting the wrapper in the first place.
A few other misc things in the pr:
- some more messing around with the stat timers
- some more GC debugging helpers + fix a pre-existing gc issue
```
django_template.py             6.4s (2)             6.0s (2)  -4.9%
pyxl_bench.py             4.2s (2)             4.2s (2)  -1.1%
sqlalchemy_imperative.py             2.4s (2)             2.3s (2)  -2.2%
django_migrate.py             2.1s (2)             2.0s (2)  -4.2%
virtualenv_bench.py             8.2s (2)             8.1s (2)  -1.7%
geomean                 4.1s                 3.9s  -2.9%
```
I'm not super happy only getting a few percent at a time, but I think the stat timers are …
=> rewrite wrapperdescriptors

from_cpython/Include/stringobject.h, src/capi/codecs.cpp, src/runtime/str.cpp
Was running pyston at higher collection frequencies and ran into these issues.  After these fixes it looks like we can pass the integration tests when doing 100x collections, except for virtualenv_test.py which runs into the issue @rudi-c was running into (if we free a class in the same collection as some of its objects).
=> fix two minor bugs

src/gc/heap.cpp, src/gc/heap.h
linux clusters page faults so the larger the regions we mmap the better, and larger regions don't cost us anything.
On jitdev, `/proc/sys/vm/page-cluster` contains '3', which means the kernel tries to read-ahead 8 (2^3) pages whenever there's a page fault.  For the small arena, we were only mmaping 16k at a time, so we would have twice the number of page faults for the small arena.  Instead of just upping it from 16k to 32k, I made the mappings much larger initially (e.g. 64 megs for the small arena), and the increments by which they grow also much larger (16megs for small arena.)
We don't really pay anything for doing this, since it's just a vm reservation, so there's no reason *not* to save the syscalls.
```
06a07a2c6f0a19fdbb:  cdfbb8ee6b7ce5f185:
django_template.py             6.1s …
```
=> don't mmap such small regions

src/asm_writing/icinfo.cpp, src/asm_writing/rewriter.h, src/runtime/objmodel.cpp, test/tests/weakref1.py, test/tests/weakref_proxy.py
Mostly related to callsites.  django_template hits an interesting case where we can't rewrite callsites that always throw exceptions.
```
django_template.py             6.0s (2)             6.0s (2)  -1.1%
pyxl_bench.py             4.2s (2)             4.1s (2)  -2.2%
sqlalchemy_imperative.py             2.3s (2)             2.3s (2)  -1.6%
django_migrate.py             2.0s (2)             2.0s (2)  -2.1%
virtualenv_bench.py             8.1s (2)             8.1s (2)  +0.1%
geomean                 4.0s                 3.9s  -1.4%
```
=> more rewriting

src/core/stats.cpp, src/core/util.cpp, src/core/util.h, src/jit.cpp
Also removing logic in Stats::dump that counts the total number of ticks
in timers. It relies on specific timer naming conventions that aren't
currently being followed. If, at a later time, we are interested in
having the sum of timer ticks, we should refactor the code to have a
separate class for counters that log time.
=> Revert to using gettimeofday to have measurements in us instead of ticks.

Makefile
Specify /bin/bash for the Makefile, as some distros may have other shells (eg, ubuntu image for docker has /bin/sh pointing to /bin/dash).
This causes failures when bash extensions are used (in my case, the time command cannot run)
=> Specify /bin/bash for the Makefile, as some distros may have other shells as /bin/sh

src/core/stats.cpp, src/core/util.cpp, src/core/util.h, src/jit.cpp
aka `Revert "Revert to using gettimeofday to have measurements in us instead of ticks."`
changing back to us resulted in a decent perf hit.  I tried converting some of the hotter timers back to ticks, but it seems better for now just to have them all in ticks since we were already dealing with that.  I think there are a couple broken features right now (ex min_us), but maybe we should just deal with those directly.
=> change timers back to ticks

libunwind_patches/0003-use-a-sorted-array-for-registered-objects-and-do-a-b.patch
Don't think this is currently showing up much, but if we start to use more runtime ICs (e.g. new JIT tier) this shows up as a serious bottleneck (and with this change it disappears from the top perf output).
Instead of making a patch for the patch I directly changed the libunwind patch...
Implementation is inspired by ```std::lower_bound``` http://en.cppreference.com/w/cpp/algorithm/lower_bound
=> _U_dyn_register: Use binary search to find insert location

test/extra/cheetah_test.py, test/extra/mysqldb_test.py, test/extra/protobuf_test.py, test/extra/pyicu_test.py, test/extra/test_helper.py
I'm seeing fewer failures locally than specified in the file, and
I'm guessing it's because I'm somehow skipping some tests, but I'm
not sure.
=> Include total-tests-run in our test-suite-results checking

minibenchmarks/sqlalchemy_declarative.py, minibenchmarks/sqlalchemy_imperative.py
this increases cpython time on _imperative.py to ~2 seconds (and lowers pyston's % from ~480% to ~380%).
the declarative benchmark takes 10 seconds for cpython with this change, but it doesn't work on pyston at all yet.
the imperative case shows this at the top of `perf report`:
```
-   7.59%  pyston_release  pyston               [.] llvm::StringMapImpl::FindKey(llvm::StringRef) const           
- llvm::StringMapImpl::FindKey(llvm::StringRef) const                                                          
- 49.37% pyston::getattrInternalGeneric(pyston::Box*, llvm::StringRef, pyston::GetattrRewriteArgs*, bool, bo
- 41.03% getattr                                                                                         
- 21.88% PyObject_GetAttr …
```
=> do 100 queries per insert instead of 1000 after all inserts.

test/extra/cheetah_test.py
cheetah's tests do a PATH search for the "cheetah" executable,
and since we were appending the test-cheetah's location to PATH,
it would find the system cheetah preferentially to the test cheetah.
This is fine since on most systems there isn't a system cheetah, but
somehow mine has one.  The system cheetah will invoke the system python,
which will end up passing more of the tests.
We could prepend PATH instead of append to it, but it looks like the
the tests don't need anything else, so for now don't pass in anything else
in PATH.
=> Don't have cheetah_test look for system cheetah

src/gc/collector.cpp, src/gc/heap.cpp, src/gc/heap.h, test/tests/class_freeing_with_instances.py
Was running into it, so just added a quick fix that should hopefully
get us through until rudi gets in his real fix.
This commit just delays freeing the class objects until the end of the
sweep.  It doesn't deal with a number of corner cases such as if
a class and a metaclass get freed at the same time (they both get delayed
to the same point), or if we free a class with weakrefs to it (it just
gets treated like a normal weakreferent).
=> Temporary fix for freeing-classes-before-instances bug

from_cpython/Include/object.h, src/asm_writing/rewriter.cpp, src/asm_writing/rewriter.h, src/codegen/ast_interpreter.cpp, src/codegen/compvars.cpp, src/codegen/irgen/hooks.cpp, src/core/cfg.cpp, src/core/types.h, src/runtime/code.cpp, src/runtime/descr.cpp, src/runtime/generator.cpp, src/runtime/objmodel.cpp, src/runtime/objmodel.h, src/runtime/rewrite_args.h, src/runtime/types.cpp, src/runtime/types.h, test/extra/test_helper.py
Previously, we would call non-functions by doing something like `getattr(func_like_obj, '__call__')()`, ie doing an attribute lookup and then another round of figuring out how to call the object.  Now instead, we have class-level function pointers that we can set that will bypass this extra overhead.
This is "tpp_call" and not CPython's tp_call, since it uses our internal rewriter-capable interface.
There's some more cleanup that can be done; we have a similar mechanism on functions ("internal callable") which is much less useful with this new strategy.  Most of the internal callables are on classes '__call__` functions, and they should probably just be converted to tpp_call pointers.  I did this for typeCall, though it ended up being pretty messy.
The bulk of the changes in this PR are …
=> add tpp_call for faster calling of non-functions

microbenchmarks/itertools_chain_bench.py, microbenchmarks/loop.py, microbenchmarks/unicode_ctor_bench.py, src/asm_writing/rewriter.cpp, src/capi/typeobject.cpp, src/capi/typeobject.h, src/capi/types.h, src/core/types.h, src/runtime/builtin_modules/builtins.cpp, src/runtime/capi.cpp, src/runtime/descr.cpp, src/runtime/ics.h, src/runtime/iterators.cpp, src/runtime/iterobject.cpp, src/runtime/list.cpp, src/runtime/objmodel.cpp, src/runtime/stacktrace.cpp, src/runtime/types.cpp
ie try to call c slots when they were requested.  this PR does that for tp_iternext, and somewhat for tp_new/tp_init.
```
django_template.py             5.3s (2)             5.2s (2)  -1.3%
pyxl_bench.py             4.0s (4)             4.1s (4)  +1.7%
sqlalchemy_imperative2.py             6.7s (2)             5.6s (2)  -16.3%
django_migrate.py             1.9s (4)             1.9s (4)  -0.6%
virtualenv_bench.py             8.1s (2)             8.0s (2)  -0.3%
geomean                 4.7s                 4.5s  -3.6%
```
=> reduce api conversions

src/codegen/ast_interpreter.cpp, src/codegen/compvars.cpp, src/codegen/compvars.h, src/codegen/irgen/irgenerator.cpp, src/codegen/runtime_hooks.cpp, src/core/types.h, src/runtime/builtin_modules/builtins.cpp, src/runtime/builtin_modules/sys.cpp, src/runtime/classobj.cpp, src/runtime/dict.cpp, src/runtime/float.cpp, src/runtime/ics.h, src/runtime/import.cpp, src/runtime/int.cpp, src/runtime/iterobject.cpp, src/runtime/long.cpp, src/runtime/objmodel.cpp, src/runtime/objmodel.h, src/runtime/types.cpp
in order to save one register.
This makes it possible to pass up to 3 args to a runtimc IC callattr
(Runtime ICs currently don't support passing args on the stack)
Wouldn't have started if I would have known that I have to change so many calls for such a small improvement.
=> callattr: Embed the ArgPassSpec arg into the CallattrFlags struct

Makefile, src/codegen/unwinding.cpp, src/core/types.h, src/gc/collector.cpp, src/gc/heap.cpp, src/gc/heap.h
split this out of #660.
we build a sorted cache from our large and huge arenas before collections, to speed up all the `::allocationFrom` calls that are coming.
```
django_template.py             4.7s (2)             4.6s (2)  -3.0%
pyxl_bench.py             3.9s (2)             3.8s (2)  -2.0%
sqlalchemy_imperative2.py             5.1s (2)             5.0s (2)  -1.7%
django_migrate.py             1.8s (2)             1.8s (2)  -1.7%
virtualenv_bench.py             7.8s (2)             7.7s (2)  -1.8%
geomean                 4.2s                 4.1s  -2.1%
```
=> Binary search large and huge arenas for ::allocationFrom

src/asm_writing/assembler.cpp, src/asm_writing/assembler.h, src/asm_writing/icinfo.cpp, src/asm_writing/icinfo.h, src/asm_writing/rewriter.cpp, src/asm_writing/rewriter.h
The incl, decl, and call can use the smaller instructions sometimes instead of loading large constants.
I also now allocate the slot before emitting assembly, to make it easier to emit assembly which depends on its address. (This was an easy change to make, since we emit all the assembly in the commit, anyway.)
Average IC size goes down from 143 bytes to 130 bytes. 
```
django_template.py            5.1s (14)             5.1s (4)  -0.8%
pyxl_bench.py            4.2s (14)             4.1s (4)  -2.4%
sqlalchemy_imperative.py            2.1s (14)             2.1s (4)  -0.4%
django_migrate.py            1.9s (14)             1.9s (4)  -1.1%
virtualenv_bench.py            8.3s (14)             8.3s (4)  -0.1%
geomean                 3.7s                 3.7s  -0.9%
```
=> Use less large constants

src/asm_writing/assembler.cpp, src/asm_writing/assembler.h, src/asm_writing/types.h
makes the encoding 4-5byte shorter and works because the upper 32bit will get auto cleared
This is quite common in code generated by the new JIT
=> assembler: Use 32bit moves if the immediate fits inside 32bit

src/runtime/classobj.cpp, test/tests/oldstyle_classes.py
The first contribution target [#245](https://github.com/dropbox/pyston/issues/254). Add lt/le/gt/ge to old-style class. Pass the tests and format check.
=> For issue #254, add lt, le, gt, ge to old-style class

from_cpython/Include/stringobject.h, from_cpython/Objects/unicodeobject.c, microbenchmarks/re_finditer_bench.py, microbenchmarks/unicode_split_ubench.py, src/codegen/entry.cpp, src/runtime/str.cpp, src/runtime/types.cpp
Mostly, inline things into _PyUnicode_New to reduce its overhead.
Also, sneak in a change to reenable PyString_GET_SIZE.
Overall effect:
```
django_template.py             4.7s (2)             4.6s (2)  -2.1%
pyxl_bench.py             4.0s (2)             4.0s (2)  -0.4%
sqlalchemy_imperative2.py             5.3s (2)             5.3s (2)  -1.1%
django_migrate.py             2.0s (2)             2.0s (2)  -2.0%
virtualenv_bench.py             5.3s (2)             5.3s (2)  -0.4%
geomean                 4.0s                 4.0s  -1.2%
```
=> Unicode-creation optimizations

src/codegen/unwinding.cpp
I think the ip we receive is the return address to that stack frame
(at least in the non-signal case).  This makes things a bit weird
since the "is this ip in this range" tests have a different half-openness
than they normally do.  At some point an "ip = ip - 1" snuck in, which
I think was to address this issue, but I think it's better to not
change the ip -- ie the resulting address is not independently useful (it's
in the middle of an instruction); we could pass it around as "ip_minus_one",
but instead just try converting the tests to be better.
=> Be more consistent about "ip" while unwinding

section_ordering.txt, src/capi/typeobject.cpp, src/capi/typeobject.h, src/codegen/baseline_jit.cpp, src/codegen/irgen/irgenerator.cpp, src/runtime/inline/boxing.h, src/runtime/inline/link_forcer.cpp, src/runtime/objmodel.cpp, src/runtime/types.h
Mostly around optimizing unicode handling.  The gains are pretty small so I tried again to mess around with section_ordering.txt.
```
django_template.py             4.5s (2)             4.2s (2)  -5.8%
pyxl_bench.py             3.9s (4)             3.9s (2)  -0.6%
sqlalchemy_imperative2.py             5.2s (2)             5.1s (2)  -1.2%
django_migrate.py             1.9s (2)             1.9s (2)  +0.0%
virtualenv_bench.py             5.2s (2)             5.1s (2)  -1.3%
geomean                 3.9s                 3.8s  -1.8%
```
=> More small improvements

src/core/common.h, src/runtime/objmodel.cpp, src/runtime/types.cpp
#define SOMETHING_OFFSET -> offsetof(...)
Generates the same assembly, more standard and less `#define`s
=> Refactor offset macros to use the C++ built-in instead.

src/runtime/types.h, test/tests/instance_methods.py
We would try to statically-resolve their getattrs, but there's some
special casing in the getattr logic for them.  Which should be handled
by moving the special-case to a proper tp_getattr, but for now just
add the special-casing to "hasGenericGetattr" as well.
=> Fix irgen bug for instancemethods

src/codegen/ast_interpreter.cpp
GC allocating the huge number of large ASTInterpreter instances is slow,
instead add a small wrapper object which gets GC allocated and notifies the ASTInterpreter.
```
pyston django_template.py                 :    3.8s base_3: 3.9 (-2.5%)
pyston pyxl_bench.py                      :    3.5s base_3: 3.6 (-2.4%)
pyston sqlalchemy_imperative2.py          :    4.7s base_3: 4.8 (-2.5%)
pyston django_migrate.py                  :    1.7s base_3: 1.8 (-3.6%)
pyston virtualenv_bench.py                :    4.9s base_3: 4.9 (-0.4%)
```
=> interpreter: Don't GC allocate ASTInterpreter instances.

src/asm_writing/assembler.h, src/asm_writing/disassemble.cpp, src/asm_writing/disassemble.h, src/asm_writing/rewriter.h, src/codegen/ast_interpreter.cpp
reduces the number of calls to malloc from the biggest users (mostly ASTInterpreter + Rewriter).
```
0915db4ee1808a2c5b:  3501184a72c8b867da:
django_template.py             3.9s (2)             3.8s (2)  -2.7%
pyxl_bench.py             3.7s (2)             3.7s (2)  -0.1%
sqlalchemy_imperative2.py             4.6s (2)             4.5s (2)  -1.9%
django_migrate.py             1.7s (2)             1.6s (2)  -7.1%
virtualenv_bench.py             4.9s (2)             4.9s (2)  -1.5%
geomean                 3.5s                 3.4s  -2.7%
```
=> Fewer mallocs

src/runtime/objmodel.cpp
the type casts we were using were causing bad things to happen with gcc builds (still not exactly sure
why they aren't in clang builds), since we were casting from a function which expects arguments on the stack to a function type that doesn't.
this manifests itself as rewrite_args changing from NULL to a small heap pointer on this line:
```
objmodel.cpp:4108    contained = callattrInternal1(rhs, contains_str, CLASS_ONLY, NULL, ArgPassSpec(1), lhs);
```
that is, the local variable rewrite_args is NULL before the call, and non-NULL after.  The actual line that causes the pointer overwrite is in `bindObjIntoArgs`:
```
objmodel.cpp:3043    arg1 = bind_obj;
```
so I'm guessing that since we didn't push things onto the stack before the call to `callattrInternal`, we end up trampling over …
=> use inline functions instead of casting function pointers

src/asm_writing/rewriter.h, src/runtime/objmodel.cpp, src/runtime/rewrite_args.h
We were doing some unnecessary guards, like guarding the types of constant objects. Fixing this saves about 10 bytes on average per IC, and has a comparable small improvement in performance:
```
django_template.py             5.1s (6)             5.1s (8)  -1.6%
pyxl_bench.py             4.2s (6)             4.1s (6)  -2.4%
sqlalchemy_imperative.py             2.1s (6)             2.0s (6)  -2.5%
django_migrate.py             2.0s (6)             1.9s (6)  -1.9%
virtualenv_bench.py             8.4s (6)             8.3s (6)  -0.5%
geomean                 3.8s                 3.7s  -1.8%
```
=> Don't guard types sometimes

src/asm_writing/assembler.cpp, src/asm_writing/assembler.h, src/asm_writing/rewriter.cpp, src/asm_writing/rewriter.h, src/codegen/baseline_jit.cpp, src/codegen/baseline_jit.h, src/runtime/ics.h, src/runtime/types.cpp
In order to speedup baseline JITed code directly emit patchpoints.
- reduces number of calls
- reduces number of EH frames
- supports stack args (currently hard coded to 8args)
- maybe slightly faster unwinding because of of reduced call nesting  
I choose to directly add the stack args support to the baseline jit instead of the rewriter because I think to get this right for all cases is harder and in the baseline jit I have special knowledge about the stack layout which makes it easier.
```
pyston django_template.py                 :    3.7s base_3: 3.9 (-4.0%)
pyston pyxl_bench.py                      :    3.4s base_3: 3.6 (-6.0%)
pyston sqlalchemy_imperative2.py          :    4.6s base_3: 4.7 (-2.0%)
pyston django_migrate.py                  :    1.7s base_3: 1.7 (-0.8%)
```
=> baseline jit: directly emit patchpoints instead of using runtime ICs

src/gc/collector.cpp
sorry about that - for some reason I had it in my head that travis-ci still did quick_check against pyston_dbg
=> fix null check

from_cpython/Modules/_sre.c, src/capi/abstract.cpp, src/capi/typeobject.cpp, src/codegen/ast_interpreter.cpp, src/codegen/baseline_jit.cpp, src/codegen/runtime_hooks.cpp, src/gc/heap.cpp, src/gc/heap.h, src/runtime/builtin_modules/builtins.cpp, src/runtime/builtin_modules/sys.cpp, src/runtime/dict.cpp, src/runtime/import.cpp, src/runtime/inline/link_forcer.cpp, src/runtime/inline/list.cpp, src/runtime/inline/list.h, src/runtime/list.cpp, src/runtime/str.cpp, src/runtime/traceback.cpp, src/runtime/types.cpp, src/runtime/types.h
I think these are good changes, but the perf results are exactly the same as my non-perf-related PR:
```
django_template.py             3.6s (2)             3.6s (2)  -0.2%
pyxl_bench.py             3.5s (2)             3.4s (2)  -1.2%
sqlalchemy_imperative2.py             4.3s (2)             4.4s (2)  +0.4%
geomean                 3.8s                 3.8s  -0.4%
```
It speeds up some simple regex microbenchmarks by 4x though.
=> optimize regex handling

src/codegen/compvars.cpp, src/codegen/compvars.h, src/codegen/irgen/irgenerator.cpp, src/codegen/irgen/util.cpp, src/runtime/tuple.cpp, test/tests/tuples.py
Not super common, but can seems to help since we are particularly bad at handling `a in (b, c)`.
```
django_template.py             3.6s (2)             3.6s (2)  -0.5%
pyxl_bench.py             3.5s (2)             3.5s (2)  -0.4%
sqlalchemy_imperative2.py             4.3s (2)             4.3s (2)  -0.9%
geomean                 3.8s                 3.8s  -0.6%
```
=> Convert "a in (b, c)" to "a == b or a == c"

from_cpython/Include/Python.h, from_cpython/Include/object.h, from_cpython/Modules/_sre.c, from_cpython/Modules/itertoolsmodule.c, from_cpython/Objects/weakrefobject.c, src/capi/typeobject.cpp, src/codegen/ast_interpreter.cpp, src/gc/heap.cpp, src/runtime/file.cpp, src/runtime/frame.cpp, src/runtime/generator.cpp, src/runtime/objmodel.cpp, src/runtime/objmodel.h, src/runtime/types.cpp, src/runtime/types.h
Mostly moving simple_destructor functions into tp_dealloc instead of their own field. Replace the field with a boolean to indicate whether the tp_dealloc has the safety properties of a simple_destructor. Assign simple_destructor to more builtin types.
Depends on gcfinalizers2 PR.
=> Preparation for finalizer code, refactoring some simple_destructor logic.

from_cpython/Include/methodobject.h, from_cpython/Objects/stringobject.c, from_cpython/Objects/unicodeobject.c, microbenchmarks/django_parsing.py, src/runtime/descr.cpp, src/runtime/str.cpp, src/runtime/types.cpp
by introducing some new calling conventions that we are able to jit to.  helps those functions a lot but maybe this isn't a huge deal overall (or maybe I need to add it to more places):
```
django_template.py             3.6s (2)             3.6s (2)  -0.4%
pyxl_bench.py             3.4s (2)             3.4s (2)  +0.1%
sqlalchemy_imperative2.py             4.3s (2)             4.3s (2)  +0.5%
django_lexing.py             1.8s (2)             1.7s (2)  -6.4%
```
=> speed calling of (some) capi code

from_cpython/Include/listobject.h, src/runtime/inline/list.cpp, src/runtime/list.cpp, src/runtime/types.h
Our list object format was pretty close to CPython's -- we had two fields flipped, and I guess some extra padding from an empty structure.  Fixing that allows C API code to use the PyList macros for direct field access, which can significantly speed up list-heavy benchmarks.  which apparently none of ours are:
```
django_template.py             3.6s (2)             3.7s (2)  +0.6%
pyxl_bench.py             3.4s (2)             3.4s (4)  +0.2%
sqlalchemy_imperative2.py             4.3s (2)             4.3s (2)  -0.6%
geomean                 3.8s                 3.8s  +0.1%
```
So no win, but I think it's an improvement so I'm going to merge it in.
=> reenable PyList macros

src/asm_writing/rewriter.cpp, src/asm_writing/rewriter.h, src/codegen/baseline_jit.cpp
This patch makes scratch space allocated with ```Rewriter::allocate``` available when the ```RewriterVar``` becomes unused.
I'm not really happy about this patch, I couldn't add the release logic into ```bumpUse``` because it get's called to early (the scratch space will get used afterwards but we could spill vars in between which would overwrite the argument)
@tjhance any ideas?
It looks like we run only rarely out of scratch space and in non of our important benchmarks.
=> rewriter: release allocated scratch space

src/core/ast.cpp, src/runtime/types.cpp, src/runtime/types.h, test/tests/float.py
We were using a C 'double' as the hashmap key, which meant
that 0.0 and -0.0 would end up caching to the same thing.
Instead, extract the bits of the double, and use that as the
cache key instead.
Should fix #724
=> Cache floats based on their bits, not their value

CONTRIBUTING.md, README.md, docs/TIPS.md, src/capi/typeobject.h, src/codegen/ast_interpreter.cpp, src/core/types.h, src/runtime/classobj.h, src/runtime/types.h, test/CPYTHON_TEST_NOTES.md, test/cpython/NOTES.org
The changes are mainly doc changes, so they are easier to read from my fork https://github.com/rudi-c/pyston than the diff itself.
Mostly of the changes are in `CONTRIBUTING.md` and `docs/TIPS.md`
=> Add docs and tips for new contributors

test/integration/Cython_0001-Pyston-change-we-don-t-support-custom-traceback-entr.patch, test/integration/numpy_test.py
Since we're not able to install NumPy yet, I just added `skip-if: True` and a comment saying that the script expects to find `NumPy` at the same directory level as `pyston` (to avoid having yet another submodule to clone).
This uses @undingen's patch for CPython.
=> Add integration test for installing NumPy

src/codegen/parser.cpp
Flipped conditional meant that we were never caching the parse results :(
perf results are pretty nice!
```
django_template2.py             7.1s (2)             5.3s (2)  -25.3%
pyxl_bench.py             3.7s (2)             3.4s (2)  -8.5%
sqlalchemy_imperative2.py             5.3s (2)             4.2s (2)  -21.2%
geomean                 5.2s                 4.2s  -18.6%
```
(only because the bug caused an equal regression earlier...)
=> Fix parsing caching

src/codegen/ast_interpreter.cpp, src/codegen/irgen/hooks.cpp, src/core/types.h
This function can get quite hot because now with the baseline jit we execute it much more often.
I'm not really excited about adding the ```InternedString``` fields to ```ParamNames``` but I don't know where to add them else.
```
e648044ce2266a3fc6:  b8f5647281593fc5ed:
django_template.py             3.5s (4)             3.4s (4)  -0.7%
pyxl_bench.py             3.3s (4)             3.3s (4)  -0.6%
sqlalchemy_imperative2.py             4.1s (4)             4.1s (4)  -0.7%
geomean                 3.6s                 3.6s  -0.7%
```
=> Slightly speedup ASTInterpreter::initArguments

from_cpython/Include/descrobject.h, from_cpython/Include/object.h, microbenchmarks/bm_django.py, src/capi/abstract.cpp, src/capi/typeobject.cpp, src/runtime/builtin_modules/builtins.cpp, src/runtime/inline/boxing.h, src/runtime/objmodel.cpp, src/runtime/types.h, test/tests/isinstance.py
isinstance() has to a remarkable amount of work -- check out abstract.cpp:PyObject_IsInstance if you're curious.  Add some class-level caching of whether or not the bulk of the work can get skipped.
Improves bm_django by about 8%, though the effect on the macrobenchmarks seems like a wash:
```
django_template2.py             5.2s (2)             5.2s (2)  +0.6%
pyxl_bench.py             3.4s (4)             3.4s (4)  +0.3%
sqlalchemy_imperative2.py             3.9s (2)             3.9s (2)  -0.3%
geomean                 4.1s                 4.1s  +0.2%
```
=> Improve isinstance speed

src/runtime/generator.cpp
I verified with gdb that this now really visits all entries of the return context struct
=> Fix gc visiting code for running generators

src/gc/collector.cpp
This also makes the implementation of TraceStack more correct. Though in practice we always a non-zero number of elements to the TraceStack before using it, the old TraceStack would leak memory if it was created but never used.
Addresses https://github.com/dropbox/pyston/issues/749
=> Release leftover chunk in the TraceStack.

src/codegen/ast_interpreter.cpp, src/codegen/ast_interpreter.h, src/codegen/baseline_jit.cpp
This doen't show any perf improvement at the moment, but I think it's still nice and it may improve perf after #736. 
Having to call less external functions helps register allocation.
=> bjit: inline trivial helper functions

src/codegen/entry.cpp, src/codegen/irgen.cpp
The previous set was based on trying to get the absolute
best results on microbenchmarks; go back to the small set.
We'll want to revisit this later, but for now we're not getting much benefit from these (especially with type speculation not firing), so turning them off is an easy win:
```
django_template2.py             5.2s (2)             5.1s (2)  -2.3%
pyxl_bench.py             3.4s (2)             3.3s (2)  -2.1%
sqlalchemy_imperative2.py             4.0s (2)             3.9s (2)  -1.2%
geomean                 4.1s                 4.0s  -1.9%
```
=> Reduce number of optimization passes we run

from_cpython/Include/object.h, src/capi/abstract.cpp, src/capi/typeobject.cpp, src/capi/typeobject.h, src/runtime/objmodel.cpp, src/runtime/rewrite_args.h, src/runtime/types.h, test/tests/55.py, test/tests/isinstance.py
sqlalchemy in particular likes to use it and we weren't handling it very well.
@tjhance would you mind taking a look?
```
public/master:             getattr:
django_template2.py             5.2s (2)             5.2s (2)  -0.4%
pyxl_bench.py             3.5s (2)             3.3s (2)  -4.2%
sqlalchemy_imperative2.py             4.0s (2)             3.8s (2)  -5.6%
geomean                 4.2s                 4.0s  -3.4%
```
=> Improve __getattr__ handling

src/runtime/float.cpp, src/runtime/long.h
Installing gcc 4.9 installs its version of libc++, which breaks even clang builds unless we apply this fix.
for more info, see https://gcc.gnu.org/gcc-4.9/porting_to.html (search for "Header <cstddef> changes")
=> Gcc 4.9 gmp fix

src/capi/typeobject.cpp, src/codegen/ast_interpreter.cpp, src/codegen/irgen/irgenerator.cpp, src/core/types.h, src/gc/collector.cpp, src/gc/heap.cpp, src/runtime/builtin_modules/builtins.cpp, src/runtime/capi.cpp, src/runtime/classobj.cpp, src/runtime/descr.cpp, src/runtime/dict.cpp, src/runtime/objmodel.cpp, src/runtime/str.cpp, src/runtime/tuple.cpp, src/runtime/types.cpp, test/tests/print_function.py
This is an optimization that cpython uses.  It's helpful because we can't have an EmptyDict singleton like we do for EmptyTuple, and we are currently creating a dict for every call to a function that takes kwargs (many c api functions).
```
django_template2.py             5.0s (2)             5.0s (2)  -1.2%
pyxl_bench.py             3.3s (2)             3.2s (2)  -2.0%
sqlalchemy_imperative2.py             3.6s (2)             3.6s (2)  +0.5%
geomean                 3.9s                 3.9s  -0.9%
```
=> Allow passing NULL for empty kwargs

src/CMakeLists.txt, src/asm_writing/assembler.cpp, src/codegen/ast_interpreter.cpp, src/codegen/ast_interpreter.h, src/codegen/ast_interpreter_exec.S, src/codegen/baseline_jit.cpp, src/codegen/baseline_jit.h, src/core/ast.h, src/core/cfg.cpp, src/core/cfg.h, src/core/contiguous_map.h, src/runtime/builtin_modules/thread.cpp, src/runtime/types.cpp
This removes a bottleneck of the interpreter/bjit:
most var accesses introduced a DenseMap lookup, with this change we use a fixed offset per var.
The bjit stores the pointer to the vregs array inside r14 for fast accesses.
It is based on #720 (=the first commit is the same) and removes the fixed limit of variables.
This improves perf by: (this includes the perf gained by #720)
```
f1129a8463c7fdbd56:  7974141245e82dbd99:
django_template2.py             4.5s (6)             4.1s (4)  -8.6%
pyxl_bench.py            3.2s (10)             3.1s (4)  -3.9%
sqlalchemy_imperative2.py            3.8s (10)             3.6s (4)  -4.6%
geomean                 3.8s                 3.6s  -5.7%
```
=> assign fixed slots (vregs) to the symbols.

from_cpython/Include/iterobject.h, from_cpython/Lib/test/test_iter.py, from_cpython/Objects/iterobject.c, src/capi/abstract.cpp, src/codegen/compvars.cpp, src/runtime/builtin_modules/builtins.cpp, src/runtime/inline/list.cpp, src/runtime/iterobject.cpp, src/runtime/iterobject.h, src/runtime/objmodel.cpp, src/runtime/types.cpp
I need to clean this up, maybe write some tests for ourselves, but this nearly gets `test/cpython/test_iter.py` working.
There was a function `calliter_hasnext` in `from_cpython/Objects/iterobject.c`. It needs to throw exceptions, so I moved it to our own `iter.cpp`.
The behavior of `filter` depends on the type of its input. For filtering strings, I used cpython's code; for filtering tuples I wrote my own. I should probably pick a style. I guess `test_iter.py` doesn't implement filtering unicode, but I guess I should do that too.
The test is still throwing one exception:
```
d = {"one": 1, "two": 2, "three": 3, 1j: 2j}
for k in d:                                 
self.assertIn(k, d)                     
self.assertNotIn(k, d.itervalues())     
for v in d.values(): …
```
=> Get test_iter.py to work

src/codegen/ast_interpreter.cpp, src/codegen/ast_interpreter.h, src/codegen/baseline_jit.cpp, src/codegen/baseline_jit.h
- don't jit cold blocks after doing a OSR JIT compilation
- previously after doing a OSR JIT compilation we continued to JIT every block outside of the loop.
This doesn't show up as a perf change but reduces the number of JITed code / makes it slightly smaller.
- add the most common missing AST nodes to the baseline JIT
- with this PR I'm seeing only 6 aborts for ```django_template.py```, 1 abort for ```pyxl_bench.py``` and none for ```sqlalchemy_imperative.py```
=> bjit: add support for most common missing nodes and don't JIT compile cold blocks

src/capi/abstract.cpp, src/capi/object.cpp, src/capi/typeobject.cpp, src/core/types.h, src/runtime/builtin_modules/builtins.cpp, src/runtime/capi.cpp, src/runtime/descr.cpp, src/runtime/dict.cpp, src/runtime/import.cpp, src/runtime/iterobject.cpp, src/runtime/objmodel.cpp, src/runtime/objmodel.h, src/runtime/rewrite_args.h, src/runtime/types.cpp
with the goal of making sure that most exceptions we throw are CAPI exceptions rather that C++ exceptions.  This is just some easy things for now: getattr, getitem, and len().  The plan is then to add runtimeCall, callattr, and then finally add support from the interpreter and/or jit to call the capi-style versions (ideally with some sort of profiling guidance).
For django_template3, these changes cut the number of calls to __cxa_throw from 44k to 27k, and the number of C frames we unwind from 395k to 240k.
Not sure why there's a fairly consistent regression in pyxl_bench; I tried looking into it and it seems dwarfed by variability so I'm punting on that for now.
```
django_template3.py             3.8s (2)             3.7s (2)  -2.6%
pyxl_bench.py             3.0s (2)             3.1s …
```
=> start templatizing the runtime to be able to choose exception styles

src/asm_writing/rewriter.cpp, src/asm_writing/rewriter.h, src/codegen/baseline_jit.cpp, src/runtime/classobj.cpp, src/runtime/dict.cpp, src/runtime/list.cpp, src/runtime/set.cpp
- we hit an assert when we ran out of scratch space
- 'classobjSetattr' returned void but all runtime funcs must return a Box* object.
- sneak in a change which removes a unused arg from '_setupCall'
- skip retrying to jit very large blocks
- register iterator types with the correct size
- I checked all calls to ```BoxedHeapClass::create```
We may want to add a test run which forces to use the baseline JIT like we do for the other tiers...
This shows a perf change with our default thresholds which surprises me:
```
75e203a2dfac5578fc:  dbc4b9d2ff6f1b31a2:
django_template3.py             3.6s (4)             3.3s (4)  -7.2%
pyxl_bench.py             2.9s (4)             2.9s (4)  +1.4%
sqlalchemy_imperative2.py             3.3s (4)             3.2s (4)  -0.4%
geomean                 3.2s …
```
=> bjit: fix problems when setting bjit thresholds to 1

src/codegen/codegen.cpp, src/codegen/irgen.cpp, src/codegen/irgen/hooks.cpp, src/core/types.h, src/runtime/builtin_modules/builtins.cpp, src/runtime/capi.cpp, src/runtime/generator.cpp, src/runtime/inline/list.cpp, src/runtime/list.cpp, src/runtime/list.h, src/runtime/objmodel.cpp, src/runtime/objmodel.h, src/runtime/types.cpp
Which also involves templatizing most of the things that it
calls as well.
CompiledFunction's now have an additional parameter "exception_style",
and we will try to call a version of the function with the requested
style.  All of our runtime functions are written to the CXX style,
and there's not a whole lot of benefit until we templatize the runtime
functions individually.
Sorry for all the mess (duplication+churn) that this is creating.
=> Templatize runtimeCall for different exception styles

Makefile, src/codegen/compvars.cpp, src/codegen/irgen.h, src/codegen/irgen/hooks.cpp, src/codegen/irgen/hooks.h, src/codegen/irgen/irgenerator.cpp, src/codegen/irgen/irgenerator.h, src/codegen/runtime_hooks.cpp, src/codegen/runtime_hooks.h, src/codegen/unwinding.cpp, src/core/stats.cpp, src/core/types.h, src/runtime/builtin_modules/builtins.cpp, src/runtime/capi.cpp, src/runtime/dict.cpp, src/runtime/inline/link_forcer.cpp, src/runtime/inline/list.cpp, src/runtime/list.cpp, src/runtime/list.h, src/runtime/objmodel.cpp, src/runtime/objmodel.h, src/runtime/types.cpp, src/runtime/types.h, test/tests/incremental_tb.py, test/tests/incremental_tb_bjit.py
Specifically, for any attribute accesses inside a try-catch block.  Even with the new rewrites added here, there's still some perf penalty to using CAPI exceptions, so as we add more of these we should add some better heuristics for determining when to use them.  One idea is to only do this for try-catch blocks that catch AttributeErrors; at some point we'll need to make it profiling-based, since quite a few exceptions get thrown through intermediate frames without try-catch blocks.  (But then again, the cost of a c++ exception is roughly proportional to the number of frames it crosses so we might not have to do that to start seeing benefit in those cases.)
I'm getting a lot of variability when testing this change, so I tried benchmarking using the pgo build and it seems like the results …
=> have the llvm jit start emitting some capi-style calls

from_cpython/CMakeLists.txt, from_cpython/Include/compile.h, from_cpython/Include/pyconfig.h.in, from_cpython/Modules/_ctypes/_ctypes.c, from_cpython/Modules/_ctypes/callbacks.c, from_cpython/Modules/_ctypes/cfield.c, from_cpython/setup.py, src/capi/typeobject.cpp, src/runtime/int.cpp, src/runtime/objmodel.cpp, src/runtime/objmodel.h, src/runtime/types.cpp, src/runtime/types.h, src/runtime/util.cpp, test/tests/ctypes_import.py, test/tests/uuid_test.py
This PR allows us to compile the ctypes module and run `import ctypes`. Functionality has not been tested. This is part of WIP to run NumPy.
=> Import the ctypes module.

src/capi/abstract.cpp, src/runtime/builtin_modules/builtins.cpp, src/runtime/classobj.cpp, src/runtime/objmodel.cpp, test/tests/oldstyle_classes.py
**Note:**
* The `__complex__` could call `complexNew` in `complex.cpp` correctly. But `complexNew` need some improvements to support `str` and custom type.
* The behaviors of `__unicode__`, `__get__`, `__set__`, `__delete__` are exact same as in CPython. IMHO, there is no need to write additional code in `classobj.cpp`.
* `__missing__` only work in subclass of dict. So no need to write it in `classobj.cpp`.
* `__coerce__` in old style class could call the new added `coerce` builtin function correctly. But the `coerce` need further improvements.
**Update**
* According `import types; print sorted(types.InstanceType.__dict__.keys())` in CPython. Pyston has extra `__base__`.
* `__doc__`, `__new__` seems as instance's class attributes in Pyston. If these three attribute were fine, then the old …
=> Add some function to old style class

from_cpython/Lib/test/test_unary.py, src/runtime/complex.cpp, src/runtime/float.cpp, src/runtime/objmodel.cpp
__Change:__
* Add `__pos__` to `float` and `complex`
* Add compare support to `complex`
* Use new `callattr` replace old `getclsattrInternal` to find attribute, add error checking.
=> Some improvements to make test unary could pass

src/codegen/pypa-parser.cpp, src/runtime/complex.cpp, src/runtime/long.cpp, src/runtime/str.cpp
**Change**
* Pypy parser could not handle complex literal correctly, it always treat complex as 0.0j. Fix it. The code originally write by Marius.
* Add hash function to complex. Already tested. (But did not enable test_hash, please see below)
* Fix the wrong `mpz` usage in `long` constructor.
* Treat the hash value of empty string as Zero, like CPython did.
**Note**
After read CPython code. CPython str hash function will check `PYTHONHASHSEED` enviroment varialble in `random.c` file. But the Pyston DJB based str hash function didn't support it. I did some experiments try to fix it. But seems I couldn't use random number in str hash function (`types.h`). Pyston will report error:
```
pyston: ../../src/runtime/builtin_modules/thread.cpp:189: void pyston::setupThread():
Assertion …
```
=> Hash improvement for complex, str and long.

src/runtime/builtin_modules/thread.cpp, src/runtime/descr.cpp, src/runtime/objmodel.cpp, src/runtime/types.cpp, src/runtime/types.h, test/tests/thread_test.py, test/tests/wrapperdesc.py
With this change we print True for:
```
class C(object):
pass
print C.__str__ is object.__str__
```
Cheetah depends on this behavior (see https://bitbucket.org/pypy/compatibility/wiki/cheetah)
=> object.__str__ use capi slot in order to increase compatibility with cpython

from_cpython/Lib/test/test_compare.py, from_cpython/Lib/test/test_doctest2.py, from_cpython/Lib/test/test_getopt.py, from_cpython/Lib/test/test_pow.py, from_cpython/Lib/test/test_sets.py, from_cpython/Lib/test/test_unpack.py, src/analysis/type_analysis.cpp, src/codegen/ast_interpreter.cpp, src/codegen/ast_interpreter.h, src/codegen/irgen/hooks.cpp, src/codegen/irgen/irgenerator.cpp, src/codegen/runtime_hooks.cpp, src/codegen/runtime_hooks.h, src/codegen/unwinding.cpp, src/codegen/unwinding.h, src/core/ast.h, src/jit.cpp, src/runtime/builtin_modules/sys.cpp, src/runtime/inline/CMakeLists.txt, src/runtime/inline/link_forcer.cpp, src/runtime/objmodel.cpp, src/runtime/stacktrace.cpp, src/runtime/types.cpp, test/CPYTHON_TEST_NOTES.md, test/tests/classes.py, test/tests/compile_exec.py, test/tests/doctest_test.py
Needed `tuple.__module__` and `sys.displayhook` support.
A number of cpython's tests use doctest, so getting this to work meant some of those now pass and others get farther.  `test_doctest` is unfortunately not working, but since they use doctest to test itself... it's hard to tell whether it's the testing or tested part that's failing (or both).  If anyone is interested feel free to take a look :)
=> Add "doctest" support

src/capi/types.h, src/core/types.h, src/runtime/builtin_modules/builtins.cpp, src/runtime/builtin_modules/sys.cpp, src/runtime/classobj.h, src/runtime/code.cpp, src/runtime/descr.cpp, src/runtime/dict.cpp, src/runtime/dict.h, src/runtime/file.cpp, src/runtime/frame.cpp, src/runtime/generator.cpp, src/runtime/inline/xrange.cpp, src/runtime/iterobject.cpp, src/runtime/iterobject.h, src/runtime/list.cpp, src/runtime/list.h, src/runtime/long.cpp, src/runtime/set.cpp, src/runtime/set.h, src/runtime/str.cpp, src/runtime/super.cpp, src/runtime/traceback.cpp, src/runtime/tuple.cpp, src/runtime/tuple.h, src/runtime/types.cpp, src/runtime/types.h
Make them static functions on the type that the visit function is associated to whenever possible. Makes it more consistent and less likely to forget to update the visit function if we change the type's fields.
=> Refactor location and names of gc visit functions.

Makefile, from_cpython/Include/object.h, from_cpython/setup.py, src/capi/typeobject.cpp, src/capi/types.h, src/codegen/ast_interpreter.cpp, src/codegen/compvars.cpp, src/codegen/irgen/irgenerator.cpp, src/codegen/runtime_hooks.cpp, src/codegen/runtime_hooks.h, src/codegen/unwinding.cpp, src/core/ast.h, src/runtime/builtin_modules/builtins.cpp, src/runtime/capi.cpp, src/runtime/descr.cpp, src/runtime/float.cpp, src/runtime/inline/link_forcer.cpp, src/runtime/int.cpp, src/runtime/objmodel.cpp, src/runtime/objmodel.h, src/runtime/tuple.cpp, src/runtime/types.cpp, src/runtime/types.h, src/runtime/util.cpp, src/runtime/util.h, test/test_extension/setup.py, test/tests/varargs_ics.py
- add+use capi variants of runtimeCall and callattr entry points
- add some simple profiling to determine when to use C++ vs CAPI exceptions
Sorry for the huge PR; the early commits can stand on their own but they have a perf hit that is only made up by the later ones, so I didn't feel like separating into multiple prs.
=> more capi exceptions

.gitignore, src/CMakeLists.txt, src/codegen/ast_interpreter.cpp, src/codegen/irgen/hooks.h, src/codegen/irgen/irgenerator.cpp, src/codegen/runtime_hooks.cpp, src/codegen/runtime_hooks.h, src/codegen/unwinding.cpp, src/codegen/unwinding.h, src/core/types.h, src/runtime/cxx_unwind.cpp, src/runtime/exceptions.cpp, src/runtime/inline/link_forcer.cpp, tools/tester.py
Our exception-handling and unwinding code has always been a bit mixed together, which
makes it hard to add new features since things are pretty tightly coupled.  For instance,
the notion of a "reraise" was tightly coupled to the idea of a C stack frame and it was also
being tracked in the wrong place, and for these reasons we couldn't use capi exceptions
when we needed to do a reraise.
I think this PR makes things a bit cleaner:
- cxx_unwind.cpp handles C++ unwinding semantics
- unwinding.cpp converts C stacks to Python stacks
- exceptions.cpp takes Python stack frames and handles them appropriately
=> Clean up our exception handling

Makefile, src/codegen/ast_interpreter.cpp, src/codegen/irgen/hooks.cpp, src/codegen/irgen/irgenerator.cpp, src/codegen/osrentry.h, src/codegen/runtime_hooks.cpp, src/codegen/runtime_hooks.h, src/codegen/unwinding.cpp, src/core/types.h, src/runtime/exceptions.cpp, src/runtime/inline/link_forcer.cpp, src/runtime/objmodel.h, test/unittests/analysis.cpp
Also, allow reraising using CAPI exceptions.
It reduces C++ exceptions in django_template3 from 15k to 10k, but on the 10x version it cuts exceptions from 150k to 25k.  I think most of the remaining exceptions are occurring in the interpreter/bjit.  The other thing making our exceptions still slower (by about 2x) is that our exception "normalization" (calling the constructor if we need to) is slower than CPython's.
```
django_template3.py             3.3s (2)             3.3s (2)  -0.6%
pyxl_bench.py             2.9s (2)             2.9s (2)  -0.3%
sqlalchemy_imperative2.py             3.2s (2)             3.2s (2)  +0.3%
django_template3_10x.py            21.5s (4)            21.0s (4)  -2.7%
```
=> Use profiling to know when to throw CAPI exceptions

CMakeLists.txt, Makefile, cmake/pyconfig.cmake, docs/INSTALLING.md, from_cpython/Include/pyconfig.h.in, from_cpython/setup.py, test/tests/set.py, test/tests/sys_test.py, test/unittests/CMakeLists.txt
- add support for openpty (Fedora doesn't support the workaround like Ubuntu does)
- couple other minor fixes
It builds and runs, but it fails io_test.py (haven't looked into it much)
=> Get Pyston building on Fedora

from_cpython/Include/dictobject.h, microbenchmarks/string_key_ubench.py, src/asm_writing/assembler.cpp, src/asm_writing/assembler.h, src/asm_writing/rewriter.cpp, src/asm_writing/rewriter.h, src/capi/typeobject.cpp, src/codegen/ast_interpreter.cpp, src/gc/collector.cpp, src/gc/gc.h, src/gc/heap.cpp, src/runtime/capi.cpp, src/runtime/descr.cpp, src/runtime/dict.cpp, src/runtime/objmodel.cpp, src/runtime/tuple.cpp, src/runtime/types.h, src/runtime/util.cpp, test/tests/dict.py
The backstory is that while we do a pretty decent job of avoiding using dictionaries where CPython does, I was running into some cases where we use them as well, and we're slower since our dictionaries are slower.  This particular example was instantiating namedtuples, since the namedtuple class is created in an exec, and so when we get inside its `__init__`, we have to do slow lookups to access any of the builtins.  We could also try to optimize those cases specifically, or we could make our hidden class logic a "dict storage strategy" or some such.
But anyway, this pr just does some quick&easy things:
- switch from std::unordered_map to llvm::DenseMap
- The issue here is that llvm::DenseMap doesn't have a version that takes a custom allocator; Chris had #558, but I decided to fold in a …
=> Improve dictionary performance

Makefile, plugins/clang_linter.cpp, src/capi/abstract.cpp, src/capi/typeobject.cpp, src/codegen/irgen/hooks.cpp, src/codegen/unwinding.cpp, src/runtime/builtin_modules/builtins.cpp, src/runtime/builtin_modules/sys.cpp, src/runtime/builtin_modules/thread.cpp, src/runtime/capi.cpp, src/runtime/classobj.cpp, src/runtime/complex.cpp, src/runtime/descr.cpp, src/runtime/dict.cpp, src/runtime/exceptions.cpp, src/runtime/float.cpp, src/runtime/inline/dict.cpp, src/runtime/inline/list.cpp, src/runtime/inline/list.h, src/runtime/inline/tuple.cpp, src/runtime/int.cpp, src/runtime/list.cpp, src/runtime/long.cpp, src/runtime/objmodel.cpp, src/runtime/set.cpp, src/runtime/str.cpp, src/runtime/super.cpp, src/runtime/tuple.cpp, src/runtime/types.cpp, src/runtime/util.cpp
Which is faster for most of the builtin types since we use CPython's set-a-special-bit-on-the-class optimization.
Also, introduce a new clang-based linter which we can use to spot things like this.  It's currently disabled since it has a few issues (it's slow and not integrated with cmake), but should hopefully give us a base to write things like "make sure CAPI-style functions only call Pyston-style functions when inside a try block".  It might be a bit excessive for that though -- it seems to take just about as long to lint the code as it does to compile it.  There was a cool case though; I set up the linter to look for any occurrences of `isSubclass({.*}->cls, int_cls)`, and it found an instance where we did `isSubclass(cls, int_cls)` where cls was an implicit reference to `this->cls`! …
=> Change isSubclass(obj->cls, int_cls) to PyInt_Check

src/codegen/ast_interpreter.cpp, src/codegen/unwinding.cpp, src/runtime/builtin_modules/sys.cpp, src/runtime/classobj.cpp, src/runtime/dict.cpp, src/runtime/inline/dict.cpp, src/runtime/objmodel.cpp, src/runtime/tuple.cpp, src/runtime/types.cpp, src/runtime/types.h, src/runtime/util.cpp, test/tests/dict_internals.py
This lets us avoid checking equality if the hash values didn't match.
Checking equality can involve calling into user code, so it can be both
a perf drain and a noticeable behavioral difference.
I think this was the reason that we were seeing so much random variability in the sqlalchemy benchmark: it puts objects into dictionaries that have very complicated `__eq__`s defined for them, and expects them to not get called.  Depending on how the hash collisions worked out, we sometimes ended up calling them.
investigate.py says that this is an +0.8% perf regression, but measure_perf.py says that this is a whopping -5% improvement.  I think there's probably more that could be done to reduce any overhead, but I think it's still a good change.
=> Save the key hash in dictionaries

src/codegen/parser.cpp, src/codegen/pypa-parser.cpp, src/codegen/pypa-parser.h, test/tests/coding_cp1252_str.py
Previously we would always write out the data to a file, and then
call the parser on it.
Most of this is refactoring to split the file-handling logic (ie reading
from a FILE*) from stream-handling logic (encoding, counting line numbers,
etc).  One tricky point is handling encoding markers inside strings-to-
parse; we (and CPython) handle the file case by creating a Python file
object to iterate over it, and CPython handles the string case with a special
function to pre-process and decode the string.  This commit takes the
approach of creating a cStringIO file-like-object and running it through
the same decoding logic as the file case.
=> Have pypa parse strings directly

src/gc/heap.h
This attribute unfortunately lets the compiler skip stores if
the pointer doesn't escape.  This is bad because we will be
looking at the memory during a collection; the compiler was skipping
storing to cls and then the gc was crashing.
This didn't seem to affect performance at all.
=> Remove __attribute__((__malloc__)) from the gc

src/capi/typeobject.cpp
This is important because commonClassSetup will modify tp_as_number
if it exists.  This causes an issue when an extension class uses
multiple inheritance; it will inherit the tp_as_number from its
main base, but then copy in any fields from its secondary bases. But
tp_as_number points to the same struct as its parent, so it would
update the parent's slots accidentally.
So, move the tp_as_number copying to where CPython does it, or at least,
after the calls to inherit_slots.
=> Copy tp_as_number *after* commonClassSetup

src/codegen/baseline_jit.cpp
```
django_template3.py             3.0s (6)             3.0s (6)  -0.6%
pyxl_bench.py             2.6s (6)             2.6s (6)  -0.7%
sqlalchemy_imperative2.py             3.0s (6)             3.0s (6)  +0.2%
geomean                 2.9s                 2.9s  -0.4%
```
=> bjit: don't generate a 'getGlobal' call for 'None'

Makefile, src/asm_writing/rewriter.cpp, src/asm_writing/rewriter.h, src/codegen/baseline_jit.cpp, src/codegen/baseline_jit.h
By adding a SmallFunction class that is similar to std::function but stores closure data inline rather than in a dynamic allocation.
```
django_template3.py             3.0s (4)             2.9s (4)  -1.5%
pyxl_bench.py             2.7s (4)             2.6s (4)  -2.6%
sqlalchemy_imperative2.py             3.1s (4)             3.1s (4)  -0.7%
geomean                 2.9s                 2.9s  -1.6%
```
=> Don't malloc-allocate rewriter lambdas

src/asm_writing/icinfo.cpp, src/asm_writing/icinfo.h, src/asm_writing/rewriter.cpp, src/asm_writing/rewriter.h, src/codegen/baseline_jit.cpp, src/codegen/irgen/irgenerator.cpp, src/codegen/patchpoints.cpp, src/codegen/patchpoints.h, src/codegen/stackmaps.cpp, src/codegen/stackmaps.h, src/codegen/unwinding.cpp, src/core/thread_utils.h, src/core/util.h, src/runtime/ics.cpp
another one (percent) bites the dust:
```
django_template3.py             2.9s (4)             2.9s (2)  -1.2%
pyxl_bench.py             2.7s (4)             2.6s (2)  -0.8%
sqlalchemy_imperative2.py             3.1s (4)             3.0s (2)  -0.8%
geomean                 2.9s                 2.9s  -1.0%
```
=> Reduce some codegen allocations

from_cpython/Python/dtoa.c, src/analysis/type_analysis.cpp, src/codegen/compvars.cpp, src/gc/collector.cpp, src/gc/heap.cpp, src/runtime/types.cpp, test/tests/float.py, test/tests/str_functions.py
I was noticing that classes were getting freed a few
collections after they were seen to be not-marked; the
issue with the old keep-classes-alive implementation is
that it assumed that !isMarked() implies that the object
will be freed in the sweep phase.  With the finalization
ordering, this isn't true.  We could move the ordering
before the keep-classes-alive behavior, but then the
finalization ordering might get things wrong since it
wouldn't see the final set of mark bits.  So I think
we need to integrate the two phases.
I think it ends up working to just say that type objects
have ordered finalizers, even though they typically don't;
I think this gets us the guarantees we need.
=> Class gc fix: integrate with the finalization logic

from_cpython/Python/dtoa.c, src/analysis/type_analysis.cpp, src/codegen/compvars.cpp, test/tests/float.py, test/tests/str_functions.py
The first one (memory error) was the one I initially was planning to fix but then I run the test with ```-n``` and saw that there are additional problems. I'm somewhat surprised that no current test triggers them.
I'm not sure if ```AbstractFunctionType::callType``` should not in addition return ```UNKNOWN``` instead of ```UNDEF```. Because of this we will trigger an assert if we can't find a function that supports the requested args instead of just throwing an exception at runtime.
I don't like the ```AbstractFunctionType``` arg handling code I think it shouldn't copy so much, but I'm not currently feeling like rewriting it...
=> Fix a few errors encountered while running test/cpython/test_math.py

src/asm_writing/assembler.cpp, src/asm_writing/assembler.h, src/asm_writing/rewriter.cpp, src/asm_writing/rewriter.h, src/codegen/baseline_jit.cpp, src/codegen/baseline_jit.h
- If a jump offset is larger then 0x80 the instruction encoding requires 6bytes instead of 2bytes.
This adds up quickly, thats why we will try to find another jump to the slowpath with the same condition with a
smaller offset and jump to it / use it as a trampoline.
The benchmark show that this increases the performance slightly even though it introduces additional jumps.
- use xor instead of a mov to clear a register
```
ivy bridge
150982683ad1dcc208:  4f745cab9d0138b2c3:
django_template3.py             2.8s (4)             2.8s (4)  -0.3%
pyxl_bench.py             2.3s (4)             2.3s (4)  +0.4%
sqlalchemy_imperative2.py             2.9s (4)             2.8s (4)  -1.6%
geomean                 2.6s                 2.6s  -0.5%
broadwell
150982683ad1dcc208:  4f745cab9d0138b2c3: …
```
=> Small improvements to reduce the size of rewrites

src/runtime/builtin_modules/builtins.cpp, src/runtime/dict.cpp
Mostly around trying to avoid calling callattr().  Looks like most remaining calls to callattr (in django_template3) are coming from the interpreter, and specifically I think from namedtuple creation (which happens inside an exec so it never leaves the interpreter).
=> Some random runtime function optimizations

src/codegen/compvars.cpp, src/runtime/descr.cpp, src/runtime/objmodel.cpp, src/runtime/types.h
I want to get ride of the thousands of BoxedWrapperObject we create during calls.
Do do you guys think this is the right way?
If so I will clean it up / reduce the duplication between ```BoxedWrapperDescriptor::tppCall``` and ```BoxedWrapperObject::tppCall```
=> when calling a BoxedWrapperDescriptor don't create a BoxedWrapperObject

from_cpython/Lib/test/test_complex.py, src/capi/abstract.cpp, src/codegen/pypa-parser.cpp, src/runtime/complex.cpp
**Change:**
* Add some basic complex function implementations.
* Adjust some error checking, raise exception rather than use `assert`. Let the behavior consistent with CPython.
* Rewrite `complexNew`. Let it could accept **keyword** arguments, such as `complex(real=xx, imag=yy)`. And also accept `comlex`, `long`, `str`, `unicode` as `real` or `imag` argument. ~~But could not handle custom class with `__complex__` yet.~~
* Rewrite `complexFmt` based on CPython implementation. Let it could remove empty decimal point.
* Some small `complex` related changes.
closes #779
=> Complex improment

src/gc/collector.cpp, src/gc/collector.h, src/gc/gc.h, src/runtime/hiddenclass.cpp
Not all references in the program are being scanned, but we get away with it for now. Until we having a moving collector, don't actually scan those references, but make note that they are there.
I have no idea how the extra code I added ended up making things faster, it's probably a fluke, but at least it's not slower.
```
Comparing to '['baseline']'
running ['python', '../pyston-perf/benchmarking/benchmark_suite/fannkuch_med.py']
1.03298902512
pyston (calibration)                      :   1.03s baseline: 1.02 (  1.0%)
running ['../pyston-perf/benchmarking/../../pyston/./pyston_release', '../pyston-perf/benchmarking/be
nchmark_suite/django_template3.py']
4.54294991493
running ['../pyston-perf/benchmarking/../../pyston/./pyston_release', '../pyston-perf/benchmarking/be …
```
=> Notion of redundant visits to slowly move towards scanning everything

CMakeLists.txt, microbenchmarks/dict_globals_ubench.py, microbenchmarks/namedtuple_ubench.py, src/codegen/ast_interpreter.cpp, src/codegen/compvars.cpp, src/codegen/compvars.h, src/codegen/irgen.cpp, src/codegen/irgen/irgenerator.cpp, src/codegen/irgen/irgenerator.h, src/codegen/runtime_hooks.cpp, src/codegen/runtime_hooks.h, src/codegen/stackmaps.h, src/codegen/unwinding.cpp, src/core/types.h, src/runtime/inline/link_forcer.cpp, src/runtime/objmodel.cpp, src/runtime/objmodel.h, test/tests/exec_in_test.py, test/tests/generator_custom_globals.py
(motivated by namedtuple)
This involves two main changes:
- changing the calling convention to pass `globals` as an argument if needed
(this only applies going into compiled code, it's already passed into the interpreter)
- changing the llvm irgenerator to use the new globals object
Perf change isn't crazy but I think there might be some more improvements that this unlocks:
```
django_template3.py             2.9s (4)             2.9s (4)  +0.1%
pyxl_bench.py             2.3s (4)             2.3s (4)  -0.3%
sqlalchemy_imperative2.py             2.9s (4)             2.9s (4)  -0.5%
django_template3_10x.py            17.7s (2)            17.5s (2)  -0.9%
pyxl_bench_10x.py            17.4s (2)            17.4s (2)  -0.3%
sqlalchemy_imperative2_10x.py            21.8s (2)            21.5s (2) …
```
=> Support non-module-globals in the llvm tier

CMakeLists.txt, microbenchmarks/nq2.py, microbenchmarks/set_sub_ubench.py, src/core/from_llvm/DenseMap.h, src/core/from_llvm/DenseSet.h, src/core/thread_utils.h, src/runtime/set.h, src/runtime/types.h, tools/check_format.sh, tools/do_format.sh
llvm's DenseMap/DenseSet have a hardcoded minimum size of 64 buckets, which I think ends up wasting a lot of memory for us.  They also take longer to iterate over (more empty buckets to skip), which is probably not as big a deal in the macrobenchmarks but shows up in some microbenchmarks.
So, fork their implementation and lower the minimum to 8 (parameterizable now).  Surprisingly effective:
```
django_template3.py             2.8s (2)             2.8s (2)  -0.8%
pyxl_bench.py             2.3s (2)             2.3s (2)  -0.1%
sqlalchemy_imperative2.py             2.8s (2)             2.7s (2)  -4.4%
django_template3_10x.py            17.5s (2)            17.1s (2)  -2.6%
pyxl_bench_10x.py            17.5s (2)            17.4s (2)  -0.4%
sqlalchemy_imperative2_10x.py            21.0s (2) …
```
=> Lower initial dict/set size from 64->8

from_cpython/Include/longobject.h, from_cpython/Lib/test/test_index.py, src/capi/abstract.cpp, src/runtime/list.cpp, src/runtime/long.cpp, src/runtime/str.cpp, test/CPYTHON_TEST_NOTES.md
**Changes**:
- Add `__imul__` to `list` object, and let `list` could multiple with the instance which has `__index__` attribute.
- Let `str` could multiple with `long`.
Full list improvements is on the way. @kmod I saw your comment in current `listSort` function, should we use CPython's list sort with some Pyston changes, or improve the exist Pyston implementation? 
I have no preference. Just want to know copy lots of CPython code whether is suitable here.(the code of CPython list sort has many lines. Not only the `list_sort`, but also dependent functions.)
=> Some improvments that let test_index could pass

src/asm_writing/icinfo.cpp, src/asm_writing/icinfo.h, src/asm_writing/rewriter.cpp, src/asm_writing/rewriter.h, src/codegen/baseline_jit.cpp, src/codegen/irgen.cpp, src/codegen/irgen/hooks.cpp, src/codegen/irgen/util.cpp, src/codegen/irgen/util.h, src/core/types.h, src/gc/collector.cpp, src/gc/gc.h
Mostly disabled by `#if MOVING_GC` for now.
Depends on #874
=> Scan constants written into compiled code.

src/capi/typeobject.cpp, src/capi/types.h, src/codegen/unwinding.cpp, src/core/threading.cpp, src/gc/collector.cpp, src/gc/collector.h, src/gc/gc.h, src/gc/heap.cpp, src/gc/heap.h, src/runtime/builtin_modules/sys.cpp, src/runtime/classobj.h, src/runtime/descr.cpp, src/runtime/dict.cpp, src/runtime/file.cpp, src/runtime/frame.cpp, src/runtime/generator.cpp, src/runtime/hiddenclass.cpp, src/runtime/inline/xrange.cpp, src/runtime/iterators.cpp, src/runtime/iterobject.cpp, src/runtime/list.cpp, src/runtime/set.cpp, src/runtime/str.cpp, src/runtime/super.cpp, src/runtime/traceback.cpp, src/runtime/tuple.cpp, src/runtime/types.cpp, test/tests/iter_gc.py, test/tests/testing_helpers.py, test/tests/unicode_test.py
Enable the code that does the moving by changing `MOVING_GC` in `gc.h`
=> Optionally move objects around in memory to prepare Pyston for a moving collector.

src/runtime/classobj.cpp, src/runtime/classobj.h, src/runtime/objmodel.cpp
This just rewrites attribute reads, this helps a small microbenchmark I created but doesn't show up on our benchmarks.
I tried to also rewrite some attribute calls but it didn't work because I had to add guards after call instructions, so I removed it again.
At some point we should change the instance_* funcs to integrate the getattr+runtimeCall like we do for callattr to really fix the perf issue. But it looks like oldstyle classes aren't used often enough currently to make this a priority.
=> rewrite oldstyle class getattro

src/analysis/type_analysis.cpp, src/codegen/compvars.cpp, src/codegen/compvars.h, src/runtime/objmodel.cpp, test/tests/callattr_exceptions.py, test/tests/unpacking_types.py
ie concerning things like:
a, b = 1, 2
The irgen phase already knows how to do unpacking in a type-analyzed
way (a and b will be of type int), but type speculation needed to
have that added.
(this caused issues with speculation)
=> Type system fix: need to add unpacking to the type system

src/core/ast.cpp, src/core/ast.h, src/core/cfg.cpp, src/core/cfg.h
I'm using this temporarily for the CFG -> object cache I'm implementing (for generating the CFG hash).
While the hashing will change in the future to a more faster and safer approach, I still think having this in tree is useful e.g. if we add an option in the future to save the CFG to a file.
=> PrintVisitor: use raw_ostream

src/runtime/descr.cpp, src/runtime/objmodel.cpp, test/tests/defaults_changing.py
This seems to not matter very much, but it means that
Cls.__new__ is a the original function, instead of an
unbound instance method.
=> __new__ is supposed to become a staticmethod

src/core/from_llvm/DenseMap.h, src/core/from_llvm/DenseSet.h, src/runtime/builtin_modules/thread.cpp, src/runtime/classobj.cpp, src/runtime/dict.cpp, src/runtime/objmodel.cpp, src/runtime/set.cpp, src/runtime/types.cpp, test/integration/sqlalchemy_smalltest.py, test/tests/instance_methods.py
by expanding our test harness to be closer to how the tests get
run under pytest (which we don't support yet)
Also fix a couple minor things that this turned up.  There is a lot more
to be found here: the new harness supports many more of the sqlalchemy
tests, a number of which aren't working for us.  Also there is some
sort of issue with the current tests that we run, since repeating the tests
multiple times will end up crashing.
=> Get more of the sqlalchemy tests working

from_cpython/Lib/test/test_xrange.py, src/runtime/inline/xrange.cpp
Some xrange improvments that make `test_xrange` pass
**Changes:**
- Implement `__reduce__` and `__repr__`
- Improve the argument check in `xrange`
- Improve the `xrangeiterator`.
=> Some xrange improvments

src/runtime/set.cpp, src/runtime/types.h
The issue is that the set destructor, which is marked as "safe",
will try to access the type object.  But a safe destructor is not
allowed to assume that any objects are alive, including its own class.
We do actually force the class to be alive during a safe destructor,
but the tp_mro field was not so lucky.  We could try to address this by
saying again that types have ordered finalizers, which will cause them
to also keep their references alive.  But this doesn't completely work
since it will cause issues with objects that have actual ordered finalizers.
So for now, just remove type-check from the destructor.
=> Try to fix set-dtor segfault

src/runtime/int.cpp, test/tests/intmethods.py
After some investigation of the new added CPython tests. Some of them related to the long constructer. 
eg:
- Need to handle unicode string in `long()`; 
- Get correct error type and error message in long constructor. 
- etc...
When I fix it. I found our int constructor has same issue. So I make some improvements. The `test_long` need some discuss. So I create this PR first.
Changes:
This patch reorganize the error check in `_intNew`, and remove some unnessary or dead code.
=> some improvements in intNew

src/runtime/long.cpp, test/tests/long.py
The long constructor is far from complete. It block too many CPython tests. Just fix it along with other issues found in `test_long`. test_cpickle also blocked by it.
All these code are tested and passed in `test_long`. But not enabled `test_long` here. Because `mpz_get_d` use "round to zero", CPython need "round to nearest".
=> some long improvements

from_cpython/Lib/test/test_platform.py, src/runtime/builtin_modules/sys.cpp, test/tests/sys_test.py
`make run_test_platform` is just to pass with one error, pyston have no `sys.subversion`.
In [this document](https://docs.python.org/2/library/sys.html#sys.subversion), `sys.subversion` is just a placeholder, so implement it as const value.
Or maybe we should modify the test just ignore it?
=> make platform test pass

from_cpython/Lib/weakref.py, src/capi/typeobject.cpp, src/runtime/capi.cpp, src/runtime/descr.cpp, src/runtime/dict.cpp, src/runtime/list.cpp, src/runtime/objmodel.cpp, src/runtime/objmodel.h, src/runtime/types.cpp, src/runtime/types.h, test/integration/sqlalchemy_smalltest.py, test/tests/class_getattr.py, test/tests/class_setattr.py, test/tests/list_subclassing.py
Calling object.__getattribute__ on a class will skip the normal
special type attribute-lookup rules (checking base classes, executing
descriptors).
This PR also includes some other fixes to get a bunch more sqlalchemy tests working.
=> type.__getattribute__ and object.__getattribute__ are different

src/analysis/type_analysis.cpp, src/codegen/ast_interpreter.cpp, src/codegen/compvars.cpp, src/codegen/irgen/irgenerator.cpp, src/core/types.h, src/runtime/builtin_modules/builtins.cpp, src/runtime/types.h, test/tests/ellipsis.py, test/tests/ellipsis_more_test.py
*  some fix of Ellipsis
*  test more about Ellipsis
```
class TestEllipsis(object):
def __getitem__(self, item):
if item is Ellipsis:
return "Ellipsis"
else:
return "return %r items" % item
print Ellipsis
v = Ellipsis
print v
print type(v)
x = TestEllipsis()
print x[2]
print x[...]
```
results as 
```
<ellipsis object at 0x127000c4a8>
<ellipsis object at 0x127000c4a8>
<type 'ellipsis'>
return 2 items
../../src/codegen/ast_interpreter.cpp:552: pyston::Value pyston::<anonymous namespace>::ASTInterpreter::visit_slice(pyston::AST_slice *): Assertion `0' failed: not implemented
Someone called abort!
Traceback (most recent call last):
File "ellipsis_getname.py", line 16, in <module>:
print x[...]
```
but now 
```
Ellipsis
Ellipsis
<type 'ellipsis'>
return 2 items
Ellipsis
```
it fully passed
=> Ellipsis implementation

src/codegen/irgen/hooks.cpp, test/extra/babel.patch, test/extra/babel_test.py, test/tests/builtins.py
We don't support that, and hopefully we don't have to.  CPython seems
pretty inconsistent about it and PyPy doesn't support it.
=> Add a check to make sure users don't request custom __builtins__

.travis.yml, from_cpython/Include/code.h, src/runtime/classobj.cpp, src/runtime/code.cpp, src/runtime/import.cpp, src/runtime/types.cpp, test/extra/M2Crypto_patch.patch, test/extra/M2Crypto_test.py, test/extra/pyopenssl_test.py, test/lib/test_helper.py, test/tests/oldstyle_classes.py
- oldstyle classed don't add ```__bases__``` and ```__name__``` as attributes to their dict instead the intercept them with ```__getattribute__```
- it was possible to encounter a crash when importing a module and then deleting the entry from sys.modules and calling the function from the other module
```python
import gc, sys
def get_func():
from t2 import f2
print f2()
del sys.modules["t2"]
return f2
f = get_func()
gc.collect()
print f.__globals__ # <-- crashes here sometimes
f()                 # <-- this hits sometimes a release assert
```
- add a Pyston specific ```PyCode_GetArgCount``` instead of directly accessing ```code->co_argcount```
- In order to not have to patch swig for pyston I set the missing define ```SWIG_PYTHON_SLOW_GETSET_THIS``` with the ```CFLAGS``` environment …
=> add m2crypto test + fix missing stuff

src/asm_writing/rewriter.h, src/capi/typeobject.cpp, src/runtime/builtin_modules/builtins.cpp, src/runtime/classobj.cpp, src/runtime/cxx_unwind.cpp, src/runtime/objmodel.cpp, src/runtime/objmodel.h, src/runtime/rewrite_args.h, src/runtime/types.cpp, test/tests/binop_guarding.py
You can't get the return value from a RewriteArgs without
looking at the return convention.  Debug mode will check the
return convention during the execution of rewrites.
Split "VALID_RETURN" into "HAS_RETURN" and "CAPI_RETURN" since some
places used it to mean either.
Hopefully this helps keep things clean.  There are a lot of places that
were implictly assuming a certain return convention, but now that they
have to explicitly assume it, the issues are more obvious.  Plus
they will get checked in the debug builds.
Also tried to fix things up while going through and doing this refactoring;
I think I found a number of issues.
=> Add more asserts to aggressively enforce return conventions

src/capi/abstract.cpp, src/capi/object.cpp, src/capi/typeobject.cpp, src/capi/typeobject.h, src/codegen/compvars.cpp, src/core/cfg.cpp, src/core/types.h, src/runtime/builtin_modules/builtins.cpp, src/runtime/capi.cpp, src/runtime/classobj.cpp, src/runtime/complex.cpp, src/runtime/descr.cpp, src/runtime/dict.cpp, src/runtime/float.cpp, src/runtime/import.cpp, src/runtime/list.cpp, src/runtime/objmodel.cpp, src/runtime/objmodel.h, src/runtime/super.cpp, src/runtime/types.cpp
use a template to remove rewriter checks inside our most important runtime funcs when we know that the rewrite_args are NULL.
This is similar to #657 but uses a template arg. (as long as we only have two template args I think the are fine to use ... three would be bad :-D)
I looked at the assembly which clang generated and it's able to remove all rewriter specific code just by setting the ```rewriter_args``` to NULL in the beginning of the function.
Sadly this touches quite a lot of lines but I don't think the change is likely to introduce any bug because of this assert I added ```if (rewritable == NOT_REWRITABLE) {       assert(!rewrite_args); ```
```
origin/rewritable~:   origin/rewritable:
django_template3.py             2.7s (4)             2.7s (4)  -1.3%
pyxl_bench.py …
```
=> use a template to remove rewriter checks inside our most important runtime funcs

.travis.yml
Fixes:
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
=> Use travis_wait to workaround the no output received error

src/asm_writing/rewriter.cpp, src/asm_writing/rewriter.h
I think it's because the initial allocation of it fails.  This only shows
up in the debug build of lxml_test, which doesn't get tested through CI.
=> Fix a rare 'assert R11 is not used' crash

src/analysis/type_analysis.cpp, src/codegen/compvars.cpp, src/codegen/compvars.h, src/codegen/irgen/irgenerator.cpp, src/core/options.h, src/core/types.h, src/runtime/builtin_modules/builtins.cpp, src/runtime/inline/xrange.cpp, test/tests/int_ids.py
Feels like more work than it was worth:
```
django_template3.py             2.2s (2)             2.2s (2)  -0.1%
pyxl_bench.py             2.0s (2)             1.9s (2)  -3.6%
sqlalchemy_imperative2.py             2.4s (2)             2.4s (2)  +0.0%
django_template3_10x.py            14.3s (2)            14.4s (2)  +0.9%
pyxl_bench_10x.py            15.4s (2)            15.1s (2)  -2.5%
sqlalchemy_imperative2_10x.py            18.5s (2)            18.8s (2)  +1.3%
geomean                 6.0s                 5.9s  -0.7%
```
For now unboxed values can't get passed between BBs (compiler types don't have a hook to specify how to phi themselves, but that shouldn't be too hard to add if we need it).  Even with this limitation we seem to get most (but not all) of the benefit.
I think there's …
=> Reenable unboxed values

src/codegen/codegen.h, src/codegen/entry.cpp, src/codegen/irgen.cpp, src/codegen/irgen.h
This lets us to skip running the opt passes when we find a cached object file.
This has the disadvantage that opt passes are not allowed to call embedRelocatablePtr()
but has the advantage that we could do more costly optimizations in the future without hurting the perf on the second run.
```
upstream/master:  origin/cache_optim:
django_template3.py             2.4s (4)             2.2s (4)  -4.5%
pyxl_bench.py             2.0s (4)             1.9s (4)  -3.8%
sqlalchemy_imperative2.py             2.5s (4)             2.4s (4)  -3.4%
geomean                 2.3s                 2.2s  -3.9%
```
=> object cache: hash IR before running any opt passes

from_cpython/Include/object.h, src/asm_writing/assembler.cpp, src/asm_writing/assembler.h, src/asm_writing/rewriter.cpp, src/runtime/objmodel.cpp
This if WIP but before spending more time on it I would like to get feedback on it.
This removes the guarding ```Box::getattr``` adds for types which have the ```HAVE_VERSION_TAG``` set (aka. all types except capi extensions types which are not part of pyston)
instead it guards on the ```tp_version_tag```. 
There is currently a problem that the version tags are only 32bit and can overflow. So in case they overflow we need some mechanism to invalidate all ICs....
Perf change of the last commit:
```
django_template3.py             2.3s (4)             2.3s (4)  -1.2%
pyxl_bench.py             2.0s (4)             2.0s (4)  -2.4%
sqlalchemy_imperative2.py             2.5s (4)             2.5s (4)  -2.6%
geomean                 2.3s                 2.2s  -2.1%
```
=> typeLookup: guard on tp_version_tag instead of mro

from_cpython/Objects/floatobject.c, src/capi/typeobject.cpp, src/codegen/parser.cpp, src/codegen/pypa-parser.cpp, src/codegen/runtime_hooks.cpp, src/codegen/runtime_hooks.h, src/runtime/float.cpp, src/runtime/inline/link_forcer.cpp, src/runtime/objmodel.cpp, src/runtime/objmodel.h, src/runtime/str.cpp, src/runtime/types.cpp, test/tests/unicode_test.py
- switch to use cpythons repr handling - while I don't think python explicitly allows returning anything other than a string from ```__repr__``` and ```__str__``` cpython and pypy support it for string formats and we support it now too.
- enable libpypas optimizations which often let us omit an unary neg op when encountering something like ```-1```.
```
upstream/master:  origin/str_cleanup:
django_template3.py             2.2s (4)             2.2s (4)  -0.7%
pyxl_bench.py             1.9s (4)             1.9s (4)  -1.5%
sqlalchemy_imperative2.py             2.4s (4)             2.4s (4)  -0.4%
geomean                 2.2s                 2.1s  -0.9%
```
=> Cleanup the __str__, __repr__ support and let they handle unicode strings

from_cpython/Lib/test/test_set.py, src/runtime/dict.cpp, src/runtime/set.cpp, test/tests/set.py
**Ready to review**
**Changes:**
- Some improvements in `dict.cpp`, do not recompute the hash value in `fromKeys` if the container argument is set.
- Check the set is modified in iteration.
- Let the subclass of `set` and `frozenset` could take keyword argument.
- In some set functions, if the container argument is `set` or `dict, do not recompute the element hash value again.
- ~~Implement `__reduce__` to let `pickle` and `deepcopy` could work.~~ The new added commit of this file seems add this implementation. Remove it.
- Let `discard`, `remove` could handle the key which type is `frozenset`.
- Some other small bug fixing, such as clear the value in `init`, do not create new BoxedSet in `union` and other functions directly(need to apply `cls`), etc.
**Note**
- Disable two gc related …
=> Some stuff to enable "test_set"

src/codegen/compvars.cpp, src/codegen/compvars.h, src/codegen/irgen/irgenerator.cpp, src/codegen/runtime_hooks.cpp, src/codegen/runtime_hooks.h, src/core/types.h, src/runtime/inline/link_forcer.cpp, src/runtime/objmodel.cpp, src/runtime/objmodel.h, test/extra/pyopenssl_test.py, test/tests/slice.py
We've been allocating slice objects for slicing operations, but
CPython's internal slice methods already take separate start+stop
arguments.  So if we see a slice, instead of creating the slice
and sending it off to getitem, try calling PySequence_GetSlice.
This will be slower for classes with user-defined __getitem__
functions that can handle slices; we can fix that by adding rewriting
to this new endpoint, but it seems to not matter too much right now.
```
django_template3.py             2.4s (4)             2.4s (4)  +0.5%
pyxl_bench.py             2.1s (2)             2.1s (2)  +0.8%
sqlalchemy_imperative2.py             2.5s (2)             2.5s (2)  -0.3%
django_template3_10x.py            14.8s (2)            14.8s (2)  +0.2%
pyxl_bench_10x.py            15.7s (2)            15.1s …
```
=> Avoid creating most slice objects

src/asm_writing/icinfo.cpp, src/asm_writing/icinfo.h, src/asm_writing/rewriter.h, src/codegen/ast_interpreter.cpp, src/codegen/baseline_jit.cpp, src/codegen/baseline_jit.h, src/codegen/compvars.cpp, src/codegen/irgen.h, src/codegen/irgen/irgenerator.cpp, src/codegen/patchpoints.cpp, src/codegen/patchpoints.h
I chose IC slot size heuristic just by running a few times the benchmarks and taking the best one, we may want to adjust it later.
```
django_template3.py             2.2s (6)             2.2s (2)  -0.5%
pyxl_bench.py             1.9s (6)             1.8s (2)  -3.8%
sqlalchemy_imperative2.py             2.3s (6)             2.3s (2)  -1.3%
pyxl_bench2.py             1.5s (6)             1.3s (2)  -14.5%
django_template3_10x.py            14.3s (6)            14.2s (2)  -0.5%
pyxl_bench_10x.py            14.7s (6)            13.9s (2)  -5.4%
sqlalchemy_imperative2_10x.py            18.1s (6)            17.4s (2)  -3.4%
pyxl_bench2_10x.py            13.8s (6)            11.6s (2)  -15.9%
geomean                 5.4s                 5.1s  -5.9%
```
=> LLVM tier: adjust num of IC slots depending on the num of times the IC got rewritten in the bjit tier

from_cpython/Modules/_sre.c, from_cpython/Modules/cStringIO.c, from_cpython/Python/getargs.c, src/capi/modsupport.cpp, src/runtime/capi.cpp, src/runtime/objmodel.cpp, src/runtime/str.cpp
Other than the slices change, didn't find a whole lot; this PR reduces the number of collections by 2%.
Doesn't seem to have that much of an overall effect but I think it's still a good change:
```
django_template3.py             2.1s (4)             2.1s (2)  +0.1%
pyxl_bench.py             1.8s (4)             1.8s (2)  +0.2%
sqlalchemy_imperative2.py             2.3s (4)             2.3s (2)  +0.3%
django_template3_10x.py            13.6s (4)            13.7s (2)  +0.4%
pyxl_bench_10x.py            14.5s (4)            14.3s (2)  -1.3%
sqlalchemy_imperative2_10x.py            17.1s (4)            17.1s (2)  -0.2%
geomean                 5.6s                 5.6s  -0.1%
```
=> pyxl_bench allocation reductions

from_cpython/Objects/stringobject.c, src/capi/typeobject.cpp, src/capi/typeobject.h, src/gc/heap.cpp, src/runtime/objmodel.cpp, src/runtime/str.cpp
Please take a look at the the individual commits to figure out whats changed.
The switch from 4byte to a 2byte unicode type changed a lot of the unicode functions names so it maybe a good idea to regenerate the section ordering file but I was not sure with which perf sample I have to run it.
```
upstream/master:        origin/pyxl2:
django_template3.py             2.2s (4)             2.1s (2)  -1.8%
pyxl_bench.py             1.8s (4)             1.8s (2)  +1.3%
sqlalchemy_imperative2.py             2.3s (4)             2.3s (2)  +0.7%
pyxl_bench2.py             1.3s (4)             1.1s (2)  -19.5%
django_template3_10x.py            14.1s (4)            13.6s (2)  -3.7%
pyxl_bench_10x.py            13.9s (4)            14.2s (2)  +1.6%
sqlalchemy_imperative2_10x.py            17.6s (4) …
```
=> Misc optimizations for pyxl2

src/codegen/parser.cpp, src/core/types.h, src/runtime/capi.cpp
Add a FileHandle class for c++-style raii on FILE* objects.
Also, add support for using the cpython parser for parsing
strings (still only in -X mode).
=> Parser fix: call fclose

Makefile
Use configurable path to cpython to be able to build pyston on machines with default Python3.
=> Use configurable path to cpython

CMakeLists.txt
I guess our hack for pre-3.3 doesn't work in 3.3, but thankfully
we can include both the pre-3.3 workaround and the actual 3.3+ fix,
and it looks like cmake will end up doing the right thing in both cases.
Fixes #996 and #1002
=> Support CMake 3.3+

CMakeLists.txt, Makefile, plugins/refcount_checker/CMakeLists.txt, plugins/refcount_checker/refcount_checker.cpp
Surprisingly hard to get the build to work.  I feel like no one must use
libTooling for out-of-tree projects.  Also, the binary can only be run from
the directory in which it would have been placed for an in-tree project.
It was going to be a refcount discipline checker, but I'm not sure that's
a good use of time right now.  I want to check it in though so that we have it.
=> Add a clang libTooling example

src/asm_writing/rewriter.h, src/codegen/compvars.cpp
Got a couple build errors when building pyston in my clean Ubuntu 15.10 installation.
Adding the missing 'override's fixes them.
=> Fix build error caused by missing 'override's.

docs/INSTALLING.md
In the section "Building and testing" of INSTALLING.md, have commands to clone the clang and the llvm repositories, but the links are broken.
=> Changing the INSTALLING instructions. 

src/analysis/scoping_analysis.cpp, src/codegen/ast_interpreter.cpp, src/codegen/ast_interpreter.h, src/codegen/baseline_jit.cpp, src/codegen/codegen.cpp, src/codegen/entry.cpp, src/codegen/irgen.h, src/codegen/irgen/irgenerator.cpp, src/codegen/irgen/irgenerator.h, src/codegen/patchpoints.cpp, src/codegen/patchpoints.h, src/codegen/unwinding.cpp, src/core/cfg.cpp, src/core/cfg.h, src/core/stringpool.cpp, src/core/stringpool.h, src/core/types.h
This splits up the handling of deopts and normal frame introspection (e.g. for a traceback).
We have to add to nearly all call sites frame introspection which makes it very important that it does not introduce much overhead over a normal call instruction.
By always storing the user visible variables into a vregs array (layout the same as in the interpreter/bjit) we can make introspection cheaper.
Frame introspection only needs to access user facing variables therefore we don't have to generate extra bytes for spilling variables which get clobbered in the callee because all values we need to access are inside the vregs array.
This let's use remove the 95byte overhead and reduces the stackmap size.
It adds a slight cost of maintaining the vregs array but we were already doing some of this …
=> Cheaper frame introspection

src/runtime/import.cpp, test/tests/sys_path_str.py, test/tests/sys_path_str_subclass.py, test/tests/sys_path_unicode.py, test/tests/sys_path_unicode_subclass.py
I use isSubclass check if a given entry in `sys.path` is subclass of `str` or `unicode` and tried to allow both situations. If it is `unicode`, I also convert it to `str` with `PyUnicode_AsEncodedString()` with `Py_FileSystemDefaultEncoding `.
I also modified `nullImporterInit` to make it accept subclasses of `str`.
=> Fix #599 by allowing subclasses of string and unicode in sys.path

src/gc/collector.cpp
Make it better performance using std::vector instead of std::list
```
Comparing to '['baseline']'
pyston (calibration)                      :   0.66s baseline: 0.66 ( -0.2%)
pyston django_template3_10x.py            :   8.98s baseline: 9.10 ( -1.3%)
pyston pyxl_bench_10x.py                  :   7.45s baseline: 7.39 (  0.8%)
pyston sqlalchemy_imperative2_10x.py      :  10.43s baseline: 10.47 ( -0.4%)
pyston django_template3.py                :   1.60s baseline: 1.64 ( -2.2%)
pyston pyxl_bench.py                      :   1.00s baseline: 1.02 ( -1.1%)
pyston pyxl_bench2.py                     :   0.73s baseline: 0.72 (  1.6%)
pyston sqlalchemy_imperative2.py          :   1.44s baseline: 1.46 ( -1.1%)
pyston pyxl_bench2_10x.py                 :   6.18s baseline: 6.15 (  0.4%)
pyston …
```
=> Micro optimization on 'gc_invalidateOrderedFinalizerList'

src/runtime/generator.cpp
This could happen when we trigger a collection inside the BoxedGenerator constructor when allocating space for the args array.
In this case it would not be set but we would dereference the memory.
=> Fix crash inside BoxedGenerator::gcHandler

from_cpython/Include/Python.h, src/gc/collector.cpp, src/runtime/import.cpp
This function let's one register a potential root range from the CAPI
Was part of the unmerged #1026 but split out because #1029 requires it too.
=> add PyGC_AddPotentialRoot

from_cpython/CMakeLists.txt, from_cpython/Include/dictobject.h, from_cpython/Objects/dictobject.c, src/capi/typeobject.cpp, src/runtime/dict.cpp, src/runtime/dict.h, src/runtime/inline/dict.cpp, src/runtime/types.cpp, test/tests/builtins.py, test/tests/capi_slots.py, test/tests/descriptors_double.py
- implement ```attrwrapper.has_key```
- switched to cpythons ```dictview``` types because we were missing a lot of functionality.
- different types for the dict iterators
- support empty tp_new
- add descriptor default type arg: descr.__get__(self, obj, type=None)
=> fix minor compatibility issues

from_cpython/Objects/floatobject.c, src/runtime/float.cpp, src/runtime/frame.cpp, src/runtime/int.cpp, src/runtime/long.cpp, src/runtime/long.h, test/tests/float.py, test/tests/intmethods.py, test/tests/long.py
Some NumPy bugs was difficult to debug. For example, one of those bugs just due to Pyston's `int` has no `__long__`. Others are similar, so I decide to let Pyston's numeric types have fully support first.
Rewrite some `int` methods implementation, and add some missing attributes.
=> Add some missing attributes to Int object

src/codegen/compvars.cpp, src/codegen/compvars.h, test/tests/type_errors.py
=> Don't abort when generating a call of a known type which is not callable.

src/runtime/descr.cpp, test/tests/static_class_methods.py
fixes #1033
I think there are more of this still around, at some point we should audit all this ```cls ==``` checks.
=> Allow subclassing classmethod and staticmethod

src/gc/collector.cpp
this showed up while importing a C extension
and fixes a bug introduced in #1043
=> Correctly align pointers inside registerPotentialRootRange

src/runtime/builtin_modules/builtins.cpp, src/runtime/long.cpp, src/runtime/objmodel.cpp, src/runtime/types.cpp, test/tests/int_ids2.py
Before we did not use the interned ints for constants inside the source code
so every module had there on 0, 1 etc...
=> Use our interned ints more often (especially for constants specified inside the source)

test/extra/lxml_test.py
Disable lxml objectify tests because they depend on refcounting GC behavior and are therefore very flaky
=> Disable lxml objectify tests

src/codegen/patchpoints.h
With the new frame introspection we don't need to save additional space for spilling vars which live in regs (except for deopts).
And for deopts we will never need more scratch than the one required for spilling the args.
```
upstream/master:     origin/pp_stack:
django_template3.py             2.1s (2)             2.1s (2)  -0.4%
pyxl_bench.py             1.8s (2)             1.8s (2)  +0.2%
sqlalchemy_imperative2.py             2.2s (2)             2.2s (2)  -0.4%
pyxl_bench2.py             1.1s (2)             1.1s (2)  -1.1%
django_template3_10x.py            14.0s (2)            13.9s (2)  -0.6%
pyxl_bench_10x.py            13.7s (2)            13.6s (2)  -1.0%
sqlalchemy_imperative2_10x.py            16.9s (2)            17.0s (2)  +0.3%
pyxl_bench2_10x.py             9.3s (2) …
```
=> llvm tier: reduce scratch size

Makefile
See also: #1069 
There are other scripts (``configure_travis.sh`` and ``src/run-tests.sh`` in libpypa upstream). Need to get a Ubuntu system up to double check they wouldn't break (they would if there we bash-specific code in it)
=> Switch to /usr/bin/env sh for portability

CMakeLists.txt
Fixes #1071 (building jemalloc dep on BSD systems)
See also:
- #1068
- https://github.com/neovim/neovim/blame/73dbd14/third-party/CMakeLists.txt#L25
from neovim, (Apache License v2)
=> Search for gmake and make when building

src/runtime/traceback.cpp, src/runtime/traceback.h, test/tests/traceback_test2.py
I implements `tb_lineno` but I don't know this is right implementatation.
I know `tb_linno` should assigend by frame's `f_lineno` but this implementation looks different.
I check it print right `tb_lineno` on below code after this patch...
```python
import sys, traceback
def lumberjack():
bright_side_of_death()
def bright_side_of_death():
return tuple()[0]
try:
lumberjack()
except IndexError:
exc_type, exc_value, exc_traceback = sys.exc_info()
print "*** print_tb:"
traceback.print_tb(exc_traceback, limit=1, file=sys.stdout)
print "*** print_exception:"
traceback.print_exception(exc_type, exc_value, exc_traceback,
limit=2, file=sys.stdout)
print "*** print_exc:"
traceback.print_exc()
print "*** format_exc, first and last line:"
formatted_lines = traceback.format_exc().splitlines()
print …
```
=> implement tb_lineno of Traceback

src/codegen/baseline_jit.cpp, src/codegen/baseline_jit.h, src/runtime/ics.cpp, src/runtime/ics.h
This removes the 2GB process limitation I ran into.
(With the EH frame format we are using the code offset is specified as a 32bit signed offset)
I checked if aligning the code speeds it up but I did not notice any perf change.
=> EH frame: use a single allocation for the EH frame + generated code

src/runtime/inline/CMakeLists.txt
I think this was the cause of the 'Python.h not found' errors.
=> Add missing runtime/inline include dependence

from_cpython/Include/pystate.h, from_cpython/Lib/logging/__init__.py, from_cpython/Lib/traceback.py, src/codegen/ast_interpreter.cpp, src/codegen/ast_interpreter.h, src/codegen/irgen/irgenerator.cpp, src/codegen/irgen/irgenerator.h, src/codegen/runtime_hooks.cpp, src/codegen/runtime_hooks.h, src/codegen/unwinding.cpp, src/codegen/unwinding.h, src/core/threading.cpp, src/core/types.h, src/runtime/exceptions.cpp, src/runtime/frame.cpp, src/runtime/generator.cpp, src/runtime/inline/link_forcer.cpp, src/runtime/traceback.cpp, src/runtime/traceback.h, src/runtime/types.cpp, src/runtime/types.h, test/tests/generator_threads2.py, test/tests/sys_getframe_exited.py
This replaces #1007 with a faster approach (I leave it up until this one is merged).
add frame intospection for exited frames
this works by copying the last locals state into the BoxedFrame when we exit a function.
As a perf improvement we only create BoxedFrames if _getframe got called or an exception got thrown.
It turned out that our python frame retrieving / updating code was really slow (using libunwind) I replaced it now with
a approach which manually keeps track of the python frames (calling initFrame/deinitFrame every time a functions gets called / exits).
Sadly we can't inline this functions in the llvm tier currently because it uses thread local storage which the JIT does not support.
But I have a prototype which works around the issue with inline asm.
We also store now always …
=> support inspecting exited frames (faster version)

src/analysis/scoping_analysis.cpp, src/capi/object.cpp, src/runtime/float.cpp, test/tests/datetime_test.py
* Quick fix for issue #1083
* use _PyObject_GetDictPtr of cpython implementation
* `std::sort(allDerefVarsAndInfo.begin(), allDerefVarsAndInfo.end(), derefComparator);` to remove functor and use lambda expression
now pyston can fully execute `test/cpython/test_datetime.py`
=> Quick fix for issue #1083

src/codegen/cpython_ast.cpp, src/codegen/parser.cpp, src/core/ast.cpp, src/core/cfg.cpp
Because we only checked for Or's instead of checking for Ands this did not cause any issues except when printing the CFG
=> Fix cpython parser bool operation conversion

from_cpython/Lib/test/test_signal.py, from_cpython/Modules/signalmodule.c, src/codegen/ast_interpreter.cpp, src/codegen/ast_interpreter.h, src/codegen/baseline_jit.cpp, src/codegen/baseline_jit.h, src/codegen/entry.cpp, src/codegen/irgen/irgenerator.cpp, src/codegen/runtime_hooks.cpp, src/codegen/runtime_hooks.h, src/core/threading.cpp, src/core/threading.h, src/runtime/capi.cpp, src/runtime/inline/link_forcer.cpp, src/runtime/types.h, test/CPYTHON_TEST_NOTES.md, test/tests/signal_test.py
We check for signals on most calls to runtime functions in the llvm tier and the bjit and inside the interpreter on some additional places, because checking on every bytecode is a too large slowdown (>10%).
I don't like that there is different behavior between the different tiers but it was the best result I could accomplish.
This patch does more checks than pypy does see: https://bitbucket.org/pypy/pypy/issues/1841/signal-check-only-in-jump_absolute-when
I think the perf regression is not nice but I think we could accept it:
```
django_template3.py             2.1s (6)             2.2s (4)  +2.8%
pyxl_bench.py             1.8s (6)             1.8s (4)  +4.2%
sqlalchemy_imperative2.py             2.2s (6)             2.3s (4)  +3.0%
pyxl_bench2.py             1.1s (6)             1.1s (4) …
```
=> Add signal support

from_cpython/CMakeLists.txt, from_cpython/Include/classobject.h, from_cpython/Include/dictobject.h, from_cpython/Include/methodobject.h, from_cpython/Lib/test/pickletester.py, from_cpython/Lib/test/test__locale.py, from_cpython/Lib/test/test_cookie.py, from_cpython/Lib/test/test_cpickle.py, from_cpython/Lib/test/test_locale.py, from_cpython/Lib/test/test_pickle.py, from_cpython/Lib/test/test_pickletools.py, from_cpython/Lib/test/test_sax.py, from_cpython/Lib/test/xmltestdata/test.xml.out, from_cpython/Modules/cPickle.c, from_cpython/setup.py, src/capi/typeobject.cpp, src/capi/types.h, src/runtime/builtin_modules/builtins.cpp, src/runtime/builtin_modules/sys.cpp, src/runtime/classobj.cpp, src/runtime/dict.cpp, src/runtime/list.cpp, src/runtime/long.cpp, test/CPYTHON_TEST_NOTES.md, test/tests/cPickle_test.py
- add the ```_locale``` module
- add the ```cPickle``` module
the module is much faster than the python implementation (in a small benchmark by about 4x)
But I had to change the code a little bit because of our GC and more importantly because some of our types have different names etc...
I also noticed that we failed to to set ```capifunc.__module__``` in a lot of cases which made pickle error
- together this makes us run 7 more tests :-)
=> add the _locale and cPickle modules

from_cpython/Lib/socket.py, from_cpython/Lib/ssl.py, from_cpython/Lib/test/test_asynchat.py, from_cpython/Lib/test/test_asyncore.py, from_cpython/Lib/test/test_ftplib.py, from_cpython/Lib/test/test_httplib.py, from_cpython/Lib/test/test_poplib.py, from_cpython/Lib/test/test_ssl.py, from_cpython/Lib/test/test_telnetlib.py, from_cpython/Lib/test/test_urllib2net.py, from_cpython/Lib/test/test_urllibnet.py, from_cpython/Lib/urllib2.py, from_cpython/Modules/socketmodule.c, from_cpython/Modules/socketmodule.h, src/jit.cpp, test/CPYTHON_TEST_NOTES.md, test/cpython/badcert.pem, test/cpython/badkey.pem, test/cpython/https_svn_python_org_root.pem, test/cpython/keycert.pem, test/cpython/nokia.pem, test/cpython/nullbytecert.pem, test/cpython/nullcert.pem, test/cpython/sha256.pem, test/cpython/wrongcert.pem, test/extra/M2Crypto_patch.patch
The socket implementation used to only call close on a socket when all references where gone.
This works fine for cpython which uses reference counting but for pyston (and pypy) this is a problem.
This works around the problem in a similar way as pypy does.
It also uses the same method names so that 3th party libs which already support pypy will automatically work with pyston too.
(e.g. urllib3)
I would prefer if we get ref counting but meanwhile this improves the situation a lot. (While I'm not sure if this does not break other stuff but I would prefer to not spend to much time on this now if it may get replaced soon)
=> socket fixes

src/capi/typeobject.cpp, src/runtime/builtin_modules/builtins.cpp, src/runtime/objmodel.cpp, src/runtime/rewrite_args.h, test/tests/getattr_start_failing_test.py
Otherwise callers have no way of knowing if an exception might
occur in the rewritten code, and they'd have to conservatively
not rewrite those cases (such as 3-arg getattr).
Well, previously getattr() wasn't doing that, so it would rewrite
itself correctly for a descriptor that is not throwing now, but would
start throwing later (those exceptions would get propagated instead
of being caught by getattr).
=> Add a ReturnConvention for getattrs that can C++ throw

src/capi/typeobject.cpp
Sometimes we started filling in the method-cache before calling add_operators.
add_operators directly modifies the class objects, so it needs to signal that
the cache is now invalid.
I think CPython avoids needing this since they never call add_operators
after doing any type lookups, but we are a bit more flexible with our initialization.
=> Call PyType_Modified() in add_operators()

src/runtime/list.cpp, src/runtime/tuple.cpp, test/tests/list.py, test/tests/tuples.py
For `tuple.__add__`, if we throw an exception in our `tuple.__add__`, we won't bother checking for an `__radd__`. So before throw exception, I call `__radd__` first. If both return `NotImplemented`. Throw an exception.
For `list.__mul__`. Before throw `TypeError, XXX object cannot be interpreted as an index`., I check the argument type whether is `int` or `long` first. If not, throw `TypeError, can't multiply sequence by non-int of type XXX`. This may not the correct solution, but the behavior is more like CPython.
=> Tuple and list calling order fixing.

src/runtime/float.cpp, src/runtime/int.cpp, src/runtime/str.cpp
Split from https://github.com/dropbox/pyston/pull/1014
In the second commit, I add a special case in `typeCallInner` for `int_cls`, since it's the most common one to show up. It helps performance a bit.
```
Comparing to '['baseline']'
pyston (calibration)                      :   1.01s baseline: 1.02 ( -0.6%)
pyston django_template3.py                :   1.98s baseline: 1.97 (  0.2%)
pyston pyxl_bench.py                      :   1.63s baseline: 1.62 (  0.5%)
pyston sqlalchemy_imperative2.py          :   2.12s baseline: 2.11 (  0.3%)
pyston django_template3_10x.py            :  11.72s baseline: 11.53 (  1.6%)
pyston pyxl_bench_10x.py                  :  12.84s baseline: 12.78 (  0.5%)
pyston sqlalchemy_imperative2_10x.py      :  16.31s baseline: 16.13 (  1.1%)
pyston (geomean-2ec9) …
```
=> Fixes for tp_new for C extensions

CMakeLists.txt, from_cpython/Lib/test/test_ascii_formatd.py, from_cpython/Lib/test/test_uuid.py, from_cpython/Lib/types.py, from_cpython/Modules/_ctypes/ctypes.h, src/capi/modsupport.cpp, src/runtime/import.cpp, src/runtime/long.cpp, test/extra/cffi-1.2.1.patch, test/extra/cffi_test.py, test/lib/test_helper.py, test/tests/ctypes_test.py, test/tests/type_flags.py
We can now run most of the CFFI tests.
Some of the changes were required because CFFI tests loading the same shared library several times from different locations.
The CFFI patch introduces a memory leak but I think this is okay for now because we will soon be able to remove it when we switch to ref counting
=> fixes for CFFI and add an integration test for it

from_cpython/Include/Python.h, from_cpython/Include/frameobject.h, from_cpython/Modules/_ctypes/callbacks.c, from_cpython/Python/traceback.c, src/codegen/unwinding.cpp, src/runtime/builtin_modules/sys.cpp, src/runtime/capi.cpp, src/runtime/code.cpp, src/runtime/code.h, src/runtime/cxx_unwind.cpp, src/runtime/exceptions.cpp, src/runtime/frame.cpp, test/extra/lxml_test.py, test/integration/Cython-0.22.patch, test/integration/numpy_test.py, test/tests/ctypes_traceback.py
tracebacks: implement PyFrame_New and PyCode_New / custom traceback entries from the CAPI
- it only allows creating empty code objects but this is enough to allow ctypes and cython to create custom traceback entries.
- It's not enough for removing the pyexpat and all cython code object workarounds (because some paths need 'real' code object / frames)
- I also changed ```ExcInfo``` to use ```NULL``` instead of ```None``` for a unset traceback which makes it more similar to cpython and allows ```PyTraceBack_Here``` to work correctly
=> add support for custom traceback entries

from_cpython/Include/abstract.h, from_cpython/Include/pyerrors.h, from_cpython/Python/errors.c, src/capi/abstract.cpp, src/capi/types.h, src/core/threading.cpp, src/runtime/builtin_modules/builtins.cpp, src/runtime/builtin_modules/sys.cpp, src/runtime/builtin_modules/thread.cpp, src/runtime/types.cpp, test/tests/cPickle_test.py, test/tests/compile_eval.py, test/tests/dict_setting.py, test/tests/dict_setting_old_dict.py, test/tests/sys_test.py
- call threading._after_fork and threading._shutdown, return real thread id
- fix attrwrapper of an object which becomes dict backed and support non str key types
_I tried to merge the attrwrapper code with our dict code. But sadly this introduced quite some slowdown which make me switch back to this minimal fix._
- fix thread.error pickling
=> Threading and multiprocessing related fixes

src/runtime/objmodel.cpp, test/tests/binops_subclass.py
If the rhs is a subclass of the lhs, call into the reverse op first.
Performance looks unaffected or only very minor slowdown.
@Daetalus confirmed that this is fixing the numpy problem he had.
=> implement correct binop lookup for subclasses

src/asm_writing/assembler.cpp, src/asm_writing/assembler.h, src/codegen/ast_interpreter.cpp, src/codegen/ast_interpreter.h, src/codegen/baseline_jit.cpp, src/codegen/baseline_jit.h, test/tests/bjit_osr_test.py
We can't directly do OSR from the bjit frame because it will cause issues with exception handling.
Reason is that the bjit and the OSRed code share the same python frame and the way invokes are implemented in the
bjit. During unwinding we will see the OSR frame and will remove it and continue to unwind but the try catch
block inside ASTInterpreter::execJITedBlock will rethrow the exception which causes another frame deinit,
which is wrong because it already got removed.
Instead we return back to the interpreter loop with special value (osr_dummy_value) which will trigger the OSR from there.
=> bjit: don't directly do a OSR from the bjit

src/codegen/baseline_jit.cpp, src/codegen/baseline_jit.h
saves a few bytes because r12 requires the SIB byte
django_template bjit bytes emitted shrinks from 3016247 to 3006353
=> bjit: microptimization use r13 instead of r12 for the interpreter pointer

src/codegen/compvars.cpp, test/tests/unicode_iteration.py
If we find a type that
- we think we can reason about statically
- does not have an `__iter__` but can be iterated via `__getitem__`
we previously just bailed saying that we know it doesn't have an `__iter__` method
(instead of calling getiterHelper like we should).  I think we've always had this,
we've just never run into it until testing the refcounting in llvm-only mode.
=> Fix a llvm-tier getiter() bug

from_cpython/Modules/_io/bufferedio.c, src/codegen/ast_interpreter.cpp, src/codegen/baseline_jit.cpp, src/jit.cpp, src/runtime/capi.cpp, src/runtime/objmodel.cpp, test/tests/dict.py, test/tests/set.py
fixes leaks in
- interactive mode
- -m mode
- when calling ```tp_setattr``` from ```setattr()```
- creating duplicate set and dict entries from an AST node
I could not enable the tests yet because the need the generator abandonment fix but this fix is not ready yet but I want to land this fixes now so we don't do duplicate work.
=> Misc refcounting leaks encountered while fixing the generator abandonment tests

src/codegen/ast_interpreter.cpp, src/codegen/baseline_jit.cpp, src/codegen/irgen/irgenerator.cpp, src/runtime/set.cpp, src/runtime/set.h, test/tests/dict.py, test/tests/set.py
we have to insert the elements in reverse in order to replicate cpythons behaviour.
cpython is pushing the temps on it's value stack and than inserting them ona after another by poping them from the stack
=> fix set.add() for existing keys and fix set ast node when encountering keys with same hashes

from_cpython/Lib/test/test_parser.py, from_cpython/Lib/test/test_structseq.py, from_cpython/Modules/parsermodule.c, src/runtime/float.cpp, src/runtime/iterators.cpp, src/runtime/iterobject.cpp, src/runtime/set.cpp, src/runtime/set.h, src/runtime/tuple.cpp, src/runtime/types.cpp, test/tests/float.py, test/tests/tuples.py
this issues all got triggered by cpython test we currently have disabled.
Generally I'm not really sure what pattern to use (and I'm very inconsistent with it) when a value needs to get decrefed incase a exception get's throwen but else returned. 
- create a ```AUTO_DECREF(x)``` and do a ```return incref(x)```
- use a try catch block and only decref in the catch (probably fastest way to do it in case the exception is very unlikely but also verbose)
- use something like ```ExceptionCleanup``` which decrefs it in the destructor when an exception gets thrown...
=> Misc refcounting leaks encountered while fixing the generator abandonment tests part 2

src/analysis/function_analysis.cpp, src/asm_writing/rewriter.cpp, src/asm_writing/rewriter.h, src/codegen/ast_interpreter.cpp, src/codegen/baseline_jit.cpp, src/codegen/baseline_jit.h, src/codegen/irgen/irgenerator.cpp, src/core/ast.cpp, src/core/ast.h, src/core/cfg.cpp, src/core/types.h, src/runtime/objmodel.cpp, src/runtime/str.cpp, test/tests/local_lifetime.py, test/tests/resurrection.py
to help clear out temporaries (ie subexpressions) in a more timely fashion.
=> Add some liveness information to the cfg

src/codegen/ast_interpreter.cpp, src/core/types.h, src/runtime/builtin_modules/builtins.cpp, src/runtime/generator.cpp, src/runtime/iterators.cpp, src/runtime/types.h
We seem to be calling malloc() a lot more than we used to.  Some manual sampling turned up a couple places that could be fixed:
- Anything that used to use a STLCompatAllocator got switched back to malloc, which is quite a bit slower for allocation/reallocation.  I tried to reserve() the space to reduce this a little bit.
- pyElements had gained an allocation, which this commit gets rid of
- some things got switched from our gc functions to PyMem_Malloc which is malloc
The net result is pretty small :/  about 1% on django_template3 and less on sqlalchemy_imperative2
=> Trying to reduce allocations in refcounting branch

src/codegen/baseline_jit.cpp
the comment was totally not true, result can't be 0 for our uses it was just missing a ```refUsed``` call
=> bjit: directly emit recordType again

from_cpython/Lib/test/mapping_tests.py, from_cpython/Lib/test/test_file.py, from_cpython/Lib/test/test_memoryio.py, src/codegen/unwinding.cpp, src/codegen/unwinding.h, src/runtime/cxx_unwind.cpp, src/runtime/objmodel.cpp, test/tests/dict_comparisons.py
This time it was from trying to look at the result of isUnwinding()
to determine if the function terminated successfully or via an exception.
(And in the exception case, to decref some values that would have been returned.)
This got tripped up in a case where we through an exception, this triggers
an AUTO_DECREF which takes an object to zero decrefs, which has a custom destructor,
and calls code that ends up calling isUnwinding().  This is all happening from inside
a C++ destructor, so this counts as isUnwinding().
We had some code to try to keep isUnwinding() meaning what we wanted to use it for,
but it was only for certain cases.  I think we might be able to extend it to more cases,
but it seems like that would be a losing battle since it's hard to say when "unwinding"
ends and then we …
=> Another run-arbitrary-code-during-unwinding issue

src/codegen/compvars.cpp, src/codegen/irgen/irgenerator.cpp, src/codegen/irgen/refcounts.cpp, test/tests/undef_join.py
I think I had gotten confused and mixed up "undefined variables" (Python
variables which hadn't gotten set) and "undefined values" (results of
expressions that the JIT knows will throw, or otherwise can't evaluate).
For undefined *variables*, we represent them using None, since they can
still have refcount operations done on them.
For undefined *values* (or results), we can use llvm's undefValues, since
they should never be touched.
=> Fix usage of undef variables

src/codegen/ast_interpreter.cpp, src/codegen/ast_interpreter.h, src/codegen/baseline_jit.cpp, src/runtime/types.cpp, test/tests/generator_cycle2.py
without this we would never traverse the variable and the GC would therefore be unable to destroy the generator
=> interpreter: mark created_closure as live variable inside yields

src/codegen/pypa-parser.cpp, src/runtime/builtin_modules/builtins.cpp, src/runtime/inline/xrange.cpp, src/runtime/iterators.cpp, src/runtime/objmodel.cpp, src/runtime/str.cpp, src/runtime/types.cpp
this should make pyston more robust to cases where the error is set by a previous operation
no functional change intended
=> check return value instead of calling checkAndThrowCAPIException()

src/asm_writing/assembler.cpp, src/asm_writing/assembler.h, src/asm_writing/rewriter.cpp, src/asm_writing/rewriter.h, src/runtime/objmodel.cpp, src/runtime/types.cpp, test/extra/cffi_test.py
we used to emit always 64bit comparisons.
Some functions return an ```int``` so we have to emit a 64bit comparison because can't assume anything about the upper 32bits.
=> checkAndThrowCAPIException needs to do a 32bit comparison in some cases

src/runtime/frame.cpp, src/runtime/tuple.cpp, src/runtime/types.cpp, src/runtime/types.h
split out of https://github.com/dropbox/pyston/pull/1177 which is broken...
```
upstream/refcounti:  origin/perf_refcou:
django_template3.py             2.8s (4)             2.8s (6)  -0.8%
pyxl_bench.py             2.9s (4)             2.8s (6)  -2.1%
sqlalchemy_imperative2.py             2.8s (4)             2.8s (6)  -1.2%
pyxl_bench2.py             1.3s (4)             1.2s (6)  -1.2%
django_template3_10x.py            14.2s (4)            14.0s (6)  -1.7%
pyxl_bench_10x.py            18.8s (4)            18.3s (6)  -2.5%
sqlalchemy_imperative2_10x.py            20.1s (4)            19.9s (6)  -0.8%
pyxl_bench2_10x.py            10.6s (4)            10.6s (6)  -0.3%
geomean                 6.0s                 5.9s  -1.3%
```
=> add tuple free list and don't update boxed frame on exit when it's not used

Makefile, src/capi/typeobject.cpp, src/core/types.h, src/runtime/builtin_modules/builtins.cpp, src/runtime/capi.cpp, src/runtime/descr.cpp, src/runtime/generator.cpp, src/runtime/objmodel.cpp, src/runtime/rewrite_args.h, src/runtime/types.cpp, src/runtime/types.h, test/tests/arg_refs.py
This lets it more-efficiently keep track of the different situations in which it might return, because it doesn't have to pass back data signalling which path it took and what cleanups need to be done afterwards.
This is a perf win and also lets us not incref the args in as many cases -- before it was kind of expensive to pass back an extra flag saying whether or not the args should be decreffed.
```
origin/refcounting:  personal/rearrange:
django_template3_10x.py            13.8s (2)            13.6s (2)  -1.4%
sqlalchemy_imperative2_10x.py            19.2s (2)            18.9s (2)  -1.5%
pyxl_bench2_10x.py            11.3s (2)            10.4s (2)  -8.6%
geomean                14.4s                13.9s  -3.9%
```
=> Make rearrangeArgs take a callback instead passing back values

from_cpython/Objects/obmalloc.c, from_cpython/Objects/unicodeobject.c, src/runtime/types.cpp
- switch back to CPython's PyUnicode_New (which uses the freelist)
- add some LIKELY/UNLIKELY annotations to PyUnicode_New and PyObject_Malloc
Results on top of refcounting are quite encouraging, but when on top of rearrange_and_call, it actually shows a small regression.  I feel like something weird is going on with pyxl_bench2_10x, and I feel like this change should help...
=> Some misc performance optimizations

src/runtime/builtin_modules/builtins.cpp, src/runtime/str.cpp, src/runtime/types.cpp, test/tests/str_functions.py, test/tests/wrapperdesc.py
Without `str.__rmod__`, `"%s" % numpy.string_` will force NumPy call `numpy.reminder`. This is horrible.
=> some minor NumPy fixing

README.md, test/tests/unicode_iteration.py
this only adds the ```test/tests/unicode_iteration.py``` test.
Main motivation for this is that this commits showed up in https://github.com/dropbox/pyston/compare/refcounting...dropbox:master?expand=1 and I feared it forgot to merge them...
=> merge the missing merge commits (mostly cosmetic change)

src/core/types.h, src/runtime/inline/dict.cpp, src/runtime/inline/list.cpp, src/runtime/list.h, src/runtime/long.h, src/runtime/types.cpp, src/runtime/types.h
so that it can be used in more places.  Looking at pyxl_bench2_10x,
most of the calls to PyType_GenericAlloc are from the dict and list
iterator classes, which don't use DEFAULT_CLASS_SIMPLE (or DEFAULT_CLASS)
since they use the same C++ class with multiple Python classes.  So
by extracting out the core of that function, it's now usable by those
other classes.
Also convert some things to DEFAULT_CLASS_SIMPLE while we're at it.
=> Extract the logic from DEFAULT_CLASS_SIMPLE

from_cpython/Include/objimpl.h, from_cpython/Modules/gcmodule.c
this is an advantage for _PyObject_GC_TRACK
which before compiled to something like this:
```
cmpq    $-2, -16(%rdi)
jne     .LBB0_2
movq    $-3, -16(%rdi)
movq    _PyGC_generation0(%rip), %rax
movq    %rax, -32(%rdi)
movq    _PyGC_generation0(%rip), %rax
movq    8(%rax), %rax
movq    %rax, -24(%rdi)
leaq    -32(%rdi), %rcx
movq    %rcx, (%rax)
movq    _PyGC_generation0(%rip), %rax
movq    %rcx, 8(%rax)
```
and now compiles to
```
cmpq    $-2, -16(%rdi)
jne     .LBB0_2
movq    $-3, -16(%rdi)
movq    _PyGC_generation0(%rip), %rax
movq    %rax, -32(%rdi)
movq    8(%rax), %rcx
movq    %rcx, -24(%rdi)
leaq    -32(%rdi), %rdx
movq    %rdx, (%rcx)
movq    %rdx, 8(%rax)
```
notice that it had to load `_PyGC_generation0` three times because the compiler had to assume that because of aliasing it …
=> microptimization: mark _PyGC_generation0 as having a const address

Makefile, src/asm_writing/rewriter.cpp, src/capi/typeobject.cpp, src/capi/typeobject.h, src/runtime/objmodel.cpp, src/runtime/objmodel.h, test/extra/numpy_fulltest.py, test/integration/numpy_test.py, test/lib/test_helper.py, test/tests/arg_refs.py, test/tests/cpython_oldstyle_getattr_crash.py
- Add test/extra/numpy_fulltest.py that is similar to numpy_test.py, but runs the entire testsuite.
- Fix a few more cases where we add more refs than CPython does.  Fixes #1196 
I also tried to improve performance measurement by force-rebuilding src/ and from_cpython/ when we do pgo builds.  I'm not sure if this was necessary; it seems to help but it is hard to judge.
=> Some work on the numpy test suite

from_cpython/Objects/stringobject.c, src/runtime/str.cpp, test/extra/numpy_fulltest.py
string is special in that it is a c++ type which has tp_as_number and tp_as_sequence.
This causes problems because when we fixup the slot dispatcher we will set the tp_as_number fields but not the
tp_as_sequence because setting both can cause problems.
Some extensions (e.g. numpy) require that we use the sq_* functions instead of nb_*.
Therefore clear the tp_as_number fields (except nb_remainder which cpython has set too because it is not part of
tp_as_sequence).
=> str: use tp_as_sequence instead of tp_as_number

.travis.yml, src/capi/typeobject.cpp
since we were installing it from the LLVM APT repo, which they
took down since it was getting too expensive.  I guess we can
just run with the gcc build until that situation gets resolved.
=> Temporarily disable the clang build on travis-CI

src/asm_writing/assembler.cpp, src/asm_writing/rewriter.cpp, src/asm_writing/rewriter.h, src/codegen/ast_interpreter.cpp, src/codegen/ast_interpreter.h, src/codegen/baseline_jit.cpp, src/codegen/baseline_jit.h, src/codegen/unwinding.cpp, src/runtime/objmodel.cpp, test/tests/iter_del_time.py
First patch of baseline JIT improvements.
the major changes are:
- it reenables the optimization that we don't use the vregs for compiler generated vars which don't get used after the current basic block
- allows usage of r12 and r15 in the bjit
- jit bjit code into 31bit address space
This makes the generated code look much more reasonable and is a good foundation for further improvements.
I have a second tier of patches which I will put into another PR which makes the bjit reuse some of the vregs which improves the performance further.
```
upstream/master:    origin/bjit_opt2:
django_template3.py             2.8s (4)             2.6s (4)  -6.5%
pyxl_bench.py             2.8s (4)             2.4s (4)  -13.7%
sqlalchemy_imperative2.py             2.7s (4)             2.7s (4)  -2.7% …
```
=> major bjit improvements

src/codegen/ast_interpreter.cpp, src/codegen/baseline_jit.cpp, src/codegen/codegen.cpp, src/codegen/irgen.cpp, src/codegen/irgen/hooks.cpp, src/codegen/irgen/irgenerator.cpp, src/codegen/unwinding.cpp, src/core/cfg.cpp, src/core/cfg.h, src/core/types.h, test/unittests/analysis.cpp
this splits the vregs into three parts (from the two we had before user visible/not user visible):
```
user visible: used for all non compiler generated names, name could be used in a single block or multiple
all frames contain atleast this vregs in order to do frame introspection
cross block : used for compiler generated names which get used in several blocks or which have closure scope
single block: used by compiler created names which are only used in a single block.
get reused for different names
we assign the lowest numbers to the user visible ones, followed by the cross block ones and finally the single block
ones. we do this because not all tiers use all of the vregs and it still makes it fast to switch between tiers.
```
This reduces stack space because of the lower total number …
=> vregs: reuse block local vregs

src/codegen/cpython_ast.cpp, src/core/ast.cpp, src/core/ast.h
This fixes a bug with expressions inside loops in interactive mode
that resulted in expressions not being printed:
>> for i in range(3):
...    i
...
>>
Python prints the value every iteration:
>> for i in range(3):
...    i
...
0
1
2
>>>
The same also applies to while loops.
=> Improve REPL support

from_cpython/Include/boolobject.h, from_cpython/Include/pyport.h, src/codegen/ast_interpreter.cpp, src/codegen/baseline_jit.cpp, src/codegen/compvars.cpp, src/codegen/opt/const_classes.cpp, src/runtime/bool.cpp, src/runtime/builtin_modules/builtins.cpp, src/runtime/builtin_modules/pyston.cpp, src/runtime/builtin_modules/sys.cpp, src/runtime/capi.cpp, src/runtime/dict.cpp, src/runtime/float.cpp, src/runtime/inline/boxing.h, src/runtime/iterobject.cpp, src/runtime/list.cpp, src/runtime/objmodel.cpp, src/runtime/set.cpp, src/runtime/str.cpp, src/runtime/types.cpp, src/runtime/types.h, src/runtime/util.cpp
Some extensions will use `True` and `False` from other package. For example, X11 defines `True` and `False` in `/usr/include/X11/Xlib.h`. Which will cause name conflict when try to build extensions which use x11.
I think this is not good solution. V8 encountered it too:
https://bugs.chromium.org/p/v8/issues/detail?id=448
But we can't control how extension handle it. So just add a prefix to it.
closes #1242
=> add prefix to Pyston defined True and False

Makefile, docs/PROFILING, src/codegen/ast_interpreter.cpp, src/codegen/baseline_jit.cpp, tools/annotate.py, tools/perf_jit.py
a hack which should only get enabled when specifically looking into the bjit perf...
=> perf: add a script which allows 'perf report' to disassemble JITed functions

.travis.yml, from_cpython/Include/Python.h, from_cpython/Modules/gcmodule.c, src/capi/object.cpp, src/codegen/ast_interpreter.cpp, src/codegen/compvars.cpp, src/codegen/irgen/irgenerator.cpp, src/codegen/irgen/refcounts.cpp, src/codegen/irgen/util.h, src/runtime/types.cpp, test/tests/signal_ref_test.py
I think this is why test_telnetlib fails sporadically (it's hard to reproduce so I'm not 100% sure).  We currently leak references in most cases if we throw an exception via a signal.
Also, this PR changes the leak-checking behavior to only report "direct" leaks, and hides objects that were only leaked due to being referenced by other leaked objects.  Hopefully this makes debugging future leaks easier.
=> Fix some leaks related to signals

src/asm_writing/rewriter.cpp, src/asm_writing/rewriter.h, src/codegen/baseline_jit.cpp, src/codegen/baseline_jit.h
Misc improvements, please take a look at the individual commits to find out what changed
```
upstream/master:    origin/bjit_opt7:
django_template3.py             2.6s (4)             2.4s (4)  -6.7%
pyxl_bench.py             2.3s (4)             2.2s (4)  -1.9%
sqlalchemy_imperative2.py             2.8s (4)             2.6s (4)  -7.9%
pyxl_bench2.py             1.2s (4)             1.2s (4)  -2.0%
django_template3_10x.py            13.9s (4)            13.1s (4)  -5.7%
pyxl_bench_10x.py            17.6s (4)            17.5s (4)  -0.9%
sqlalchemy_imperative2_10x.py            20.4s (4)            18.9s (4)  -7.5%
pyxl_bench2_10x.py            10.2s (4)            10.0s (4)  -1.9%
geomean                 5.6s                 5.4s  -4.4%
```
=> rewriter+bjit: remove duplicate getattrs, misc codegen improvements

src/codegen/ast_interpreter.cpp
OSR can fail in some cases and we have to continue with interpreting in this cases.
=> bjit: fix failed OSR

from_cpython/Lib/test/test_types.py, src/runtime/types.cpp
give ` type_cls ` the attribute member ` __basicsize__  ` and  ` __itemsize__ `
=> Add type.__basicsize__, type.__itemsize__

src/asm_writing/assembler.h, src/asm_writing/icinfo.cpp, src/asm_writing/icinfo.h, src/asm_writing/rewriter.cpp, src/asm_writing/rewriter.h, src/codegen/baseline_jit.cpp, src/codegen/baseline_jit.h, src/codegen/patchpoints.cpp, src/codegen/patchpoints.h, src/runtime/ics.cpp, src/runtime/ics.h
ICs: variable size IC slots
before this change we had a fixed number of equal size slots inside an IC.
Because of the large difference in rewrite sizes a fixed slot size is not ideal.
We often ended up with too large slots which prevented us from emitting more slots.
(or very large ICs in general which are bad for memory usage and the instruction cache)
With this commit we will start with a single slot with the size of the whole IC and then decreasing its size to the actual bytes emitted
and creating a new slot which starts directly at the end of the previous slot.
We will repeat to to this until the space left is smaller than the number of bytes the last slot required.
This makes it a little bit less likely that we will be successful in overwritting an existing slot
but our benchmarks …
=> ICs: variable size IC slots

microbenchmarks/large_import_bench.py, src/codegen/irgen/refcounts.cpp, src/codegen/opt/inliner.cpp
Some small optimizations speed up this part of the pipeline ~25%.  Not a huge overall win since refcounting is about 20% of (cached-case) LLVM time, but at least we can claw some of the refcounting regression back.
The remaining time is largely spent manipulating the LLVM IR.
```
django_template3.py             2.3s (2)             2.3s (2)  -0.6%
pyxl_bench.py             2.2s (2)             2.2s (2)  -0.4%
sqlalchemy_imperative2.py             2.5s (2)             2.5s (2)  -0.9%
pyxl_bench2.py             1.2s (2)             1.2s (2)  -0.8%
pyxl_bench_10x.py            16.8s (2)            16.8s (2)  -0.4%
django_template3_10x.py            12.4s (6)            12.3s (2)  -0.4%
sqlalchemy_imperative2_10x.py            18.0s (2)            18.1s (2)  +0.1%
pyxl_bench2_10x.py …
```
=> Optimize the llvm refcounter pass

src/asm_writing/icinfo.cpp, test/tests/decrefinfo_invalidation.py
The pattern seems to be that we invalidate an IC (deregestering the decrefinfo),
but there is a stack frame in that IC and furthermore that stack frame will
get unwound via an exception.
The fix I did here is to not deregister the decrefinfo if num_inside>0.
@undingen could you give it a review?  I think this is enough to fix the issue but still allow the same amount of potential rewriting, but it's hard to be sure.
=> Track down an elusive reference leak

src/asm_writing/rewriter.cpp, src/asm_writing/rewriter.h, src/capi/typeobject.cpp, src/codegen/ast_interpreter.cpp, src/codegen/baseline_jit.cpp, src/codegen/baseline_jit.h, src/codegen/compvars.cpp, src/codegen/irgen/irgenerator.cpp, src/codegen/runtime_hooks.cpp, src/codegen/runtime_hooks.h, src/runtime/classobj.cpp, src/runtime/dict.cpp, src/runtime/inline/link_forcer.cpp, src/runtime/objmodel.cpp, src/runtime/objmodel.h, test/test_extension/slots_test.c, test/tests/capi_slots.py, test/tests/slice.py
only lookup `__[set/get/del]slice__` for slice AST nodes
before this change
`C()[slice(1,2)] = "a"`
would call into `__setslice__` because it got handled as
`C()[1,2] = "a"`
the problems only appeared after the guarding change in `setitem` because before we called `mp_ass_subscript` even when it was `slot_mp_ass_subscript` when we encountered before a type which had a `!=  slot_mp_ass_subscript` (we missed the guard)
I'm not sure if there is not a much nicer way to resolve this which I missed..
=> only lookup __[set/get/del]slice__ for slice AST nodes

src/codegen/irgen/hooks.cpp, src/runtime/builtin_modules/builtins.cpp, test/tests/execfile_test.py, test/tests/pyc_stress_test.py
Or rather, have execfile() be more permissive in what it accepts.
It may still abort when we get to pickGlobalsAndLocals() and we
discover that we can't actually execute in that particular attrwrapper.
=> Support attrwrapper as globals argument to execfile

src/codegen/irgen/refcounts.cpp, src/core/cfg.cpp, test/extra/pyopenssl_test.py, test/tests/test_package/import_target.py
Fix the scipy.weave issue (we didn't handle this circular-import-error correctly)
Don't require explicit annotations for constant null pointers in the llvm jit
- I didn't want to loosen the assertions, so instead it just adds the annotations for you.
=> Some scipy fixes

src/asm_writing/assembler.cpp, src/asm_writing/icinfo.cpp, src/asm_writing/icinfo.h, src/asm_writing/rewriter.cpp, src/asm_writing/rewriter.h, src/asm_writing/types.h, src/codegen/ast_interpreter.cpp, src/codegen/baseline_jit.cpp, src/codegen/baseline_jit.h, src/codegen/patchpoints.cpp, src/codegen/patchpoints.h, src/codegen/unwinding.cpp
Small bjit and rewriter improvements
- use r12, r15 and rbx in bjit and inside bjit ICs
- remove some nonzero calls when we already know that the object is a python bool
- don't check if the arguments of a function are nonzero in the entry block
Also changes the way we keep track of which registers are available inside the rewriter:
Keeping the available registers in a bitset makes it more memory efficient and
also easier and faster to calculate a subset of the registers.
I will soon implement the 'otherThan' functionality using it which would fix the current problem of only allowing to exclude one register.
=> use r12, r15 and rbx in bjit and inside bjit ICs, remove some nonzero checks

src/runtime/types.cpp, test/extra/cffi_test.py, test/integration/pytest_test.py, test/tests/functions.py
Internally we store it as either-dict-or-module, but when we expose
it to Python it needs to be given back as a mapping.  I looked briefly
into switching the internal representation, but that seemed like a much
more invasive change.
Also, add a pytest test that exposed this issue.
=> Have function.func_globals always be dict-like

src/codegen/cpython_ast.cpp
They end up generating "pass" statements with a lineno of 0, which
trips an assert later on.  This commit just sets them to have a lineno
of 1.
=> Support empty lines on the repl

src/codegen/irgen/irgenerator.cpp, src/core/cfg.cpp, test/tests/literals_order.py
Fix literals_order issue #1191
not create temporary variables when remapExpr
=> Fix evaluation order for dict operations

src/core/types.h, src/runtime/hiddenclass.cpp, src/runtime/hiddenclass.h, src/runtime/objmodel.cpp, src/runtime/types.cpp
+ use pyston::DenseMap to save a little more memory
this saves about 5%-10% of peak memory on django
=> hidden classes: split into subclasses to reduce memory consumption

src/codegen/compvars.cpp, src/codegen/irgen.cpp, src/codegen/irgen.h, src/codegen/irgen/hooks.cpp, src/codegen/irgen/irgenerator.cpp, src/codegen/irgen/irgenerator.h, src/core/types.h
=> delete the llvm module after code generation

src/asm_writing/icinfo.cpp, src/asm_writing/icinfo.h, src/core/types.h
when we overwrote a existing IC slot we forgot to remove the old invalidator entries.
Took the opportunity to clean up the code a little bit
=> ICSlotInfo: remove old invalidator entries

src/runtime/ics.cpp, src/runtime/ics.h
we should not execute memory which got allocated using malloc
(crashes a lot of memory inspection tools and also the windows subsystem for linux)
I replaced it with a trivial mmap allocator which never unmaps the memory
(but reuses the memory if a runtime ICs gets deleted)
I think this is fine for now:
- there are <100 runtime ICs used per test
- because all runtime ICs have the same size there is no problem with fragmentation
=> runtime ICs: use mmap instead of malloc for executable code

src/codegen/baseline_jit.cpp, src/codegen/baseline_jit.h
we used to destroy the `ICInfo` before all references to it got deleted.
I run into this when using the glibc alloc instead of jemalloc
=> bjit: fix memory corruption

src/asm_writing/icinfo.cpp, src/asm_writing/rewriter.cpp, src/capi/typeobject.cpp, src/runtime/capi.cpp, src/runtime/classobj.cpp, src/runtime/objmodel.cpp, src/runtime/types.cpp, src/runtime/util.cpp, test/tests/elementree_test.py
The issue is that the object could be deallocated and then a similar one reallocated in the same place.  We've dealt with this in some places but not in all, and it came up again :(  So get the rest of the places that this could affect.
=> Fix uses of addGuard(python_object)

libunwind_patches/0003-use-a-sorted-array-for-registered-objects-and-do-a-b.patch, src/codegen/baseline_jit.cpp, src/codegen/baseline_jit.h, src/codegen/memmgr.cpp, src/codegen/memmgr.h, src/codegen/unwinding.cpp, src/codegen/unwinding.h, src/runtime/ics.cpp, src/runtime/ics.h
- previously we never deregistered the EH frame from libunwind (which exposed a bug)
- I removed the calls to register the EH info with gcc since we have our own unwinder which does not need this
- cleaned up the code and fixed some small memory leaks
=> EH: correctly deregister EH frames and cleanup the code 

src/asm_writing/icinfo.cpp, src/asm_writing/icinfo.h, src/codegen/ast_interpreter.cpp, src/codegen/baseline_jit.cpp, src/codegen/baseline_jit.h, src/codegen/codegen.h, src/codegen/irgen/hooks.cpp, src/core/cfg.h, src/core/types.h
we free now the code blocks after a recompile in the LLVM tier (except for OSR frames) because
it is likely that we will not use the code anymore.
- we have to make sure we are not currently executing any code we will delete that's why I added bjit_num_inside
- there were some cases where we forgot to deregister stuff
- when profiling we don't actually unmap the code in order to not brake profiling
=> free bjit code after LLVM codegen

src/runtime/hiddenclass.h, src/runtime/objmodel.cpp
this fixes the huge (~350MB) leak in:
```
for i in xrange(1000000):
class C(object):
pass
```
=> hidden classes: free classes of singleton type

src/CMakeLists.txt, src/runtime/str.cpp, src/runtime/str_interning.cpp, src/runtime/types.h
We used to store the string content twice.
This implementation makes use of `DenseSet::find_as` functionality where one can search using a different type.
I was not sure if the special `DenseMapInfo` I had to create causes any problems so I choose to create a new source file for it so that it does not get picked up somewhere else.
---
mmh I'm not sure if we want to merge this change: 
- it looks like it's a much smaller memory usage improvement than I thought (only a few hundred kb) :-(
- perf is also about the same (maybe very slightly better)
@kmod what do you think?
=> string interning: make it slightly more space efficient

src/runtime/types.h
`_mm_prefetch(next, _MM_HINT_T0)` expands to `__builtin_prefetch(next, 0, 3)` which are the defaults of `__builtin_prefetch(next)` too.
Reason for this change is that we did not include `xmmintrin.h` and instead of pulling this header in everywhere I thought it's better too just use the compiler intrinsic directly
=> switch from the SSE prefetch to __builtin_prefetch

llvm_patches/0013-MCJIT-free-loaded-objects.patch
This fixes the llvm tier memory consumption until we migrate to the ORC JIT which has better memory management.
=> MCJIT: free loaded objects

from_cpython/Lib/distutils/ccompiler.py, src/runtime/import.cpp
I'm still hoping that we can keep this on in some way, because it continues to find issues.
So let's try keeping it on for debug builds.
I'm not sure if this is weakening the check enough (there may be other cases like scipy),
but it's sounding like we need to have this check turned off in our releases regardless,
such as issue #1344.
@undingen what do you think?
=> Turn off implicit-function check in release mode

src/capi/types.h, src/runtime/builtin_modules/builtins.cpp, src/runtime/builtin_modules/thread.cpp, src/runtime/code.cpp, src/runtime/code.h, src/runtime/frame.cpp, src/runtime/generator.cpp, src/runtime/inline/xrange.cpp, src/runtime/iterobject.h, src/runtime/set.cpp, src/runtime/set.h, src/runtime/super.cpp, src/runtime/tuple.h, src/runtime/types.cpp, src/runtime/types.h
performance is about the same (mostly noise), I think the BoxedCode change could get more important in the near future when we start to create much more of them
=> microptimizations: use DEFAULT_CLASS_SIMPLE, non gc code object, fewer handleFrameExit calls 

src/analysis/function_analysis.cpp, src/analysis/scoping_analysis.cpp, src/analysis/scoping_analysis.h, src/analysis/type_analysis.cpp, src/codegen/ast_interpreter.cpp, src/codegen/irgen.cpp, src/codegen/irgen/irgenerator.cpp, src/codegen/unwinding.cpp, src/core/ast.cpp, src/core/ast.h, src/core/bst.cpp, src/core/bst.h, src/core/cfg.cpp, src/core/types.h, src/runtime/cxx_unwind.cpp
this is mostly cleaning up stuff so it's easier to change the BST representation in the future.
also switched a few `std::vector<BST_expr*>` to   `BST_expr*` when we know it can only be a single element
=> AST & BST: remove unnecessary nodes and fields + little less memory usage

src/codegen/cpython_ast.cpp, src/codegen/cpython_ast.h, src/codegen/irgen/hooks.cpp, src/codegen/parser.cpp, src/codegen/parser.h, src/core/ast.h, src/core/cfg.cpp, src/jit.cpp, src/runtime/capi.cpp, src/runtime/import.cpp, test/unittests/analysis.cpp
Use a bumpptr allocator to keep track of the AST nodes.
I could not use the LLVM one because it does not call the destructor on allocated elements.
=> AST: deallocate nodes

from_cpython/Lib/compileall.py, from_cpython/Lib/distutils/core.py, from_cpython/Lib/py_compile.py, from_cpython/Lib/test/test_py_compile.py, from_cpython/Lib/test/test_sundry.py, from_cpython/Python/import.c, src/codegen/parser.cpp, src/codegen/parser.h, src/runtime/builtin_modules/builtins.cpp, src/runtime/builtin_modules/pyston.cpp, src/runtime/builtin_modules/sys.cpp, test/CPYTHON_TEST_NOTES.md, test/extra/numpy_fulltest.py, test/integration/virtualenv_test.py
Well, really an unmodified pip+setuptools
The last piece is py_compile.  Just shim that back into our parser
to get the parser to write out a pyc file.
It seems like we don't even need this -- most callers of py_compile
(or at least, virtualenv), don't seem to care if the compile step
passed or failed.  But while we're here, try to support it.
=> Be able to run an unmodified virtualenv

src/capi/abstract.cpp, src/capi/typeobject.cpp, src/runtime/types.cpp, test/tests/subclasscheck_test.py
We supported classes that overrode them, but didn't provide a
default implementation in case people called it by hand.
The tricky part is making sure that these new additions don't
mess with our "does this class override __instancecheck__" optimizations.
=> Add type.__instancecheck__ and __subclasscheck__

src/asm_writing/icinfo.cpp, src/runtime/hiddenclass.h, src/runtime/objmodel.cpp, src/runtime/set.cpp, src/runtime/types.cpp, test/integration/typing_test.py
typing.py likes to create lots of class objects, and it exposed an issue that we didn't properly invalidate ICs for freed class objects.
=> Add test for typing.py and fix the issues it uncovers

src/analysis/type_analysis.cpp, src/analysis/type_analysis.h, src/codegen/ast_interpreter.cpp, src/codegen/irgen.cpp, src/codegen/irgen/hooks.cpp, src/codegen/irgen/irgenerator.cpp, src/codegen/irgen/irgenerator.h, src/core/bst.cpp, src/core/bst.h, src/core/cfg.cpp, src/core/cfg.h, src/runtime/code.cpp, src/runtime/types.cpp, src/runtime/types.h, src/runtime/util.cpp
this sets the foundation for https://github.com/dropbox/pyston/pull/1381
=> move constants into CodeConstants, call BoxedCode destructor, cleanup BST nodes

src/runtime/types.cpp, test/extra/sqlalchemy_0.5_smalltest.py, test/tests/instance_methods.py
We had implemented instancemethod.__eq__, but not any of the other comparisons,
and most importantly, not __hash__.
=> Fix instancemethod comparisons

CMakeLists.txt, docs/MEMORY_PROFILING.md, test/extra/avro_test.py, test/extra/paste_test.py
After installing `sudo apt-get install libjemalloc-dev` [1] one can use jemallocs heap profiling with:
```
~/pyston$ MALLOC_CONF="prof:true,prof_prefix:jeprof.out" ./pyston_release minibenchmarks/raytrace.py
~/pyston$ build_deps/jemalloc/bin/pprof pyston_release jeprof.out.*
(pprof) top3
Total: 4.5 MB
1.0  22.2%  22.2%      1.0  22.2% pyston::BST_FunctionDef::operator new (inline)
0.5  11.1%  33.3%      0.5  11.1% pyston::DenseMap::allocateBuckets (inline)
0.5  11.1%  44.5%      0.5  11.1% pyston::CFG::addBlock
```
I could not measure any performance regression so I think we can just always compile it with profiling support.
[1]: Unfortunately it can't find the jemalloc header file - instead of finding out how to tell the configure script where to look at I just installed the jemalloc …
=> jemalloc: build with profiling support

LICENSE, cmake/CheckTypeSizeof.c.in, cmake/CheckTypeSizeof.cmake, docs/Doxyfile.in, docs/TIPS.md, from_cpython/Modules/_struct.c, from_cpython/Python/import.c, from_cpython/setup.py, src/asm_writing/icinfo.cpp, src/asm_writing/mc_writer.cpp, src/asm_writing/rewriter.h, src/codegen/ast_interpreter.cpp, src/codegen/ast_interpreter_exec.S, src/codegen/entry.cpp, src/codegen/irgen/irgenerator.cpp, src/codegen/opt/mallocs_nonnull.cpp, src/codegen/unwinding.cpp, src/runtime/complex.cpp, src/runtime/cxx_unwind.cpp, src/runtime/objmodel.cpp, src/runtime/types.cpp, test/CPYTHON_TEST_NOTES.md, test/integration/scipy_test.py, test/test_extension/slots_test.c, test/tests/delattr.py, test/tests/exceptions_test.py, test/tests/import_failure_test.py
Minus the ones to code that we inherited from CPython or LLVM,
in order to keep those diffs clean.
Closes #1389
=> Typo fixes from PR #1389

src/core/from_llvm/DenseMap.h, src/core/from_llvm/DenseMapInfo.h, src/core/stringpool.h, src/runtime/str_interning.cpp, src/runtime/types.h, test/tests/attr_ordering.py, test/tests/dict_ordering.py, test/tests/globals_ordering.py
Rather than switching to CPython's dict implementation, which would
be quite a bit of code changes (since we use our internal dict interface
a lot), change our current dict implementation to more-closely match CPython's.
In particular, change the growth strategy and probing strategy to match cpython's.
=> Get dict ordering closer to CPython's

src/analysis/function_analysis.cpp, src/analysis/type_analysis.cpp, src/codegen/ast_interpreter.cpp, src/codegen/codegen.cpp, src/codegen/irgen.cpp, src/codegen/irgen/irgenerator.cpp, src/codegen/irgen/irgenerator.h, src/core/bst.cpp, src/core/bst.h, src/core/cfg.cpp, src/core/cfg.h, src/runtime/generator.cpp, src/runtime/types.cpp, src/runtime/types.h, test/unittests/analysis.cpp
this is a modified version of https://github.com/dropbox/pyston/pull/1381 which creates the bytecode in-place and does not evolve duplicating some CFG structures.
- all instructions of the CFG are directly emitted a single memory region.
- all instructions are packed and follow each other directly
- the CFGBlock just point into the bytecode block where the first instruction of the block is located
- invokes are only a bit in the opcode field which when set means that the pointers to the normal and exc `CFGBlocks*` directly follow the normal instruction
=> transform BST to gapless bytecode inplace

src/asm_writing/disassemble.h, test/extra/M2Crypto_test.py, test/extra/avro_test.py, test/extra/babel_test.py, test/extra/cffi_1.7_test.py, test/extra/cffi_test.py, test/extra/cheetah_test.py, test/extra/formencode_test.py, test/extra/geoip_test.py, test/extra/lxml_test.py, test/extra/mysqldb_test.py, test/extra/numpy_fulltest.py, test/extra/paste_test.py, test/extra/protobuf_test.py, test/extra/pyicu_test.py, test/extra/pylons_test.py, test/extra/pyopenssl_test.py, test/extra/routes_test.py, test/extra/sass_test.py, test/extra/simplejson_test.py, test/extra/unidecode_test.py, test/integration/pycrypto_test.py, test/lib/test_helper.py, tools/tester.py
A common issue is that we see that a test goes from N failures to N+1,
but it's not clear at all which of the failures is new.
This adds a simple hashing mechanism to try to help us in these cases:
we hash each line in the log, and construct a small bloom filter of
which lines were seen.  We can then put this into the test file, and
when the test fails we can run the received output against the expected
bloom filter.
I tried testing it and it seems ok, but we'll have to see how well it
works in practice.
=> Add "log hashing" to see new failures

from_cpython/Include/Python.h, from_cpython/Modules/gcmodule.c, src/analysis/scoping_analysis.cpp, src/analysis/scoping_analysis.h, src/runtime/dict.cpp, src/runtime/types.cpp, test/tests/exec_set_local.py, test/tests/name_scopes.py
Previously we only thought this was true for bare execs,
but this is important for `exec s in {}, locals()` since
it is allowed to change the locals in a way that should
get picked up.
=> All execs force "name" lookup behavior

src/asm_writing/assembler.cpp, src/asm_writing/assembler.h, src/asm_writing/rewriter.cpp, src/asm_writing/rewriter.h, src/codegen/ast_interpreter.cpp, src/codegen/baseline_jit.cpp, src/codegen/baseline_jit.h, src/codegen/codegen.h, src/codegen/irgen/irgenerator.cpp, src/codegen/runtime_hooks.cpp, src/codegen/unwinding.cpp, src/core/cfg.h, src/core/types.h, src/runtime/frame.cpp
- this transforms all stores from 64bit to 32bit
- but more importantly removes a lot of embedded pointers and replaces them with constant integers which lets llvm use smaller opcodes.
- had to teach our assembler how to generate 32bit stores
```
django_template3.py             2.4s (6)             2.4s (4)  +0.3%
pyxl_bench.py             2.1s (6)             2.1s (4)  -1.9%
sqlalchemy_imperative2.py             2.6s (6)             2.5s (4)  -1.2%
pyxl_bench2.py             1.1s (6)             1.1s (4)  -1.9%
pyxl_bench_10x.py            16.7s (6)            16.5s (4)  -1.4%
django_template3_10x.py            11.8s (6)            11.5s (4)  -3.0%
sqlalchemy_imperative2_10x.py            18.0s (6)            17.9s (4)  -0.4%
pyxl_bench2_10x.py             9.3s (6)             8.8s (4) …
```
=> FrameInfo: store current statement as offset from the bytecode start

src/codegen/compvars.cpp, src/codegen/compvars.h, src/codegen/irgen/irgenerator.cpp, src/codegen/irgen/util.cpp, src/codegen/irgen/util.h, test/tests/is.py
before the llvm JIT returned in some cases `const is const` `False` where the other tiers returned `True`.
=> llvm JIT: better handling of `const is const` & less unboxing calls

src/codegen/ast_interpreter.cpp, src/codegen/codegen.cpp, src/codegen/irgen.cpp, src/codegen/irgen/hooks.cpp, src/runtime/types.h
```
django_template3.py             2.5s (4)             2.5s (4)  +1.0%
pyxl_bench.py             2.1s (4)             2.1s (4)  -0.3%
sqlalchemy_imperative2.py             2.6s (4)             2.6s (4)  -0.3%
pyxl_bench2.py             1.0s (4)             1.0s (4)  -0.9%
pyxl_bench_10x.py            16.4s (4)            16.0s (4)  -2.3%
django_template3_10x.py            11.5s (4)            11.5s (4)  +0.0%
sqlalchemy_imperative2_10x.py            18.1s (4)            17.6s (4)  -2.8%
pyxl_bench2_10x.py             8.5s (4)             8.2s (4)  -4.0%
interp2.py             2.5s (4)             2.5s (4)  -1.7%
raytrace.py             5.6s (4)             5.4s (4)  -3.6%
nbody.py             8.0s (4)             7.8s (4)  -3.2%
fannkuch.py             6.9s (4)             7.0s (4) …
```
=> OSR: enable type specialization

from_cpython/Lib/test/test_ssl.py
cpython's tests don't reply on it since v2.7.12, so i think we should just disable it until we updated to 2.7.12.
=> disable some tests on test_ssl.py since svn.python.org's cert is expired now

src/runtime/str.cpp
I love the Pyston's useful strategey about an one length string and an empty string.
But some operations are did not using this lovely strategy. so I change it to avoid unnecessary operations.
And I checked Travis CI were passed except Avro integration tests, but I found that it happens on master branch. so it is not related with this PR.
=> Micro optimizations for string operations.
